### PR TITLE
Issue 5071 - Repeater. DC Link

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #5071 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [x] Test if DC link adds to all columns in repeater (example from issue)
-   [x] Test if DC status still works as expected with repeater (is not inherited from one column to another)
-   [ ] Test LinkControl in general, check if everything works as expected
-   [ ] Test migrator (more info in comments)

**_ Pre-Code Testing _**

-   [ ] Test if DC link adds to all columns in repeater (example from issue)
-   [ ] Test if DC status still works as expected with repeater (is not inherited from one column to another)
-   [ ] Test LinkControl in general, check if everything works as expected
-   [ ] Test migrator (more info in comments)
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors

### Summary by CodeRabbit

Release Notes:

- New Feature: Added support for dynamic content links in the LinkControl component.
- Bug Fix: Fixed an issue where the title property of newLinkSettings was not updated correctly in certain conditions in the withMaxiDC higher-order component.
- Refactor: Moved the DC_LINK_BLOCKS array to a separate file and imported it in the Link component and excludeAttributes module for better modularity.
- Style: Updated CSS styles for the LinkControl component, including the width, background color, and color of various elements.
- Documentation: Improved the documentation of the getBlockNameFromUniqueID function in the utils module.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
Main issue is fixed)

1) should we create a migrator or it is unneeded for old patterns? We don't have a lot, but customers can have
https://jam.dev/c/aed0c627-a5e0-4bb5-92a9-62a384e84fa8
https://jam.dev/c/29f0a0d4-a816-4985-b564-8d0e4fb9504a

few questions - should create for it separate issues?
2) for some of the blocks ( row, column, group,... need to check all ) toolbar"s link icon doesn't change colour to active 
https://jam.dev/c/40a1025a-e474-4314-874c-1ed839d8f8c4 
3) I guess, we should not have ability to add custom link, if for this block enabled DC, because custom link is not working if enabled DC link. But it is working, if DC link is disabled. Idk should we leave this ability for customers or it will confuse them?
https://jam.dev/c/0f63530a-317f-474e-bee3-7513a2fb1675 
4) create row > enable CL > add DC block ( image for example ) > enable DC link > click to any another block > click again to this image > click to link`s icon > "Remove link" button doesn`t work if DC link is enabled
https://jam.dev/c/103ce0c1-f629-4aa3-b057-67c66db44768

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) need ti hide/unhide input field in the moment enabling/disabling toggle button for DC link
https://jam.dev/c/5fa21614-c545-4e54-8f86-f16412d4c059
like for Svg, For svg is working good https://jam.dev/c/4760f16d-4217-4e8e-bad7-b393231c0455
2) "Remove link" and edit buttons  are disappeared for custom link as well ( old links )
image
[old links.txt](https://github.com/maxi-blocks/maxi-blocks/files/12548288/old.links.txt)
3) Need to add these toggle buttons when we are using DC links
image

image

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://github.com/maxi-blocks/maxi-blocks/issues/4978
I`d it is related to point 1 from previous comment

image

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
2 things - version and uniqueIds

**Review by elzadj — APPROVED** [review]

**Pull request merged**
