### PR TITLE
Issue 5101 - Text list source text styles problems fix

### LINKED ISSUE #5101: Text list. Wrong indent
### Description

_No response_

### Step-by-step reproduction instructions

1) Create long ( 2 lines ) text list ( list style position - outside )
2  unordered list > custom > source - text
3) check indent for first and second text line

### Screenshots, screen recording, code snippet

image

https://jam.dev/c/0412c0ab-f954-4834-a565-618233483e21

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #5101 

# How Has This Been Tested?

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/899d84ba-b066-4eb4-abfb-c519ffdde73e

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test is problem from issue disappeared
-   [ ] Test marker size setting with text as source
-   [ ] Test marker size setting with other sources, styles
-   [ ] Test how styles behave on other list item settings change with different sources, styles

**_ Pre-Code Testing _**

-   [ ] Test is problem from issue disappeared
-   [ ] Test marker size setting with text as source
-   [ ] Test marker size setting with other sources, styles
-   [ ] Test how styles behave on other list item settings change with different sources, styles
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors

## Summary by CodeRabbit

- **New Features**
  - Introduced a new search functionality with a timeout for improved text style positioning.
  - Added new utility functions to calculate text width and determine text source.

- **Enhancements**
  - Updated text editing capabilities to support additional styling options.
  - Improved style card update logic for better performance and accuracy.

- **Bug Fixes**
  - Implemented a fix for the text style position check by adding a delay.

- **Refactor**
  - Refactored `MaxiBlockComponent` to use modern async/await syntax for updating styles.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
image

is not correct for OUTSIDE , Source text and URL

**Review by Olekrut — CHANGES_REQUESTED** [review]
marker indent does not work correct
https://jam.dev/c/7e590818-2404-4b0a-8197-4a0ca2e34a51

**Comment by Fybex** [comment]
> marker indent does not work correct https://jam.dev/c/7e590818-2404-4b0a-8197-4a0ca2e34a51

This also didn't work in master, but I fixed it here, so now this PR should be tested much more strictly as it can now affect many more patterns and cases. Check it out more deeply @Olekrut in different cases with different patterns with lists 🙏

**Review by Olekrut — CHANGES_REQUESTED** [review]
Check lists on PTL-02.
image

Looks like fixed, but now, I am feeling, that need remake patterns, right?

**Comment by Fybex** [comment]
> Check lists on PTL-02. image

Fixed `none` list style, PTL-02 from now should look as before.

> Looks like fixed, but now, I am feeling, that need remake patterns, right?

If you find any other patterns that don't look the same as before, then yes...

**Review by Olekrut — APPROVED** [review]
Looks ok on WP 6.3.1, but not good on WP 6.4.1
so will hope that it will help

**Comment by Fybex** [comment]
@Olekrut recheck deeply list styles fix from the start please

If new styles computation logic is alright, then check if there are no patterns, which should be remade before approving 🙏

**Review by Olekrut — APPROVED** [review]

**Pull request closed without merging**
