### PR TITLE
Issue 2428 bg shape

### PR DESCRIPTION
**Pull request by elzadj**
Fixes #2428

### CODE REVIEW

**Review by Alejandro9kgm — COMMENTED** [review]
The responsive test is not correct, as we expect the same value of 100 in all expect.

**Review by Alejandro9kgm — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
On adding an image, the colour tab and the SVG disappears

https://user-images.githubusercontent.com/50477222/146950445-6604c7a5-c9e3-4b91-a9b0-80e3cb83fede.mp4

**Review by Naaaaiix — COMMENTED** [review]
Cool, I like the toggle idea, much cleaner and easier. Couple of comments:

1. For a better user experience, may we add a 'state' to keep the image url in case creators decide to put an image, then remove, and come back to it again. What do you think?
2. Didn't we fix the SVG image to fit all the height? Found this, not sure if is a bug:
Captura de pantalla 2022-01-10 a las 13 00 23

**Review by Naaaaiix — APPROVED** [review]
Cooooool 😸

**Pull request merged**
