### PR TITLE
Issue 3270 - transformControl targets

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
TransformControl now can apply to different targets.

Fixes #3270 

# How to test?
Try setting transform to different targets on different blocks.

# Test checklist

**_Front/Back Testing_**

-   [x] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_Pre-Code Testing_**

-   [x] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — CHANGES_REQUESTED** [review]
Works well. Only one thing; can we have indicators for the dropdown? When you navigate off and come back to the settings, you have to choose again the element from the dropdown, so it would be good to know what exactly has been changed.
Screenshot_9

**Review by Marko64 — APPROVED** [review]
Thanks, better now with the indicators.
I've noticed that the transform tab indicator is missing too - but that may be for a different PR.

**Review by Fybex — APPROVED** [review]
Amazing job, approving  🥳🎉, but I have some small things to consider:
1. `transform` attributes was changed globally, should we have `migrator` for this or `migrator` creation will take more time than set it again by hands?
2. For me, it's not comfortable to set a target every time I switch between breakpoints or closing/opening accordion. As I know, before some of our meetings this PR had attributes for last target, but it was removed after @Naaaaiix  suggestion, should we back it? CustomCss and Transitions have this type of attributes 🤔
3. I can't see dropdown indicators on `macOS`🥲

**Review by Naaaaiix — COMMENTED** [review]
> For me, it's not comfortable to set a target every time I switch between breakpoints or closing/opening accordion. As I know, before some of our meetings this PR had attributes for last target, but it was removed after @Naaaaiix suggestion, should we back it? CustomCss and Transitions have this type of attributes 🤔

Do they? oh, my fault @TeksPeks, I requested you to remove it and it's in other part 😅 . Let's do this:
1. Reimplement it (soooooorrryyyyyy!!!).
2. We'll create an issue for it. We need to have as few attributes as we can, so what we should do (IMO) is to integrate these selectors into the same store state as we have the accordions and the tabs, so that way 1) it will keep the value when switching from one block to another 2) won't rely on attributes 👍 

The reason why we don't want to rely this information on attributes is to avoid having oversized patterns that will need bigger data size on the API requests 👍 

PS: this is not a review of the PR, just comments 👍

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Found this issue on frontend. Check it out please 😄 

https://user-images.githubusercontent.com/50477222/174071801-3c6565c5-6269-4c40-91eb-db1738d0c733.mp4

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Still finding bugs. Going to ask 2 things:
1. Going to restart the review process, as the bugs I'm finding are a front/back tests, no coding.
2. The code is so good `src/components/transform-control/index.js`, but at least for me is long and complex to read. Can you please divide it into smaller and more understandable pieces, or put comments? It would help massively on it 👍 Thanks!



https://user-images.githubusercontent.com/50477222/174338889-0bb86731-a024-448c-955d-ac6a222bcd1a.mp4

**Review by Marko64 — CHANGES_REQUESTED** [review]
Founds this issue too. Seems that before and after target things globally:
after-canvas
before-canvas
before-canvas

**Review by Marko64 — APPROVED** [review]

**Review by Fybex — CHANGES_REQUESTED** [review]
We need toggle in hover state as we have in all other controls with hover. Because now for example you're changing scale to 120 in normal state, switch to hover and there you have 100, but it's not working until you change it

**Review by Fybex — CHANGES_REQUESTED** [review]
Hover not working until value changes, but it must

**Review by Fybex — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
Lovely job: clean, simple in its complexity, and super powerful. Is a job of a 10/10, congrats @TeksPeks, you should be proud of this art piece 🎨 👏 💯 🎉 

Buuuuuuut... there's a but! We need a migrator my friend 😭 I'm going to approve it, as this job is magnificent, but the migrator is mandatory. I recommend you to create a branch from this current one, and create a PR pointing here, this way we'll just review the migrator, and then we can merge this one 👍

**Review by Fybex — APPROVED** [review]

**Review by Marko64 — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Review by FitseTLT — APPROVED** [review]

**Pull request merged**
