### PR TITLE
Issue 2197

### PR DESCRIPTION
**Pull request by javadsamiee**

### CODE REVIEW

**Review by kyrapieterse — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Good job 👍

**Review by Naaaaiix — APPROVED** [review]
Well done 🥳 let's apply to the rest of blocks 💪 😸

**Review by Alejandro9kgm — COMMENTED** [review]
The icon you choose does not remain when changing button styles.

https://user-images.githubusercontent.com/58038966/138082262-22c76966-c90e-4765-978d-893b801c0feb.mp4

The width only works up to 63

https://user-images.githubusercontent.com/58038966/138082396-6e543397-8999-4dee-aa3e-6efa9ccdf158.mp4

The padding icon can be negative

 

https://user-images.githubusercontent.com/58038966/138082752-dc58b626-dcdc-4e98-ad9b-1b092551c755.mp4

**Review by Naaaaiix — COMMENTED** [review]
Congrats @javadsamiee , such a hard job! Let's fix some minor bugs 😸 

Backend issues:
1. Please, leave tests and snapshots tests as they are on master; if not, Alejandro won't have a point of reference to see the changes on the snapshots, and will make his job much harder.

Frontend issues:
1. Block appears fullwidth without the setting enabled:
Captura de pantalla 2021-10-20 a las 13 25 36
2. Map Maxi block breaks

**Review by Naaaaiix — COMMENTED** [review]
Please @javadsamiee , return the snapshots of the tests to the original to let @Alejandro9kgm start fixing the tests 🙏

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Let's see:
1. I've requested to you to come back all e2e tests to the original one to let @Alejandro9kgm start with the tests. As this PR is a priority, every time I have to repeat is a delay of time. This is 3rd time. Please, come back `e2e-tests/blocks/button-maxi/index.spec.js` and `e2e-tests/utils/test/__snapshots__/getBlockAttributes.js.snap` to its originals. In other PRs you've showed some troubles related with the tests, so if you don't want to deal with them and leave Alejandro do it, please make it easy for all 👍 
2. Considering this implementation is big by itself, why do you add another fix for other issue without commenting anything and without making @elzadj and @Alejandro9kgm review it? This is not a good workflow and make us add code without the review standards we are trying to apply to ensure a good code and avoiding errors. Not agree with this implementation and the way it has been done. Please, get the code of the issue #2225 and set it in another branch to get it out from this PR. If in order to fix that issue you need this current implementation, create a branch from here and then point the merge of the new branch to this current branch.

**Review by Naaaaiix — APPROVED** [review]

**Review by kyrapieterse — APPROVED** [review]

**Review by Alejandro9kgm — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
