### PR TITLE
New styles for plugin UI

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Alternative to https://github.com/maxi-blocks/maxi-blocks/pull/5077

Fixes # (issue)

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### Summary by CodeRabbit

- New Feature: Introduced a new `newStyle` prop to various components to enable alternative styling options.
- Refactor: Adjusted CSS styles across multiple components for improved visual appearance and user experience. Changes include modifications to padding, margin, border, color, and layout.
- Style: Added a new CSS variant `__second-style` for `maxi-advanced-number-control` and `maxi-base-control` components, providing an alternative visual style.
- Chore: Removed commented out CSS properties and unused code for cleaner codebase.
- Bug Fix: Corrected the `default` value and argument type for the `maxi_ai_business_name` setting in `class-maxi-dashboard.php`.
- New Feature: Added `hasMarginBottom` prop to certain components for better control over component spacing.

### CODE REVIEW

**Comment by elzadj** [comment]
- remove commented out code in css
- check some css files, there is no empty line at the end (need to re-save them) 
- the text is cut off:
screenshot-wordpress local-2023 09 21-17_09_37
- need to add newStyle to prompt after we merge

**Comment by elzadj** [comment]
Prompt maxi was merged to master, so you also can do

- need to add newStyle to prompt after we merge

**Comment by Fybex** [comment]
@elzadj, cleaned style files. I did not find where to add `newStyle` in prompt-maxi, there are not many components with this prop, and for example, for ANC `newStyle` prop does not need to be added, because ANC in prompt-maxi has a range control 👍

**Comment by elzadj** [comment]
@Fybex please make the ReactSelectControl styles the same as SelectControl.
this drowdown 
screenshot-wordpress local-2023 10 09-13_22_29

should look like this:

screenshot-wordpress local-2023 10 09-13_22_00

**Comment by Fybex** [comment]
> @Fybex please make the ReactSelectControl styles the same as SelectControl. this drowdown screenshot-wordpress local-2023 10 09-13_22_29
> 
> should look like this:
> 
> screenshot-wordpress local-2023 10 09-13_22_00

So now it looks like this in prompt-maxi:

P.S. We don't need here reset buttons I think, at least for the moment 👍 

Also, I've changed focused colours in `FontFamilySelector` component to make it look the same with `ReactSelect`s in prompt-maxi and SC.
And also creating a low priority issue to use `ReactSelectControl` in `FontFamilySelector` as well, also in that issue we can add some not highly important design improvements to select design if @kyrapieterse has some ideas 👍 

Screenshot 2023-10-09 at 21 15 36

**Comment by elzadj** [comment]
The prompt looks great, thanks

**Comment by kyrapieterse** [comment]
really hard to see the selected colour. make it the darker grey border around the selected colour

image

**Review by Olekrut — CHANGES_REQUESTED** [review]
I like rounded styles. A few points:
1) I`d make more contrast colour for this border, almost don't see it and looks weird
image
2) the same here
image
image
3) weird border ( oval ) is it correct?
image
4) so small font-size) can be a bit bigger? 
visually impaired people will need a magnifying glass
image
5) a bit to extend opacity for placeholder texts like this 
image
6) Weird border only for  hover-out https://jam.dev/c/01032ae2-3be9-4414-a3e2-869f320484c2
7) and is not so important, we dont have it now as well. But would be pretty to add transition to all hovers

**Comment by kyrapieterse** [comment]
2. the point of the light colour is to make it look less intence with so many settings I think its ok. 4. The font size is the same as elelemntor. 7.no transitions

lets fix the rest

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) arrow and cross have another colour than all others arrows like it
image
2) Circle with colour touches to line under it ( for all set custom colour )
image
maybe should be like these?
image
3) need padding
image
will be ok after merge?
it was fixed by Marko in this PR https://github.com/maxi-blocks/maxi-blocks/pull/5167
4) font-size for settings labels does not changed in sidebar ( 8px ). It is 10px only for SCs sidebar
image
5) disabled sync for overflow is invisible, need to extend opacity for it
image
6) For all sync buttons need to make the same styles as for overflow
image
7) Sync axis control buttons have wrong size for position tab
image
8) inactive text should be more contrast, not only for this screenshots ( check everywhere )
image
image

**Comment by kyrapieterse** [comment]
1. Its fine MVP
2. madde it smaller. doesnt need the select border as its only showing one colour MVP
3. done
4. seems done
5. feels unimportant - make new issue
6. feels unimportant- make new issue
7. done
8. 👀🤔

image

**Comment by Olekrut** [comment]
4) not for all. For example Icon alt
image
7) no, they smaller then others
image
image

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — COMMENTED** [review]
Approved, let's w8 for tests and merge

**Pull request merged**
