### PR TITLE
Issue 5155 - Update `uniqueID` on code editor paste

### LINKED ISSUE #5155: Bug with displaying frontend on different pages
### Description

Master

There are problems with IB as well. Check Team pro-118
https://2devdemo.maxiblocks.com/pure-team-light-ptml-pro-part-12/
https://2devdemo.maxiblocks.com/pure-team-dark-ptmd-pro-part-12/

### Step-by-step reproduction instructions

1) create page 1
2) create container or paste pattern from attached code
3) create page 2
4) copy container from page 1 and paste to page 2
5) change media( BG Layer image (simple image block is ok)) and tone  on page 2 and update
6) check frontend on page 1, there will display container from page 2

### Screenshots, screen recording, code snippet

[styles.webm](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/53ccad50-fd20-4ae5-9d6a-c4ebec672243)

### URL and/or Code editor

[SML-pro-114.txt](https://github.com/maxi-blocks/maxi-blocks/files/12658334/SML-pro-114.txt)

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #5155 

The problem was in the fact, that two code editors(from video in issue), which were pasted into two different pages were having the same uniqueIDs, because of this their styles, IB were affecting each other. Now on inserting code editor it changes uniqueIDs, so that effect should disappear.

P.S. old posts are going to be broken, writing migrator will add a lot of unnecessary calculations, don't see a need in this for the moment, so to fix it for already created posts: copy code editor of one post and repaste it. Then update both posts and everything should be fine 👍 

# How Has This Been Tested?
Checked if new `uniqueID` generates on code editor paste and template insertion.

# Test checklist

**_ Front/Back Testing _**

-   [x] Repeat steps from video from issue, check if it's not anymore repeatable

**_ Final-Code Testing _**

-   [x] Repeat steps from video from issue, check if it's not anymore repeatable
-   [x] Check if new `uniqueID` generation conditions/logic works as expected (if it doesn't recalculate uniqueID when it's not necessary, for example when block duplicates, etc)
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors

### Summary by CodeRabbit

- New Feature: Introduced a unique ID generation mechanism for blocks to ensure uniqueness even when copied.
- Refactor: Enhanced the `uniqueCustomLabelGenerator` function to generate unique labels based on custom label and unique ID inputs.
- Bug Fix: Improved class name replacement logic in `edit` class of SVG Icon Maxi block for better accuracy.
- Test: Updated test suite for repeater component with a new sanitization function for more accurate assertions.
- Refactor: Added new helper functions in `getCustomLabel` for sanitizing unique IDs and previous custom labels.
- New Feature: Added an action to check if the current post is clean in the maxi-block store.
- Refactor: Updated reducer in the maxi-block store to handle actions related to adding and removing blocks.
- New Feature: Added a new selector function `getIsNewBlock` to check if a block is new based on its unique ID.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
For new created blocks are working
https://jam.dev/c/ebafbbb0-d617-476f-87b0-355dc94a269f
Are not fixed for old patterns

**Comment by Olekrut** [comment]
https://jam.dev/c/0b530d65-c12a-4938-8a21-39ce19a28d2f
Error after copy/paste to new page

**Review by myroslavve — APPROVED** [review]

**Comment by Fybex** [comment]
> https://jam.dev/c/0b530d65-c12a-4938-8a21-39ce19a28d2f Error with svg and divider after copy/paste to new page, only this brunch

It's a legacy from the change of uniqueID form, but in any case with new added changes this bug appears more often, so fixed it, thanks @Olekrut. And @TeksPeks, rechecked front and code side as well please 🙏

**Review by Olekrut — APPROVED** [review]

**Review by myroslavve — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
The branch changes Custom labels like "Pure Team Light PTML-PRO-60" to generic labels, like "Container_2" , when you import something from the Template Library Maxi. 

We need to keep the old custom labels, they hold important information, like images sizes, etc.

**Comment by Fybex** [comment]
> The branch changes Custom labels like "Pure Team Light PTML-PRO-60" to generic labels, like "Container_2" , when you import something from the Template Library Maxi.
> 
> We need to keep the old custom labels, they hold important information, like images sizes, etc.

So now it keeps old custom labels, if old custom `customLabel` is repeated, then it adds `_${uniqueIndex}` to the end

**Comment by elzadj** [comment]
Need to figure out the repeater tests

**Review by elzadj — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
