### PR TITLE
Row Snapping Feature 

### PR DESCRIPTION
**Pull request by abder**
This pull request presents the feature of row responsive snapping but it still needs extensive testing before merging, which what I need your help with guys. 

Please check it out and comment any issues and suggestions 

Thanks!

### CODE REVIEW

**Review by javadsamiee — COMMENTED** [review]
Good job man for your hard work.

That was good,  I think we need to add an active class for the current selected item because there are lots of items, and finding the current item is hard.

A question: Did you do for responsive modes? I think it's working on a desktop

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Good job men, is a big one this!

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Much better!

**Review by Naaaaiix — APPROVED** [review]
Much better!

**Pull request merged**
