### PR TITLE
Issue:4653 Added background shape rotate scale flip settings

### PR DESCRIPTION
**Pull request by FitseTLT**
# Description
Added background shape rotate scale flip settings

Fixes #4653

# How Has This Been Tested?
Add Background shape layer and check scale rotate and flip settings for both hover and non-hover

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/253b1c34-a1ae-40b1-bbf1-e8431b76b702
You don't should make scale instead of width, just rename, because now position is not working!
2) https://jam.dev/c/e26691c9-624d-4fbe-99db-ba16d493627c
click reset value of scale > getting empty field

**Review by Olekrut — CHANGES_REQUESTED** [review]
about first point)) 
ok, it is master) try to do the same on your brunch
https://jam.dev/c/9ad30dba-d419-4803-b7cb-64b4b650768a


in this case scale shape should change height and width ( should be px, %, em, vw), it should not work as transform scale
and height and width should be equal

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) remove height
2) rename "Width" to "Height and Width"
3) and this field should change together height and width ( maybe to add aspect-ratio:1; for maxi-background-displayer__svg)

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
no, it is not equal for %,  for px, em, vw is ok

**Review by Olekrut — CHANGES_REQUESTED** [review]
Awesome)) 
transition is not working for this settings
image

**Review by Olekrut — APPROVED** [review]

**Review by darimshlk — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
