### PR TITLE
Issue-2458 : Indicators follow up

### PR DESCRIPTION
**Pull request by bilouStrike**
Fixes: #2458

### CODE REVIEW

**Review by Naaaaiix — COMMENTED** [review]
To fix the tests add 'skip' to the last 2 `it` of the Button Maxi tests 👍

**Review by Marko64 — APPROVED** [review]
Perfect.

**Review by FitseTLT — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Column size is marked as changed; what was the plan with it finally? 🤔

**Review by Naaaaiix — APPROVED** [review]
Ready for merge, fixed the test 👍

**Review by elzadj — APPROVED** [review]

**Pull request merged**
