### PR TITLE
Issue 5248 - reusable blocks styles

### LINKED ISSUE #5248: Remove default styles for reusable blocks
### Description

First screenshot - backend
Second screenshot - frontend

### Step-by-step reproduction instructions

1) add some full-width pattern
2) make reusable block

### Screenshots, screen recording, code snippet

1) 
image
2) 
image

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description

Used CSS `:has()` selector this time, since it is finally supported by all the desktop browsers.
Also removed some code that was supposed to fix problems with reusable blocks, specifically https://github.com/maxi-blocks/maxi-blocks/pull/4967#issuecomment-1701418671 and https://github.com/maxi-blocks/maxi-blocks/pull/4967#issuecomment-1702843990, but checked and seems those problems are not present.

Fixes #5248 

# How Has This Been Tested?
Checked that reusable blocks look the same as normal blocks on editor and frontend, and don't have errors.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check that reusable blocks look the same as normal blocks on editor and frontend.
-   [ ] Check https://github.com/maxi-blocks/maxi-blocks/pull/4967#issuecomment-1701418671 and https://github.com/maxi-blocks/maxi-blocks/pull/4967#issuecomment-1702843990

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Enhanced the `MaxiBlock` component to support full-width styles for reusable blocks.
- **Style**
	- Updated CSS for better targeting and styling of elements within the maxi-themes banner.
- **Refactor**
	- Improved attribute handling logic for blocks to consider parent blocks' attributes.
	- Simplified the `MaxiBlockComponent` by removing unnecessary logic and optimizing style handling methods.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) Error. Make reusable patterns on master ( On video: HOL-PRO-120 and Team-pro-121 )  and change to this brunch after
https://jam.dev/c/c94aa2bb-009e-42ae-9175-a3697e32bd69
image
2) All patterns after load with error
https://jam.dev/c/8587edb9-9449-4b43-8452-69f12dee4b89

**Comment by elzadj** [comment]
ok, I think this one + my PR with some other fixes should fix https://github.com/maxi-blocks/maxi-blocks/issues/5502 , or at least help with it. @Olekrut please review this one ASAP, thanks.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) check how looks reusable blocks after insert, synced and not synced)
https://jam.dev/c/fba51dd5-7749-4489-b2d9-b05f4be93c99
2) the rendering after insertion is correct, but after closing the styles are broken, you have to click on each one for the correct view
https://jam.dev/c/584638ed-b39f-4c04-acec-7ce255f05798

**Comment by elzadj** [comment]
> 1. check how looks reusable blocks after insert, synced and not synced)
>    https://jam.dev/c/fba51dd5-7749-4489-b2d9-b05f4be93c99
> 2. the rendering after insertion is correct, but after closing the styles are broken, you have to click on each one for the correct view
>    https://jam.dev/c/584638ed-b39f-4c04-acec-7ce255f05798

That's a different issue https://github.com/maxi-blocks/maxi-blocks/pull/5498

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/f40d1489-1294-4c22-8313-050a058474a1
 error, when we have old reusable on page before adding new

**Comment by myroslavve** [comment]
> https://jam.dev/c/f40d1489-1294-4c22-8313-050a058474a1 error, when we have old reusable on page before adding new

Cannot reproduce the error or styles problem, and on frontend reusable blocks are the same as regular, so the styles on frontend issue isn't related to reusable blocks.

**Comment by myroslavve** [comment]
> > https://jam.dev/c/f40d1489-1294-4c22-8313-050a058474a1 error, when we have old reusable on page before adding new
> 
> Cannot reproduce the error or styles problem, and on frontend reusable blocks are the same as regular, so the styles on frontend issue isn't related to reusable blocks.

Fixed the frontend issue. And as for the error on the editor, still couldn't reproduce + the message suggests that it was error in `loadable-components` library, it seems to happen in some builds, maybe if you build again the error won't be there...

**Comment by elzadj** [comment]
> > > https://jam.dev/c/f40d1489-1294-4c22-8313-050a058474a1 error, when we have old reusable on page before adding new
> > 
> > 
> > Cannot reproduce the error or styles problem, and on frontend reusable blocks are the same as regular, so the styles on frontend issue isn't related to reusable blocks.
> 
> Reproduced and fixed the frontend issue. And as for the error on the editor, still couldn't reproduce + the message suggests that it was error in `loadable-components` library, it seems to happen in some builds, maybe if you build again the error won't be there...

yeah, looks like a failed build, some files are missing, even the style-index.css file
@Olekrut try this: 

- [ ] close all editor pages opened on your local
- [ ] switch to that branch
- [ ] stop all ```npm start``` if you have it running
- [ ] remove the build folder from the plugin
- [ ] ```npm run build```
- [ ] wait for it to finish (should be a green message ```webpack xxxx compiled successfully in xxxx ms```)
- [ ] try the editor (you may need to clean your browser cache)

Or maybe you also need to do ```npm i --legacy-peer-deps``` to re-install the packages, if the above doesn't help.

**Review by Olekrut — CHANGES_REQUESTED** [review]
WP 6.4.3
https://jam.dev/c/1eefd8a0-0d4a-489a-acd2-dc2b78274126
add to new page few reusable patterns, close insert > styles are broken > sv said it is related with it issue https://github.com/maxi-blocks/maxi-blocks/pull/5498#pullrequestreview-1938856640

**Comment by elzadj** [comment]
> WP 6.4.3 https://jam.dev/c/1eefd8a0-0d4a-489a-acd2-dc2b78274126 add to new page few reusable patterns, close insert > styles are broken > sv said it is related with it issue [#5498 (review)](https://github.com/maxi-blocks/maxi-blocks/pull/5498#pullrequestreview-1938856640)

It happens when you browse patterns in the Block Inserter and then close Block Inserter

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
