### PR TITLE
3951-transform-control-translate-bad-drag-experience-with-not-units

### PR DESCRIPTION
**Pull request by MeltingWings1**
# Description

- Converted all units to move the same number of pixels on mouseMove.
- Added a slight delay on mouseOut to prevent jaggy experience when moving the mouse fast

Fixes #3951

# How Has This Been Tested?

On transform translate, drag the box with different units for x and y.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]
I think this is good for now.

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/cde1edda-8a49-47b6-b676-221614c4f570

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/787165a7-c00d-4cb3-8335-3cf32bf09614

Awesome) It is working much better with all units except %

**Review by Olekrut — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
image

after using transform, get Warning

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]

**Pull request merged**
