### PR TITLE
Issue 4519 - Implement SC CSS served from JS instead static CSS

### PR DESCRIPTION
**Pull request by Naaaaiix**
## Update
Fixed an issue where the Button Maxi wasn't having responsive styles coming from SC; detected via @ckp267 [comment](https://github.com/maxi-blocks/maxi-blocks/pull/4750#issuecomment-1514960737)

# Description

This branch implements a new system to load SC CSS styles. Basically we were implementing all CSS for SC from a SASS file that was creating ~400KB of code that in most cases wasn't necessary. What this PR does is:
1. Removed the CSS for SC from the main static CSS file (`styles.css`), reducing its size from ~540KB to ~100KB.
2. Creates the SC CSS strings using JS, and it creates the necessary CSS for the SC settings that has value, so it creates just the necessary code 👍 

This implementation is a MVP that can be much more optimized, and the code is not the best 👍 

Fixes #4519 

# How Has This Been Tested?

1. Use `wp.data.dispatch('maxiBlocks/style-cards').resetSC()` to reset SC on DB from the console.
2. Then use Maxi normally, testing SC for different values and for responsive.

I recommend using the Playground page for SC on Library 👍 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test everything related with SC

**_ Pre-Code Testing _**

-   [ ] Test everything related with SC
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) wrong font-family for Default SC, if change font-family, getting right
image
for all blocks
FRONTEND

2) font-size for button is not working
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
colours for links is not working
image

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]
Great job @Naaaaiix 
But I feel better if @Marko64 or @dashaversha also test for the bugs in general before we merge :smile_cat:

**Review by Marko64 — APPROVED** [review]
Deleted the docker container and started a new one and it worked 🙄 

Things looking good! CSS is only 100kb now and everything seems to be normal.

**Review by darimshlk — APPROVED** [review]

**Pull request merged**
