### PR TITLE
Load pattern and Select icon buttons

### PR DESCRIPTION
**Pull request by Rustam198804**
# Description

Fixes #4031

### CODE REVIEW

**Review by elzadj — CHANGES_REQUESTED** [review]
Need to fix that weird ```test``` class :+1:

**Review by Marko64 — CHANGES_REQUESTED** [review]
1. I think icons need to be the same colour:
Screenshot_1


2. Perhaps we can create a variable for these repeating colours:
Screenshot_2

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/3785d077-a678-4609-a2a1-34c0e96dbbca
Check, how it looks for narrow columns

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/711a8bc6-065d-4806-891f-124d54e2206d
1) need hover for smile icon
2) why when we pick M we have Icon and text, but when we pick S and then M, we have only icon
3) when we pick M, icon is compressed, distorted
image

**Review by Olekrut — APPROVED** [review]
See only icon from L, so it is fixed

**Review by myroslavve — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
