### PR TITLE
Issue 2891: Number counter width 

### PR DESCRIPTION
**Pull request by FitseTLT**
fixes #2891

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]

**Review by bilouStrike — COMMENTED** [review]
please ignore linting php files, to keep it easy to track php code modification

**Review by bilouStrike — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
The settings in not saved after I reload the editor: 

https://user-images.githubusercontent.com/2401618/165069365-984f0647-0661-4086-a9c0-6236e89d8991.mp4

**Review by elzadj — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
The idea is working, but is quite messy. Please, follow next steps:
1. Return default `width` attribute to `type: 'number'`
2. Add a new attribute for NumberCounter, something like `width-auto`
3. Add manually a ToggleControl that works with the width-auto
4. Remove `autoDefaultValue` prop on AdvancedNumberControl

**Review by Naaaaiix — APPROVED** [review]
Thanks @FitseTLT , good job 😸

**Pull request merged**
