### PR TITLE
Issue 4233 - Button bottom gap remove

### PR DESCRIPTION
**Pull request by Marko64**
Removed bottom gap for button, image caption and effects and accordion title.

Fixes #4233 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test that the bottom gap is removed for button, image caption and effects, and accordion title.
-   [ ] Make sure if it needs to be removed from anywhere else.

**_ Pre-Code Testing _**

-   [x] Test that the bottom gap is removed for button, image caption and effects, and accordion title.
-   [x] Make sure if it needs to be removed from anywhere else.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Naaaaiix — APPROVED** [review]
Looks good in terms of code 👍

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) You have missed search and Map) search was fixed, idk why) need to fix only Map-block
2) need to remove bottom-gap from SC for button 
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/1aee18a5-0d18-43ab-a213-857ae656b1fc
value and range control after reset in SC

**Review by Olekrut — APPROVED** [review]

**Review by Fybex — APPROVED** [review]
Looks good, left comments with minor things, which won't change code logic

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/90eb1abc-c1c4-46b4-bfb9-91c0bc629a81
remove bottom-gap for Image hover text effect ( only for capture), Bottom-gap is need only for title.
2) image
remove it for map-block ( only for description)

**Review by Naaaaiix — COMMENTED** [review]
Check tests, something is broken 🤔

**Review by Olekrut — APPROVED** [review]

**Review by Olekrut — APPROVED** [review]
Maybe need to leave bottom-gap for Map`s title? ( not sure that it is need(()
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/3ef6ffc9-c6e0-438d-a6b7-e4c0f422f6e1
map title have margin-bottom:0 0 10px;
image
bottom-gap should work instead of it

**Review by Olekrut — CHANGES_REQUESTED** [review]
can you make pls for map title default bottom-gap:10px?

**Review by Olekrut — CHANGES_REQUESTED** [review]
Returned as were before( bottom-gap should be 10 px by default
https://jam.dev/c/c1d4e2fa-e75f-4cc1-be3f-60099d416719

**Review by Olekrut — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Ensure master is merged and try removing the `skip` on the SC tests; I think they are already fixed 👍

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Please @Marko64, compare what has been fixed in master and what has been modified here. This branch is older than a branch already merged on master that fixes SC tests, and in this branch we modified some SC tests and set skip. If we merge this branch, we'll merge this skipped tests and we'll brake master. Please,check it carefully, we don't want to do steps back 👍

**Review by Naaaaiix — APPROVED** [review]

**Pull request merged**
