### PR TITLE
Issue 4096 - Disable transition option in IB for alignment

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #4096 

# How Has This Been Tested?
Checked if there are no transition settings in the IB alignment settings and if the transition isn't added in the frontend.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test if there are no transition settings in the IB alignment settings and if the transition isn't added on frontend.
-   [ ] Test if other IB settings have transition settings and if it works correct on frontend.

**_ Pre-Code Testing _**

-   [ ] Test if there are no transition settings in the IB alignment settings and if the transition isn't added on frontend.
-   [ ] Test if other IB settings have transition settings and if it works correct on frontend.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Naaaaiix — COMMENTED** [review]
Looks great, but I'm afraid we need to create a migrator for existing `relations` to add this new entry on the object; don't we?

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
transition is adding on frontend

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) we have transition effects if set IB alignment from Group
image
image
2) IB alignment are not working if set for Accordion or Pane
[alignment.txt](https://github.com/maxi-blocks/maxi-blocks/files/10304197/alignment.txt)

**Review by Olekrut — APPROVED** [review]

**Review by myroslavve — CHANGES_REQUESTED** [review]
The transition styles are added for me on frontend. Nevermind, old scripts were loaded on frontend for some reason...

**Review by myroslavve — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]

**Pull request merged**
