### PR TITLE
Fixes multiple links on Text Maxi

### PR DESCRIPTION
**Pull request by Naaaaiix**
# Description

Lately we've been experiencing an issue with Text Maxi when trying to add multiple links: the already created links were updated with the last link URL. This PR aims to fix it.

~~Not very convinced of the solution, but many part of the code was done 3 years ago, so preferred to do a simple and cheat fix 👍~~

PS: also remove unused parts of the `maxiBlocks/text` store; old code 👍 

# How Has This Been Tested?

On `master`, create a Text Maxi, add different words and into each one add a link. It should return all the words with same link. With this branch it should preserve all links:

https://user-images.githubusercontent.com/50477222/236472593-51c614f6-33fd-411a-933f-6e72c79349fa.mp4

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/93e71444-6cce-4194-87f3-2851c8ef2dde
[links.txt](https://github.com/maxi-blocks/maxi-blocks/files/11407299/links.txt)
check first link

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/1a47301a-8bf3-4262-81e6-5809c5b61f42
working better, but
if change existed link, it will change link for all links

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/9863a04c-5c32-491a-93ff-65f98e305a5f

**Review by Olekrut — CHANGES_REQUESTED** [review]
Cant to add link anymore
https://jam.dev/c/74b2bef9-27f6-42dd-847f-c8242c4ea48f

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/a31b7a95-99e2-4921-93b7-58da24052e0b
1) add link
2) try to change link
3) remove link
4) add link
5) try to change link ( i cant do this step )

**Review by Olekrut — APPROVED** [review]

**Review by darimshlk — APPROVED** [review]

**Review by elzadj — APPROVED** [review]
Other than the couple of things above, works great! Thanks @Naaaaiix

**Review by Olekrut — CHANGES_REQUESTED** [review]
i dont have error, but when i press enter, i get infinite loading of page cant do anything after that

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
