### PR TITLE
Issue 5059 - woocommerce integration

### LINKED ISSUE #5019: WooCommerce DC integration
### Description

_No response_

### Other plugins or websites examples

_No response_

### How to implement it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
This PR replaces https://github.com/maxi-blocks/maxi-blocks/pull/5059, because I couldn't rebase that PR branch.

# Description
Added DC integration for woocommerce. Currently, you can get most info about product

Fixes #5019

To test:
1. install WooCommerce plugin.
2. Add products, try to fill out most fields, woocommerce will guide you how to do it.
3. Check that DC has two new types: `products` and `cart`.
4. Check that DC shows correct info about products.
5. To test cart DC, go to frontend (product pages, or main store page) and add products to cart, check that totals shown in maxi are correct. You can also add tax rates and shipping cost to check if they are shown correct in maxi.

# How Has This Been Tested?
Checked that all fields in `cart` and `product` DC types work right. Checked that relations for products work right.

# Test checklist

**_Front/Back Testing_**

-   [ ] Test products DC for text, button, image maxi.
-   [ ] Test cart DC for text, button maxi.
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload

**_Pre-Code Testing_**

-   [ ] Test products DC for text, button, image maxi.
-   [ ] Test cart DC for text, button maxi.
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### Summary by CodeRabbit

- New Feature: Added support for WooCommerce products and cart data in dynamic content. Users can now display product and cart information dynamically in their content.
- New Feature: Introduced a new REST API route to retrieve active integration plugins, enhancing the plugin's compatibility with other systems.
- New Feature: Added an "Image Accumulator" control for the gallery field, providing users with more control over image display.
- Improvement: Enhanced the dynamic content link feature with more options, including the ability to target specific product links.
- Improvement: Updated the user interface for dynamic content settings, making it more intuitive and user-friendly.
- Improvement: Optimized data fetching for products and cart data, improving performance and reducing unnecessary network requests.
- Improvement: Enhanced the validation and parsing of dynamic content, improving the reliability of content display.

### CODE REVIEW

**Comment by TeksPeks** [comment]
https://github.com/maxi-blocks/maxi-blocks/pull/5059#pullrequestreview-1617149469 @Marko64 
> Every fields seems to display correctly.
> 
> We probably don't have a mechanism for that yet, but we need to add product gallery images too in the future.

Added product gallery images to image maxi options.

----
https://github.com/maxi-blocks/maxi-blocks/pull/5059#pullrequestreview-1618262424 @Olekrut 

> 1. smth weird > products, posts, tags have categories from posts, it is everywhere. if you dont have it, then
>    https://jam.dev/c/caa82b23-a772-4d39-816f-3efa8afbf1d9
>    https://jam.dev/c/985207a4-3454-4a28-a3a2-a645d06de2b3

Fixed.

> 2. Link for Cart is not working
>    image

Added a dropdown to choose between a link that leads to a product page and a link that adds a product to cart.

> 3. Need to convert rating to stars
>    image

This can't be done with our current blocks, will create an issue for this.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) is need default value for image accumulator?
https://jam.dev/c/e556097a-7a68-4c27-8412-f79b1d983de5
2) Due changing relation, everything is rendering so slow
https://jam.dev/c/6d9a9998-e319-45a4-81b1-add823cb917e
3) if for row change relation from product to post. All DC settings are dropping ( video from point 3 )
4) Dropdown is working for Cart`s link, only if text-block is single. Link is changing, but not dropdown's point
https://jam.dev/c/aa0d56d0-28d0-4605-a062-81a7d8f13bbc
Why link is empty for cart?
image

**Comment by TeksPeks** [comment]
> 1. is need default value for image accumulator?
>    https://jam.dev/c/e556097a-7a68-4c27-8412-f79b1d983de5

Added default.

> 2. Due changing relation, everything is rendering so slow
>    https://jam.dev/c/6d9a9998-e319-45a4-81b1-add823cb917e

Tried to optimize, but there is not much that is related to this PR that slows down DC much, tested with https://github.com/maxi-blocks/maxi-blocks/pull/5187, feels a bit faster, so it will be faster once both these PRs are merged.

> 3. if for row change relation from product to post. All DC settings are dropping ( video from point 3 )

Same happens if you switch from post to tag or post to author, so if it is an issue please create it as a separate because it affects all DC.

> 4. Dropdown is working for Cart`s link, only if text-block is single. Link is changing, but not dropdown's point
>    https://jam.dev/c/aa0d56d0-28d0-4605-a062-81a7d8f13bbc
>    Why link is empty for cart?
>    image

Fixed.

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/9393f8ae-1dbf-4456-a0bf-fe16cd080972
4 points in this video
1) need static text for button as for Post buttons
2) link is empty, if it is not single block
image
3) after click to link "add to cart" it references to Homepage template, not to cart. ( should it reference somewhere at all? )
4) need some message after adding to cart ( would be good with link to cart

**Comment by TeksPeks** [comment]
> https://jam.dev/c/9393f8ae-1dbf-4456-a0bf-fe16cd080972 4 points in this video
> 
> 1. need static text for button as for Post buttons

added.
> 2. link is empty, if it is not single block

fixed.
>    image
> 3. after click to link "add to cart" it references to Homepage template, not to cart. ( should it reference somewhere at all? )

Users can change where that link redirects on their sites, so I don't think we should change that. Tried to add a "remain on page" switch for this, but it requires many changes in DC structure, so for now didn't add it. Created an issue for it.

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
