### PR TITLE
Custom taxonomies for relations in CL / DC

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Adds CT to Relations for posts, both on pages and archive templates.

screenshot-wordpress local-2024 08 30-19_18_00

screenshot-wordpress local-2024 08 30-19_14_02

# How Has This Been Tested?

Add a CT for posts, test it in DC / CL on a page, on a CT Template Archive, backend and frontend, pagination.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Enhanced support for custom taxonomies in content retrieval and rendering logic.
	- Improved flexibility in displaying UI elements based on various relational contexts.
	- Added robust handling for custom taxonomy relations in data fetching and options generation.
	- Introduced a new function to retrieve the current template slug dynamically.

- **Bug Fixes**
	- Improved error handling and robustness in asynchronous functions to prevent runtime exceptions.

- **Refactor**
	- Streamlined logic in several components and utility functions for better readability and performance.

- **Chores**
	- Removed unused imports and simplified conditional logic across multiple files.

### CODE REVIEW

**Comment by elzadj** [comment]
Found a bug on backend - it looses content there if you reload the page, fixing

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) looks like it works slow or with bug, try a few times to change relation
https://jam.dev/c/123ea0b5-bf6d-4059-a6b1-f84b7c150cd1
2) under relation should be categories from current taxonomy
image

[acf-export-2024-09-02.json](https://github.com/user-attachments/files/16840583/acf-export-2024-09-02.json)

**Comment by elzadj** [comment]
Please test a hierarchical taxonomy first.

**Review by Olekrut — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
I am getting error if using template with DC type archive for text blocks
image
image

https://jam.dev/c/e7e0c4a1-f384-4b90-acb9-07270ad4980f

all archive template with bug as well
https://jam.dev/c/76d41671-0533-4b70-b4b8-74019a374e4a

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
