### PR TITLE
Issue 5019 - woocommerce DC integration

### LINKED ISSUE #5019: WooCommerce DC integration
### Description

_No response_

### Other plugins or websites examples

_No response_

### How to implement it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Added DC integration for woocommerce. Currently, you can get most info about product

Fixes #5019

To test:
1. install WooCommerce plugin.
2. Add products, try to fill out most fields, woocommerce will guide you how to do it.
3. Check that DC has two new types: `products` and `cart`.
4. Check that DC shows correct info about products.
5. To test cart DC, go to frontend (product pages, or main store page) and add products to cart, check that totals shown in maxi are correct. You can also add tax rates and shipping cost to check if they are shown correct in maxi.

# How Has This Been Tested?
Checked that all fields in `cart` and `product` DC types work right. Checked that relations for products work right.

# Test checklist

**_Front/Back Testing_**

-   [ ] Test products DC for text, button, image maxi.
-   [ ] Test cart DC for text, button maxi.
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload

**_Pre-Code Testing_**

-   [ ] Test products DC for text, button, image maxi.
-   [ ] Test cart DC for text, button maxi.
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### Summary by CodeRabbit

Release Notes:

- New Feature: Added a new REST route `/get-active-integration-plugins` to retrieve the active integration plugins.
- New Feature: Introduced support for handling `products` and `cart` types in dynamic content rendering.
- Refactor: Modified several functions in the dynamic content module to handle the new types and improve code organization.
- Refactor: Updated ACFSettingsControl component to use consistent prop naming.
- Refactor: Made various improvements to the DC extension, including adding new source options, type options, field options, and integration options.
- Bug Fix: Fixed issues related to retrieving taxonomy content and handling multiple products.
- Performance: Implemented memoization and indexing optimizations for retrieving product and cart data from the WooCommerce API.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) what is it price? Product has only regular price and sale price
image
2) Got error after some moment
[warnings.txt](https://github.com/maxi-blocks/maxi-blocks/files/12467878/warnings.txt)
https://jam.dev/c/fd6e921c-187c-45cc-b204-530287b9ba20
[error.webm](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/c81a5b4e-8aef-4312-8899-ec69e3adb287)
3) Average rating and review count on frontend, backend is not good as well
https://jam.dev/c/87883c5e-ce8c-423d-85b8-f742fa69d14e
4) Long DC rendering
https://jam.dev/c/97d3f59f-9f6e-4964-ae9b-ce4f7189f59d
5) if we dont have Sale price > on frontend = 0.00
image
6) if we dont have tags > on frontend, we will see "Not content found"
7) if we dont havevalue for some of DC Text block, on frontend it should has display:none;

**Review by Olekrut — APPROVED** [review]
Have not seen patterns yet, but, guess, looks ok 👍 
@marko64 can you check it as well, pls, especially cart

**Review by Marko64 — APPROVED** [review]
Every fields seems to display correctly.

We probably don't have a mechanism for that yet, but we need to add product gallery images too in the future.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) smth weird > products, posts, tags have categories from posts, it is everywhere. if you dont have it, then 
https://jam.dev/c/caa82b23-a772-4d39-816f-3efa8afbf1d9
https://jam.dev/c/985207a4-3454-4a28-a3a2-a645d06de2b3
2) Link for Cart is not working
image
3) Need to convert rating to stars
image

**Comment by TeksPeks** [comment]
Moved to https://github.com/maxi-blocks/maxi-blocks/pull/5166

**Pull request closed without merging**
