### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by elzadj**
# Description

An attempt to fix freezes during Gutenberg use.  Also fixes php warnings from DC.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test any DC component in normal state in sidebar
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test any DC component in normal state in sidebar
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Bug Fixes**
    - Improved logic for handling database results to ensure reliability.
    - Added null checks and property existence validation to enhance stability in dynamic content processing.
    - Refined error handling for more robust operation.
- **Refactor**
    - Modified logic in `get_media_content` method to handle 'author' field differently.
- **Chores**
    - Commented out the import statement for `'./fonts'` in the `src/extensions/text/index.js` file.
    - Added the import for `BundleAnalyzerPlugin` in the `webpack.config.js` file.
    - Introduced a check for the environment variable `ANALYZE` to conditionally add `BundleAnalyzerPlugin` to the list of plugins in the `webpack.config.js` file.

### CODE REVIEW

**Comment by elzadj** [comment]
@Olekrut please test again. Do ```npm run build``` and clear the cache if needed. Also please test the overall speed of the plugin - in the editor, loading from cloud, in FSE, selecting blocks, etc.

**Review by Olekrut — APPROVED** [review]
Have tried a lot of our patterns, can't find bugs((

**Review by Olekrut — CHANGES_REQUESTED** [review]
Sorry,, have found., Only one bug, can you try to open template library on FSE
It is not working for me

**Comment by Olekrut** [comment]
https://jam.dev/c/ae8fb746-f438-4157-9e46-c8681f70da1e

**Comment by elzadj** [comment]
> https://jam.dev/c/ae8fb746-f438-4157-9e46-c8681f70da1e

Master is the same, only Toolbar, only Pages and Page with Sidebar Template. Not connected to that branch.

**Review by Olekrut — APPROVED** [review]

**Comment by elzadj** [comment]
@Olekrut fixed the warnings. Could I ask you to also check Maxi Blocks and SC, not only patterns? Thanks.

**Pull request merged**
