### PR TITLE
Issue 4874 - Image URL source for image,video-maxi & image layer

### LINKED ISSUE #4874: Image URL source
### Description

We lack URL as an image source for the Maxi Image. Maybe we need it for the background images too.

### Step-by-step reproduction instructions

_No response_

### Screenshots, screen recording, code snippet

_No response_

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #4874 

image
image

# How Has This Been Tested?
Checked if URL image, media library upload works for image,video-maxi and image layer. Checked if DC image features works.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test image url source for image,video-maxi
-   [ ] Test image url source for image layer
-   [ ] Test image media library upload for image,video-maxi
-   [ ] Test image media library upload for image layer 
-   [ ] Test DC image features
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload

**_ Pre-Code Testing _**

-   [ ] Test image url source for image,video-maxi
-   [ ] Test image url source for image layer
-   [ ] Test image media library upload for image,video-maxi
-   [ ] Test image media library upload for image layer 
-   [ ] Test DC image features
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Introduced a new `ImageUrlUpload` component for handling direct image URL uploads.
  - Enhanced image and video blocks with URL validation features to improve user experience.

- **Enhancements**
  - Updated image and video editing interfaces to include new URL upload options.
  - Improved visual feedback for image URL validation errors.

- **Style Updates**
  - Added new styles for the image URL upload interface and error messaging.
  - Updated toolbar button styles for a more consistent user interface.

- **Bug Fixes**
  - Fixed issues with image display logic to ensure proper handling of valid and invalid URLs.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) URL source should work for any link? (even from google?)

2) and just asking:
is need the same for BG shape and BG Video failback ?
image
image

**Comment by kyrapieterse** [comment]
MVP make a new issue

**Comment by Fybex** [comment]
> 1. URL source should work for any link? (even from google?)

Everything that can be placed in the html `img` `rc` attribute can be placed in our text input.

> 2. and just asking:
>    is need the same for BG shape and BG Video failback ?
>    image
>    image

Added it 👍 

Test different scenarios, when link is valid/invalid, then try to replace link with image from media library and vice verca. Thanks @Olekrut

**Review by Olekrut — APPROVED** [review]
looks ok, just need to disallow this list
image

**Comment by elzadj** [comment]
@Olekrut I think that's your browser autocomplete

**Comment by elzadj** [comment]
@Olekrut check the autocomplete list (should be hidden now) pls. + changed Upload to Insert, and some other labels.

**Review by elzadj — APPROVED** [review]

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
