### PR TITLE
Topography - conflict Hover state and IB #3514

### PR DESCRIPTION
**Pull request by FitseTLT**
# Description
Changed the implementation of IB to use <style> element so that it will not override the hover state
Added capability of having different transitions for different IB effects

Fixes #3514

# How Has This Been Tested?
Check that IB don't override hover state style
Check we can have different transition for different styles

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — COMMENTED** [review]
Hover works.
Not sure about transitions; do you mean you should now be able to choose a different transition for each setting? If so, it's not working for me. If I change, for example, the duration for the alignment, it is also applied to typography (just an example.

**Review by Marko64 — COMMENTED** [review]
When you have multiple interactions, some transitions are not working. Here's an example:
https://user-images.githubusercontent.com/19425503/182565860-d3b5580b-6f15-4c9a-a726-0e608fe74a30.mp4

**Review by Marko64 — APPROVED** [review]
I can't replicate the issue anymore 👍

**Review by myroslavve — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Cool, works good! Couple of small things and will be merged 🚀

**Review by Fybex — CHANGES_REQUESTED** [review]

**Review by Fybex — APPROVED** [review]

**Pull request merged**
