### PR TITLE
Issue 3841 - Block inserter between blocks

### PR DESCRIPTION
**Pull request by Naaaaiix**
# Description

This PR aims to fix one of the multiple issues we found related with the UI and the spaces between blocks. This implementation tries to fix the inserter that should appear between Maxi blocks sitting over each other. The first idea was to add a fix gap between elements (#3853), but lately decided to add our own inserter.

The implementation of the `InterBlockInserter` component is a test and I'd like to know your feedback about the experience. This new inserter appears when hovering the bottom of the block **just when there's another block next and it is a Maxi block**:

https://user-images.githubusercontent.com/50477222/201720608-a177866a-436c-47fe-993d-7c7bea31b569.mp4

Fixes #3841 

# How Has This Been Tested?

It has been tested when:
- Standalone Maxi block => shouldn't appaer
- Between 2 Maxi blocks => should appear
- Between 2 Maxi blocks with margin-top/bottom => should appear (not in middle, same place, under the block. Between the blocks appears the original WP inserter)
- Between a Maxi block and WP native block => shouldn't appear
- Between 2 Maxi blocks inside another Maxi block => should appear
- Between 2 Maxi blocks inside a WP native block => should appear
- Between 2 Container Maxi with padding/margin => should appear under the padding.

These tests need to be done on WP 6.0 and WP 6.1. For changing from WP 6.1 (default on current Maxi version) run this line on the terminal:
`WP_ENV_CORE="WordPress/WordPress#6.0" npm run wp-env start`

Known issues/cases:
1. On Container Maxi it can generate confusion with margin/padding draggers. It will be fixed with the new dragger we'll add soon to fix #2652 👍 
2. On "calling" the inserter while hovering a Maxi block that inners some blocks, the square button disappears and let the round button appear => is expected.
3. Sometimes, while adding margin-top/bottom to a block, the inserter appears, but also appears the native WP inserter => has been fixed!

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test all situations shared above

**_ Pre-Code Testing _**

-   [ ] Test all situations shared above
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — COMMENTED** [review]
https://user-images.githubusercontent.com/19425503/202667358-c6b7f9da-a6e9-4f85-881b-1de78d9a4049.mp4

**Review by elzadj — APPROVED** [review]
Great! Maybe we can addclick to the whole ```maxi-inter-blocks-inserter__toggle```, not to the button only? Because now we need to move the cursor to the "+" sight first, and it can be challenging:

[screencast-wordpress.local-2022.11.21-16_03_51.webm](https://user-images.githubusercontent.com/2401618/203074609-0bf7a6b6-d854-478d-b6db-0075b9ca9512.webm)

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/8ac4b8a8-4897-4c70-928c-dc0f7d2fa1b8
 
 Can't click to block with small height (divider, for example)

**Review by Olekrut — APPROVED** [review]
https://jam.dev/c/e315f3a1-0a5c-4c7c-88f1-63059f21cbe8
cant pick block if height less than 12px, but I guess, it is rare case) much better!!!

**Review by Fybex — CHANGES_REQUESTED** [review]

**Review by Fybex — APPROVED** [review]

**Pull request merged**
