### PR TITLE
Fix 3596 - Implement removing empty container

### PR DESCRIPTION
**Pull request by blockchain-web-mobile-dev**
…over component

# Description

I have implemented removing empty container block when remove row block in popover component.

Fixes #3596 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — COMMENTED** [review]
This works. A couple of comments:
- My initial thought was that we wanted to pop up columns' selector instead of deleting the container. I can't decide what's better from the editor's perspective. The longer I think about it more I like your solution.
- If you delete the row from the list view, the container remains present on the page. The list view is not a Maxi feature, of course, so not sure if we can manipulate this.

**Review by Marko64 — APPROVED** [review]

**Review by myroslavve — CHANGES_REQUESTED** [review]
To make it work when deleting row from list view, and with any other way of deleting blocks, we can make use of `hasInnerBlocks` prop which we have in container-maxi.
In `edit` of container-maxi, in `maxiBlockDidUpdate` we can check if container has innerBlocks, and if it doesn't remove it (or insert a row).
Something like this:
```
if (!this.props.hasInnerBlocks) {
  // Remove the container
}
```

**Review by myroslavve — APPROVED** [review]

**Review by elzadj — APPROVED** [review]
Interesting fix :+1:

**Review by Naaaaiix — APPROVED** [review]
Waiting for #3754 and pass tests to be merged 👍

**Pull request merged**
