### PR TITLE
Issue 890

### PR DESCRIPTION
**Pull request by javadsamiee**

### CODE REVIEW

**Review by elzadj — CHANGES_REQUESTED** [review]
Good, but we need to show the default colour / blue/ spread / etc. in the settings: 

Add-New-Page-‹-DEV-Maxi-Blocks-—-WordPress

Also, please set up rgb(150, 176, 203) as default colour for the two other shadow types.

**Review by Naaaaiix — APPROVED** [review]
Good job, works fine for me 😄

**Review by elzadj — CHANGES_REQUESTED** [review]
Is that possible @Naaaaiix @javadsamiee ? Or should we try to pick a colour without any opacity?
If not possible, please try box-shadow: 0px 30px 87px 0px rgba(236, 241, 246);

Let me understand the error and the necessity: we are offering a box-shadow with an hex colour, but what is required is a rgba colour to use the opacity; am I right?

**Review by elzadj — CHANGES_REQUESTED** [review]
A weird bug - I see     box-shadow: 0px 0px 0px 0px rgb(150 176 203 / 23%); for all items: Container, Row, Columns and Text, although I've enabled the shadow for the text only.

And I need to manually change the Box Shadow settings for the 0px 30px 87px 0px part to start working.

**Review by elzadj — CHANGES_REQUESTED** [review]
Much better, thanks! 
I see all the blocks have box-shadow: 0px 0px 0px 0px rgb(236 241 246); by default - can we remove it? And the empty box-shadow css too?
Screenshot-from-2021-02-10-10-59-13

**Review by Naaaaiix — APPROVED** [review]
Works fine for me, but as the long debate has been showing, we have at least 2 derived errors:
1. ColorControl doesn't deal correct with RGBA.
2. Helpers have many errors, and generate situations like:
> Screenshot-from-2021-02-10-10-59-13

I would merge this issue, and generate issues for each one. Finally, the main objective of this PR has been achieved 👍

**Review by elzadj — APPROVED** [review]

**Pull request merged**
