### PR TITLE
Issue 880

### PR DESCRIPTION
**Pull request by javadsamiee**
Fix TextShadow Color and Opacity

### CODE REVIEW

**Review by elzadj — CHANGES_REQUESTED** [review]
Niiice, thank you.


Can we keep it across all types please?

**Review by elzadj — CHANGES_REQUESTED** [review]
Much, much better

**Review by elzadj — CHANGES_REQUESTED** [review]
Better, but I still see these

**Review by Naaaaiix — APPROVED** [review]
Works perfect for me 😄

**Review by elzadj — CHANGES_REQUESTED** [review]
I still see that bug with the previous colour applying :thinking: 

@Naaaaiix @javadsamiee can you re-create, or is it just me?

**Review by elzadj — APPROVED** [review]
Wooooorks.

**Pull request merged**
