### PR TITLE
Issue 4685 - bug with big marker

### PR DESCRIPTION
**Pull request by myroslavve**
# Description

Fixes #4685 

# How Has This Been Tested?
Checked that SVG marker has right height.

# Test checklist

**_Front/Back Testing_**

-   [x] Check that SVG marker has right height.

**_Pre-Code Testing_**

-   [ ] Check that SVG marker has right height.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/aa5d9de5-71b2-41f4-8dbf-75ef598640c0
compare with master
1) new bugs appear ( marker size, list gap. etc) 
2) bug with line-height is not fixed
3) check how it influences to patterns from library, PTL-02(for example)

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) is not fixed
image
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
yes, better, but need ability to add padding only for text in each li 
for align center of marker and first line of text
image
or text-indent by vertical
idk, what is better, but I guess, second variant will be easier

**Review by Olekrut — CHANGES_REQUESTED** [review]
Everything is cool) 
can be cases when need to align marker by bottom of first line
so text-position is not enough
need vertical marker indent 
image

can approve and make new issue or can you make it in this issue?

**Review by Olekrut — APPROVED** [review]
🔥

**Review by darimshlk — APPROVED** [review]

**Review by Fybex — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
