### PR TITLE
Issue-2902 : Number Counter responsive support

### PR DESCRIPTION
**Pull request by bilouStrike**
Fixes : #2902

### CODE REVIEW

**Review by Alejandro9kgm — APPROVED** [review]

**Review by FitseTLT — APPROVED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Tests show that something is broken, please check them 👍 

Backend:
Captura de pantalla 2022-04-26 a las 12 25 27

Frontend:
Captura de pantalla 2022-04-26 a las 12 25 39

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Number Counter is not working as expected

https://user-images.githubusercontent.com/50477222/165909585-a1210413-21dc-40c7-9303-66ba6f5cfd3b.mp4

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Cool, need some fixes. Also `e2e-tests/components/number-counter-control/index.spec.js` needs responsive tests 👍

**Review by Marko64 — APPROVED** [review]
Visually looking good.

**Review by myroslavve — APPROVED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Check my last review, still things to fix 👍

**Review by Naaaaiix — CHANGES_REQUESTED** [review]

**Pull request merged**
