### PR TITLE
Issue 4688 - Repeater

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #4688 

# Test checklist

**_ Front/Back Testing _**

-  [x] Check if on changing setting in one column or nested in column block, it will change in other columns
-  [x] Check if on adding/deleting/moving nested block to one column, it will be added/deleted/moved in all columns (check difficult hierarchy structures please)
-  [x] Check if undo works as expected (undo with one undo action last changes in all columns)
-  [x] Check if repeater don't change attributes in all columns like content in text-maxi or image in image-maxi or image bg layer (all attributes which is excluded on Copy Paste - All action)
-  [x] Check if on turning repeater with not empty, differently filled columns it will adapt columns correctly(by copying content of first column to others)
-  [x] Check if repeater works as expected with templates from library
-  [x] Check if IB inside column with turned on repeater have correct triggers, targets, list of blocks to affect
-  [x] Check if column picker has only equal width columns when repeater is turned on
-  [ ] Check if repeater works as expected with nested rows 
-  [x] Check if with turned off repeater everything works as expected(without repeater functionality)
-  [x] Check repeater in FSE
-  [x] Most important: play with repeater and try to find uncovered cases

**_ Pre-Code Testing _**

-  [x] Check if on changing setting in one column or nested in column block, it will change in other columns
-  [x] Check if on adding/deleting/moving nested block to one column, it will be added/deleted/moved in all columns (check difficult hierarchy structures please)
-  [x] Check if undo works as expected (undo with one undo action last changes in all columns)
-  [x] Check if repeater don't change attributes in all columns like content in text-maxi or image in image-maxi or image bg layer (all attributes which is excluded on Copy Paste - All action)
-  [x] Check if on turning repeater with not empty, differently filled columns it will adapt columns correctly(by copying content of first column to others)
-  [x] Check if repeater works as expected with templates from library
-  [x] Check if IB inside column with turned on repeater have correct triggers, targets, list of blocks to affect
-  [x] Check if column picker has only equal width columns when repeater is turned on
-  [x] Check if repeater works as expected with nested rows 
-  [x] Check if with turned off repeater everything works as expected(without repeater functionality)
-  [x] Check repeater in FSE
-  [x] Most important: play with repeater and try to find uncovered cases
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

### 2 rare known issues, which will be fixed later in this PR or derived into separate one:
1. Undo after moving block outside of repeater don't work correctly

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/e0b449b7-d549-4c4d-a39b-11878b758cc1

UPD: looks like it was fixed

2. Handling movement between columns with turned on repeater. I don't even know how we should handle this. It's not looks like it's possible to forbid movement.

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/2e4b82a8-eaf7-4b8d-9e3a-a2d47a6632e2

### CODE REVIEW

**Review by Olekrut — APPROVED** [review]
Not sure, but can find nothing more

**Review by darimshlk — APPROVED** [review]

**Review by myroslavve — CHANGES_REQUESTED** [review]
"Duplicate" doesn't work

https://github.com/maxi-blocks/maxi-blocks/assets/53875005/1c587d5f-bd84-43ad-8d88-499f3957d529

and "Paste nested blocks" as well

https://github.com/maxi-blocks/maxi-blocks/assets/53875005/e32a3ef2-4d44-4e42-98e7-244334712845

**Review by myroslavve — CHANGES_REQUESTED** [review]
When I paste blocks in column with blocks, they just disappear, everything else works 👍 

https://github.com/maxi-blocks/maxi-blocks/assets/53875005/b270c5fd-cfed-4c23-8ad0-5e8e226f8317

**Review by myroslavve — CHANGES_REQUESTED** [review]
> So the bug was fixed, and repeater deletion helper function was changed significantly as well, so @TeksPeks, please, test deletion process again deeply 👍

When deleting last block from column

https://github.com/maxi-blocks/maxi-blocks/assets/53875005/865a0b29-1c8f-42c5-ae21-20b3d9a9f31c

Also, probably makes sense to hide this thing in toolbar when repeater is enabled since user shouldn't be able to change columns size (it also gives me errors after I change number of columns in row from sidebar, but that won't matter if we remove it)
image

**Review by myroslavve — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
looks great, and works great, here are some things that I've noticed:

1. When I add an Icon and then add its content, it's added to all Icon Blocks in syncronised columns, it's a little bit confusing, because Text or Button don't act like this. I think we need to add the icon to only the one that we add it, and leave others with placeholder, if it's possible. If not or hard - you can ignore it.
2. I think we need to somehow highlight and show that the columns are repeated in the editor. Because it's a surprise when you remove one button, but all of them are removed.
3. The columns break when I change the number:

[screencast-wordpress.local-2023.06.23-12_54_13.webm](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/c280e835-181a-4a33-b286-bfdf4e3a817b)

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/03792b60-06f3-43c3-8a16-6406f9429df9
text is disappearing if enable list
2) https://jam.dev/c/d2db6756-40fe-4efc-ba0c-0f4a455aaaf9
i understand why, looks like weird behavior, idk, what is better
3) Hover styles for part of text in one text-block is not repeating
https://jam.dev/c/313e4640-eb8c-4ca9-b3d5-9761f18a4b2b
[repeat bug 1.txt](https://github.com/maxi-blocks/maxi-blocks/files/11892083/repeat.bug.1.txt)
4) UI bug
image
5) repeater is working for alt title and description. Is it expected, I guess, no.
image
6) repeater is working ( coping blocks to others columns ) only from first column.. is it expected?
https://jam.dev/c/a06fdd76-8535-4c23-a9cf-6f81d23e5866
7.1) weird behavior for moved blocks
https://jam.dev/c/cc737f39-94ca-4d5d-b59d-4ecfd01d27b2
7.2) And what should happen with blocks in others columns, if we moved the block from 1st?
Because for example if remove block from second column, it is removing from first one as well https://jam.dev/c/b9797b2d-1dec-4a10-b79d-a24c87398be3
8) column-gap is dropping, if enable repeater for row like that. Can be checked on PTML-PRO-11
https://jam.dev/c/b0e61870-c203-4261-8390-c245e10230fb
9) check how paste nested blocks influence to others column ( removing blocks ) 
https://jam.dev/c/b491b39d-16b8-4aa9-9972-b94cbe5a0b8d
10) if to add IB to block and then enable repeater, blocks are not adding to others columns
https://jam.dev/c/9cc3c71a-2dbc-4a66-b9b9-bceef33b4980

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/cb4e4ac0-713e-4d21-b7a3-5035c972cadb
adding link is adding link`s styles to text in others columns, but is not adding link/ is it expected?
2) https://jam.dev/c/69def9e7-ac98-4130-a9a2-62927096499a
URL for video is not changing after second change
3) https://jam.dev/c/725303b9-4a9a-42bc-9404-c813d74a466c
sometimes block is adding not to last position
4) https://jam.dev/c/7c4b94d2-a188-45e3-a0b2-afa94ca4792e
column width in case like for PTLL-PRO-22

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) I guess, repeater for IB is not working correct in this case
https://jam.dev/c/c995844a-304b-4024-b0bf-522646e5644e
2) if enable repeater and then increase amount of columns > blocks are not repeating to new empty column
https://jam.dev/c/cb09d612-0ea5-4f8f-9f9a-f260c73dc8aa

**Review by Olekrut — CHANGES_REQUESTED** [review]
Cant find bugs except freezes, but feel that there are they 😢 

https://jam.dev/c/15205c05-89d8-4979-a27d-3ec063627066
for example try to load PTML-PRO-114, enable repeater for row with images, and try to change typography for some of texts. I waited about 4-5 min before they changed

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) copy/paste styles bug
https://jam.dev/c/da595fbd-6d00-4896-9bd9-e42d159544fe
2) paste nested block not to first column, is it expected?
https://jam.dev/c/cee4b5b9-24ef-4f3c-9666-c8dc227b99a9
3) @dashaversha found. Try to enable repeater for row and increase amount of column more than 8, error
https://jam.dev/c/ba38d7c4-576d-4e5d-b454-61b15070f0a2

**Review by Olekrut — APPROVED** [review]
🥇

**Review by darimshlk — APPROVED** [review]

**Review by myroslavve — CHANGES_REQUESTED** [review]
when selecting number of columns in inner rows, one column is missing in the selected row.

https://github.com/maxi-blocks/maxi-blocks/assets/53875005/9a403ec4-01ed-4f5b-bd1d-4e1dcf690d27

When moving a block into repeater, content of all blocks in the repeater becomes the same.

https://github.com/maxi-blocks/maxi-blocks/assets/53875005/40d4dad9-2a3b-4fb1-92d6-462a1535d7f5

**Review by myroslavve — CHANGES_REQUESTED** [review]
When I delete all content from text, it deletes in other text block as well, and the same happens  for buttons.

https://github.com/maxi-blocks/maxi-blocks/assets/53875005/f6229958-811a-4533-a236-23f84f1cf96c

**Review by myroslavve — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
