### PR TITLE
Issue 1985

### PR DESCRIPTION
**Pull request by javadsamiee**

### CODE REVIEW

**Review by Alejandro9kgm — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Good job @javadsamiee , this issue is much more complex than what it seems and you're doing a fantastic job with it; really detailed, thanks. 

We'll need to fix the border-style issue also, maybe in another issue?

**Review by Naaaaiix — COMMENTED** [review]
1. `border-color` doesn't work on the block
2. No border on the arrow
3. New pseudoelement `:before` has CSS errors (`undefined` as value for some properties like `top` or `left`

Please, ensure that the implementation and the tests and everything is correct before committing or requesting for a review. If the PR is not ready, please set is a draft 👍

**Review by Naaaaiix — COMMENTED** [review]
Still finding some issues. Please, check this video and prepare tests to ensure we won't have this error in future 👍 


https://user-images.githubusercontent.com/50477222/130745152-19416461-9441-4dfa-bd44-35f35cac2fda.mp4

**Review by elzadj — APPROVED** [review]
I see some weirdness with the border hover, but it looks like another issue:


https://user-images.githubusercontent.com/2401618/131126837-cfef1303-45f8-46de-85c0-cea494f3a41a.mp4

**Review by Alejandro9kgm — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
Looks like the arrow disappears when I switch the hover border type (from solid to dotted):


https://user-images.githubusercontent.com/2401618/131332101-7f20e604-ea63-4127-9bdb-fe1d1323953d.mp4

**Review by elzadj — APPROVED** [review]
Cool. Can we add a future requests to deal with it later pls?

**Pull request merged**
