### PR TITLE
Issue 4193 - List outdent functionality and style 

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Changes:
- made indent/outdent icons smaller
- indent/outdent buttons are hidden when `text-maxi` not list
- fixed styles for paragraph list-option button (removed change colour on hover, added colour change on press(select))

P.S. paraphraph button:
image

Video of indent/outdent work(for those who do not know how it works):

https://user-images.githubusercontent.com/46112160/211368283-61f0d743-d5f7-4d1f-849b-b2f7d492c979.mp4

P.S. Video was recorded before icons size fix.

Fixes #4193

# How Has This Been Tested?
Checked if changes, which described above, are working correct.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test is outdent/indent appears only when text-maxi - list
-   [ ] Test if outdent/indent icons the same as others from list options
-   [ ] Test if paragraph styles is the same as other buttons

**_ Pre-Code Testing _**

-   [ ] Test is outdent/indent appears only when text-maxi - list
-   [ ] Test if outdent/indent icons the same as others from list options
-   [ ] Test if paragraph styles is the same as other buttons
-   [ ] Check `toHTMLString` changes to check if there is no other better solution.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]
Oh ok, so it actually worked already, but you can click it only for the second list item. Thanks for the video!
If not much work, maybe we should hide it for the first list item then, Otherwise, if that's more work, we can do it sometimes later.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/dc6c89ea-f066-4be9-887c-22a9bf581fb7
structure is not keeping for items under changed items
2) hide indent/outdent icon for first item
image
3) we have equal numbers for different items
image

**Review by Olekrut — APPROVED** [review]

**Review by myroslavve — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Been checking and I don't really see the necessity of abstracting `toHTMLString` RichText method. Let's have a talk and check together, probably I'm losing something 👍

**Review by Naaaaiix — APPROVED** [review]
Not going to lie: not a big fan of abstracting RichText core functions. Not going to spend time trying to find if there's another solution, as we need to MVP it, but going to create a new issue as these abstracted functions of this PR, as others done before (canIndentListItems, canOutdentListItems, indentListItems, outdentListItems), need to ensure a good functionality for Maxi. We need to adapt our blocks to RichText dependency to ensure a smooth and easy updates on future. 
Anyway, good job @Fybex finding Gutenberg's errors 👏

**Pull request merged**
