### PR TITLE
Issue 826

### PR DESCRIPTION
**Pull request by javadsamiee**

### CODE REVIEW

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
The idea is awesome, and it will help us with banning other plugins and themes on terms of CSS. It's a really strong point, well seen @javadsamiee 😄 

There are errors on frontend; I leave here a comparison between this branch and master:
This branch | Master
---- | ----
Captura de pantalla 2021-02-22 a las 9 45 24 | Captura de pantalla 2021-02-22 a las 9 45 37

[Code editor](https://docs.google.com/document/d/1vqLGFO6gogMyn36OASUNK0RCINxypr1cuKFCpIQQITU/edit?usp=sharing)

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Frontend is still not good styled 👍

**Review by Naaaaiix — APPROVED** [review]
Finally! hahahahaha good job @javadsamiee , the id implementation is going to make Maxi even stronger 💪

**Review by Naaaaiix — CHANGES_REQUESTED** [review]

**Review by Naaaaiix — APPROVED** [review]
🥳 🎉 😄

**Review by elzadj — APPROVED** [review]

**Pull request merged**
