### PR TITLE
Issue 5448 - Command line interface (CLI)

### LINKED ISSUE #5448: A command line interface (CLI)
### Description

A command line interface (CLI)

### Other plugins or websites examples

_No response_

### How to implement it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #5448

### Composer
Composer is a PHP package manager, similar to npm for JavaScript. It allows you to manage project dependencies effortlessly. For example, you might need to install external dependencies like PHPUnit for unit testing and Typesense for retrieving the style cards library list.

To use Composer, you must install it locally on your machine. You can follow the installation guide provided by Composer: [Composer Installation for Windows](https://getcomposer.org/doc/00-intro.md#installation-windows).

After installation:
```bash
composer install
```
For production:
```bash
composer install --no-dev --optimize-autoloader
```

### How open terminal with installed WP-CLI

1. `wp-env start`
2. `wp-env run cli bash`
3. `wp help maxiblocks` to see maxiblocks commands and `wp help maxiblocks <command>` to see detailed information about some maxiblock command

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/90cfdbb8-5d76-4019-955d-67d000770542

### 1. Style card commands

For the moment of PR, there are 3 related to style cards control commands:

-   `get-current-style-card` Get active style card name.
-   `list-style-cards` Lists all available from library style cards to set.
-   `set-style-card` Set active style card.

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/33fc8931-dec3-4372-b110-ff56b819ce81

#### How it was implemented

The implementation uses the typesense-php package to retrieve the style card library list. It leverages a copy of the existing JavaScript code to generate the styles for the style cards. After generating the styles, it uses the existing code to save and utilize the style cards.

### 2. Post control commands

Commands:

-   `create-post` Creates a new post with the given title and content.
-   `replace-post-content` Replaces the content of a post.
-   `reload-post-styles` (previous name: `update-post-styles`) Recalculates all block styles for a post. This command is useful if styles for post is broken or not working as expected.

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/6cf4238f-96bd-4a9f-bab2-0764543ead7c

#### How it was implemented

To achieve CLI style generation, all JS style helpers were implemented on the PHP side and covered by the same unit tests as on the JS side.

### 3. Import command

Commands:

- `import-page-set`  Imports a page set. Wrapper for WP CLI import command.

https://github.com/user-attachments/assets/d88abcb8-ebc6-4192-bdfd-d1cd43bf54a6

P.S. In this example, I created an XML import file using the WordPress sidebar -> tools -> export... (shown in the video). Then I placed this XML file in the same folder to which the CLI terminal is mounted and gave the command the path to the XML file. As a result, the import was successful, and the empty WordPress site turned into a site with a home page and posts from the import file.

**UPD: changed the preview of the command execution, now it quickly imports posts and then reloads styles**

#### How it was implemented

On import, styles are generating for each block in each processed post. Similar to previous point: use PHP style generators.

## Notes

<del>
### Changes to `npm run start` and `npm run build`
When you run `npm run build` or `npm run start` for the first time (only once for performance reasons), the `npm run update-blocks-json` command will be executed (takes some time). This updates the `block.json` and group attributes files, ensuring that the CLI has the latest data to operate with.

#### How it looks in terminal:
image
</del>

### Importance of `npm run update-blocks-json`

CLI works based on `block.json` and json files from `group-attributes` folder, so it's crutial to keep json files up to date. To ensure this, I've added an CI action which will fail if json files wasn't updated. Also, added warning on change attributes.js or group-attributes file, but it won't catch all times when you need to `npm run update-blocks-json`.
So we have new technical debt: update json attributes files

### CLI Development:
Whenever there are changes to any attributes, you need to either rerun `npm run start` or manually run `npm run update-blocks-json`.

### ⚠️  PHP Code Changes ⚠️ 
A significant amount of PHP code that operates on the frontend, saving styles from the editor, has been moved, refactored, and modified. Please keep this in mind and allocate time to thoroughly test the previous MaxiBlocks functionality to ensure everything works as expected.

### For developers
- Impact on CLI: When adding new functionality to the JavaScript side, consider how it affects the CLI.
- Unit Tests: If you write unit tests on the JavaScript side, remember to implement corresponding PHP unit tests. Ensure that the results from both JavaScript and PHP tests match.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the style card commands
-   [ ] Test the post control commands: if styles, fonts, custom data apply correctly in different cases
-   [ ] Test the export control commands: : if styles, fonts, custom data apply correctly in different cases
-   [ ] Test if on saving post from editor everything works as before: styles, fonts (test bunny fonts as well to ensure that on merge nothing was lost), custom data, etc
-   [ ] Test maxi in general, try different cases, create posts from scratch with editor/CLI, paste code editors with editor/CLI, import/export...

**_ Pre-Code Testing _**

-   [ ] Test the style card commands
-   [ ] Test the post control commands: if styles, fonts, custom data apply correctly in different cases
-   [ ] Test the export control commands: : if styles, fonts, custom data apply correctly in different cases
-   [ ] Test if on saving post from editor everything works as before: styles, fonts (test bunny fonts as well to ensure that on merge nothing was lost), custom data, etc
-   [ ] Test maxi in general, try different cases, create posts from scratch with editor/CLI, paste code editors with editor/CLI, import/export...
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/9ba1f8a0-7fd9-4cf0-a855-1deb55f105b3
some of the elements are disappeared on frontend  after change SC by CLI( even from HTML )
checked on HOL-PRO-62

UPD from @Fybex:
2) Posts with number counter fails (get_number_counter_styles fails at line 97)

image

**Comment by elzadj** [comment]
```
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package sebkay/wp-unit-test-stubs is abandoned, you should avoid using it. No replacement was suggested.
```
probably need to do something with this ^

**Comment by elzadj** [comment]
@Fybex let's say we have a WP install on an external server, we install this branch there. What we need to make it work on that current site? Install WP CLI on the server, what else? Change some configs?

**Comment by Fybex** [comment]
> ```
> Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
> Package sebkay/wp-unit-test-stubs is abandoned, you should avoid using it. No replacement was suggested.
> ```
> 
> probably need to do something with this ^

Done 👍 

> @Fybex the buttons code changed (so the tests fail), is it expected, and we need to update snapshots, or do we have a bug somewhere?

New attribute `widthHeightRatio` was added to keep that setting in attributes to make it possible to have correct styles in CLI for blocks with **"Set height to fit content"** switch on. Also, fixed broken `getSizeStyles` which were failing, but there was reason for that from my changes.


> @Fybex let's say we have a WP install on an external server, we install this branch there. What we need to make it work on that current site? Install WP CLI on the server, what else? Change some configs?

First, we need to load our plugin on WordPress with the composer libraries installed: `composer install --no-dev --optimise-autoloader`.

Next, nothing needs to be done on the part of maxi. You need to install the WP CLI on the server https://make.wordpress.org/cli/handbook/guides/quick-start/ and that's it.

**Review by Olekrut — CHANGES_REQUESTED** [review]
Looks ok, Except, SPEED, Really much slower on this branch. (editor )

And it's like the laptop is about to take off, it's much harder on this branch.

**Comment by Fybex** [comment]
> Looks ok, Except, SPEED, Really much slower on this branch. (editor )
> 
> And it's like the laptop is about to take off, it's much harder on this branch.

Almost all the changes out of the 505 changed files were made on the server side, which does not affect the speed of the editor. I retested the speed by inserting some template and didn't see any difference. Could you reproduce it again and record a comparison video (this branch and master) where you can see the performance drop for sure?

**Comment by elzadj** [comment]
> Almost all the changes out of the 505 changed files were made on the server side, which does not affect the speed of the editor. I retested the speed by inserting some template and didn't see any difference. Could you reproduce it again and record a comparison video (this branch and master) where you can see the performance drop for sure?

You added attributes back to block.json files, that alone really slows everything in the editor (that's why we removed them in the first place).

**Comment by Fybex** [comment]
> You added attributes back to block.json files, that alone really slows everything in the editor (that's why we removed them in the first place).

I was thinking about that too, but I didn't think it would make that much of a difference. Then I'll store the block attributes in jsons that are not connected to the editor, just like I store group-attributes. I'll create an attributes' folder in the root of the project, with two subfolders:
- groups
- blocks

Also curious to see if performance tests will show slow down or not

**Comment by Fybex** [comment]
Interesting. The speed of working with block.json files injected into registerBlockType is faster, at least the performance tests say this.

With block.json files (commit: https://github.com/maxi-blocks/maxi-blocks/pull/5667/commits/eb4059f79069fa3c3c943268359c1276ed8639dc):
- https://github.com/maxi-blocks/maxi-blocks/pull/5667#issuecomment-2318233482
- https://github.com/maxi-blocks/maxi-blocks/pull/5667#issuecomment-2319495966

Without block.json, instead - a metadata folder:
- https://github.com/maxi-blocks/maxi-blocks/pull/5667#issuecomment-2318445853
- https://github.com/maxi-blocks/maxi-blocks/pull/5667#issuecomment-2319057117

**Pull request closed without merging**
