### PR TITLE
Issue 4664 - Increase max number of Columns in a Row

### PR DESCRIPTION
**Pull request by FitseTLT**
# Description
added row column picker option to allow more than eight columns

Fixes #4664

# How Has This Been Tested?
By adding more than 8 columns in grid (row)

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
Imperceptibly that you need to click it) need to make it more mandatory to click..
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) need to add transition for hover
2) 
image
after click and if hold mouse button, text is changing to black

maybe a button should be unlickable if it is active ( make it blurred in active state)

**Review by Olekrut — CHANGES_REQUESTED** [review]
image

need to hide apply button for not base BPs

**Review by Olekrut — CHANGES_REQUESTED** [review]
no, why have hidden schemes for 1-8 col?
need to hide apply button for 9 and more col, because this button has no sense on not base breakpoint

**Review by Olekrut — APPROVED** [review]

**Review by darimshlk — APPROVED** [review]

**Pull request merged**
