### PR TITLE
Issue 5551: for theme

### LINKED ISSUE #5551: For theme: vol 2
### Description

1. Padding for template parts from WP: 
screenshot-wordpress local-2024 04 16-18_29_37
2. Author page and Data page with All Archive (without re-saving):
screenshot-wordpress local-2024 04 16-18_30_48
3. Default SC doesn't work with native blocks, need to copy it in SC Editor to make it work. (check sc_string in the DB). Affects Nav, pagination, comments form, etc.

### Step-by-step reproduction instructions

---

### Screenshots, screen recording, code snippet

_No response_

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

See the issue for details: https://github.com/maxi-blocks/maxi-blocks/issues/5551

1. To recreate on master: try to add any footer in a footer template part, then insert it into a template, and check that template on frontend. Best works with All Archives, when the blocks are Dark.
2. Add all archives from our theme, check author and date archives.
3. Reset the SCs, don't change them, and check the frontend with native blocks.

Fixes #5551

# How Has This Been Tested?

Check DC on frontend for authors and current.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Added conditional content blocks that adapt based on authorship and date.
  - Introduced new date formatting options for date-based content queries.
  - Implemented a fallback mechanism for retrieving user content under specific conditions.
  - Enabled `gutenberg_blocks_status` to enhance configuration settings.

- **Enhancements**
  - Improved logic for setting content relationships to 'current' in specific scenarios.
  - Enhanced data retrieval handling in taxonomic content queries.

- **Style Updates**
  - Updated CSS for banners to adjust top and bottom margins when specific blocks are active.

- **Refactor**
  - Optimized logic to handle different archive types more efficiently in content ordering.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) point 2, works well, but need to remove margin for .entry-content as well
theme 2024
image
2) mistake in style max-width:100%; for textarea, there is maxi-width:100%, because it does not work, extra letter
image

**Review by Olekrut — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
sorry, typo is not fixed
image

**Comment by elzadj** [comment]
> sorry, typo is not fixed image

https://github.com/maxi-blocks/maxi-blocks/pull/5552/files#diff-fea76df89efb91249d93a5ea43207f69fa9017c0f6ab03dc388721c58ec4b084

Screenshot from 2024-04-17 20-50-51

**Comment by Olekrut** [comment]
image
looks like fixed, but not ewerywhere

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
