### PR TITLE
Issue 3525 - add path aliases and remove all `..` in imports

### LINKED ISSUE #3525: Sweep:Add Path aliases
This issue must reduce multiply `../../` in import paths.

Solution: we can create path aliases.

Links: 
- https://webpack.js.org/configuration/resolve/
- https://dev.to/mmcshinsky/webpack-aliases-keep-my-code-sane-3c3e

Code before:
```
import { MaxiBlockComponent, withMaxiProps } from '../../extensions/maxi-block';
import { Toolbar } from '../../components';
import { MaxiBlock, getMaxiBlockAttributes } from '../../components/maxi-block';
```

Code after: 
```
import { MaxiBlockComponent, withMaxiProps } from '@extensions/maxi-block';
import { Toolbar } from '@components';
import { MaxiBlock, getMaxiBlockAttributes } from '@components/maxi-block';
```

Maybe it's not that critical when we are repeating `../` two times, but in many places we are repeating it 4 times, so we can fix it with alias 😄 👍

### PR DESCRIPTION
**Pull request by myroslavve**
# Description

This PR adds path aliases, in order to remove relative imports. This allows us not to worry about the location of files while developing and refactoring, so we can move file to different location and not have to update imports inside it, also reduces possible mistakes while writing imports.

Installed additional package in order for ESLint to get path aliases from webpack configuration.

Moved and updated configuration for e2e tests and created config for unit tests in order for them to support path aliases.

Fixes #3525

# How Has This Been Tested?
Checked that webpack build gives no errors, and maxi works in general on editor, frontend, FSE.

# Test checklist

-   [ ] Check that `npm run build` doesn't generate any errors or warnings.
-   [ ] Check that all tests pass.
-   [ ] Check that VS Code Intellisense works (code tips, `ctrl`+`click` on import path takes you to the file).
-   [ ] Check that maxi works in general.

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kyrapieterse** [comment]
sometimes the files get too big and hard to read and navigate, so we split them to make them more readable, and sometimes it just doesn't make sense to have file where it is anymore, for example if its code is used in multiple places, so we can move it.

And when moving a file to a different directory, we had to replace paths to files that it depends on, because they were relative to that file.
Also it is just easier to understand what we are importing when I see:
import something from '@extensions';
rather than:
import something from '../../../extensions';

And when writing imports, although it is helped by vscode tools, it's hard to imagine what is the path to the file you are importing relative to current, I used to mess this up sometimes, and AI also makes mistakes with this kind of import.

So it just makes easier to write code

**Comment by elzadj** [comment]
Looks great, but that config did not work for me in Cursor editor - it just can't get the paths. I've created [a new branch](https://github.com/maxi-blocks/maxi-blocks/tree/issue-3525-cursor-editor) that works in Cursor - all changes are in webpack config. Please test that it works ok in VS Code, and maybe merge. 

Also, conflicts.

**Review by elzadj — CHANGES_REQUESTED** [review]
.

**Comment by myroslavve** [comment]
> Looks great, but that config did not work for me in Cursor editor - it just can't get the paths. I've created [a new branch](https://github.com/maxi-blocks/maxi-blocks/tree/issue-3525-cursor-editor) that works in Cursor - all changes are in webpack config. Please test that it works ok in VS Code, and maybe merge.
> 
> Also, conflicts.

Cursor, or VS code, don't look at the webpack config but rather at `jsonfig.json`, so I don't think that that change fixes anything for Cursor.
I'd like to keep config closer to default, so if you could check on this branch once more, but reload Cursor after switching to this branch. I will merge that branch if it still doesn't work, just want to double-check.

**Comment by elzadj** [comment]
Actually, Go To Definition stopped working at all, maybe a bug in Cursor, so let's ignore it for now
https://forum.cursor.com/t/cmd-click-go-to-function-definition-functionality/3347/25

**Review by elzadj — APPROVED** [review]

**Pull request merged**
