### PR TITLE
Issue 5277 - RTL 03

### LINKED ISSUE #5277: RTL - 03
### Description

Fix how every block looks like backend/frontend with an RTL language enabled.

### Step-by-step reproduction instructions

Change to a RTL language.

### Screenshots, screen recording, code snippet

_No response_

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Marko64**
Fixes #5277

As we discussed, we can't do much about the blocks in RTL. We can't force any styles that users are meant to change through settings for example, such as margins and padding. Fixed some minor things such as the template library button and accordion pane (arrrow is now on the left and title on the right).

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Introduced RTL (Right-to-Left) language support for various components.

- **Style**
  - Added new styles to enhance the visual layout and accessibility for RTL languages.
  - Implemented additional styling for a more cohesive user interface experience.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
RTL broke lists
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
some options for list are not working
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
marker indent does not work correct for List style position: Inside
https://jam.dev/c/a67d8b53-2c70-42d3-8d10-011e8973f38b

**Review by Olekrut — APPROVED** [review]

**Comment by elzadj** [comment]
@Marko64 could you please check text-maxi tests? Seems like margin-left: and margin-right switched places, if that's not a problem, update snapshots maybe?
icon-colour test is a false-positive, ignore it

**Review by elzadj — APPROVED** [review]

**Pull request merged**
