### PR TITLE
Issue 3711 - Active state transitions

### PR DESCRIPTION
**Pull request by moroz-art-dev**
# Description

It is described in detail in issue.
Added the ability to pass an array of values ​​to hoverProp

Fixes #3711

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [x] Place the Maxi accordion component
-   [x] Settings / Settings / Title / Active state - > turn on 
-   [x] Settings / Advanced / Hover Transition (make sure it's active)

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Naaaaiix — COMMENTED** [review]
Good job @moroz-art-dev 👍 

Left a suggestion, check it please 😸

**Review by Marko64 — CHANGES_REQUESTED** [review]
Transitions are not working for me either for the title.

**Review by Fybex — CHANGES_REQUESTED** [review]
Need to modify `getTransitionStyles` function to make `hoverProp` check correct to display styles. Now you are checking it only in `inspector-transition`.

Here is a video with the problem and solution:

https://user-images.githubusercontent.com/46112160/198072051-84a49216-12f2-4bf7-80ee-01a819686f74.mp4

P.S. Wrote that snippet fast, test it a bit it to ensure that it's working in all situations 👍

**Review by Olekrut — APPROVED** [review]

**Review by Fybex — CHANGES_REQUESTED** [review]
What about accordion icon? Also has active state.

P.S. Fixing myself: it won't work because icon changes to switch to active state, so ignore this comment

**Review by Fybex — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
Cool!

The change done on `e2e-tests/components/video-options-control/__snapshots__/index.spec.js.snap` seems is breaking the e2e tests; try rolling that file back 👍

**Pull request merged**
