### PR TITLE
Text split fix / new default blocks

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Adds Maxi blocks as default, fixes the Text split.

- When you create a new page, a click in the Editor adds a Container, not a paragraph (same in FSE).
- When you create a new post, a click in the Editor adds a Text Block, not a paragraph.
- When you create anything that is not a single post, you get a Container.
- Enter on a selected Text block (or when your cursor is inside it) always creates a new Text block.
- CTRL + Enter inside a Text block create new line (as expected)
- Enter on a selected Container always creates a new Container.

Note: we probably need to add a placeholder to our Text Block, as @Olekrut suggested, because an empty Text looks a little weird.

# How Has This Been Tested?

Needs testing and suggestions. Not sure what to do with CPT (Container, I guess). 

And please test Lists (you should always get a new list item on Enter).

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Added support for text splitting in the `maxi-blocks/text-maxi` block.
	- Enhanced default block naming functionality based on block selection.
	- Improved block management in the WordPress editor to set default block names dynamically.
	- Introduced responsive preview adjustments and streamlined style management in the `MaxiBlockComponent`.
	- Enhanced block attribute management and UI behavior based on the block's position within the editor.
	- Added new styles for the `.maxi-block-inserter` class, including a button with hover and focus states.

- **Bug Fixes**
	- Ensured that the default block name updates correctly based on post type.

- **Tests**
	- Streamlined content insertion process in end-to-end tests for the repeater component.
	- Enhanced robustness of end-to-end tests for the "Delete block" functionality with improved DOM manipulations.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/6ad969d1-929b-467c-aad7-28675ee18fbb
weird that click to empty field is creating new text block or container. Guess, it should work only if we are clicking to Gutenberg paragraph

**Comment by elzadj** [comment]
> https://jam.dev/c/6ad969d1-929b-467c-aad7-28675ee18fbb weird that click to empty field is creating new text block or container. Guess, it should work only if we are clicking to Gutenberg paragraph

It's not weird, it's how Gutenberg works. It creates a "default block" on click, and it's a paragraph by default. We replace that default block to Text or Container, depending on the post /page type.

**Comment by Olekrut** [comment]
> It's not weird, it's how Gutenberg works. It creates a "default block" on click, and it's a paragraph by default. We replace that default block to Text or Container, depending on the post /page type.

ooo, idk, how is better for users, but i don't like it, because I can just click on a field, or for hiding the toolbar's settings submenu. Then i will should to remove it, or can just miss it, and we will have empty text in pattern

**Comment by elzadj** [comment]
Adding a green block inserter (that we have between blocks now) to the last block is an option too.

**Comment by Olekrut** [comment]
> Check now pls. I guess we also need to add a block inserter to the last Text block on a post, like we have for the last Container.

Yes, I like it more!!! Cool

We can use for it inserter in panel if pick last block ( almost always using it like that )
image

Maybe we can improve between inserter. Lets it appears in the end as well if possible
image

**Comment by elzadj** [comment]
@ckp267 please check this one when you have time, thanks.

**Review by ckp267 — APPROVED** [review]
This work great now! 

Adds Maxi blocks as default, fixes the Text split.
- When you create a new page, a click in the Editor adds a Container, not a paragraph (same in FSE).
- When you create a new post, a click in the Editor adds a Text Block, not a paragraph.
- When you create anything that is not a single post, you get a Container.
- Enter on a selected Text block (or when your cursor is inside it) always creates a new Text block.
- CTRL + Enter inside a Text block create new line (as expected)
- Enter on a selected Container always creates a new Container.

**Comment by elzadj** [comment]
> This work great now!
> 

@ckp267 Cool, thanks! We still need to add a replacement for the block inserter at the end of the editor's content. 
What should we do? There are some options listed above.

**Comment by elzadj** [comment]
> maybe the dropdown for pages" "Add a row", "Add a Container"
> and the green one for posts where we have Text by default 

> If you can just make the ROLL OFF on the green with a sligh dely 500ms maybe so it does not disappear so quickly. Easy to miss on roll over.

**Comment by elzadj** [comment]
@Olekrut @ckp267 added this to the last maxi block in the editor, instead. It behaves the same as the default block inserter from the paragraph.

Edit-Page-‹-MaxiBlocks-—-WordPress-10-30-2024_01_56_PM

**Review by Olekrut — APPROVED** [review]

**Comment by Olekrut** [comment]
image
@ckp267 @kyrapieterse Maybe we should make this inserter with another design? Another colour ( maybe black ) and bigger ( x2 )

**Comment by ckp267** [comment]
As per chat thread- Adjusting the styling for an "Add Block" button. Here’s a summary of the final decisions and actions to take based on the comments:

1. **Button Colour and Size**:
   - The button should be slightly larger.
   - The colour should be black or a dark grey to ensure visibility on different backgrounds.
   - A border might be considered (though the exact colour wasn’t decided).

2. **Tooltip Text**:
   - Ensure the tooltip text clearly explains the button’s purpose so that users understand its function when they hover over it.
   - This seems to refer to the default "Add Block" tooltip, with a note to make sure it’s intuitive.

3. **Style Consistency**:
   - The button should use default styling for the "Add Block" but adapted to the specific styles of the project.

In summary, the action points are:
- Adjust the button to be slightly bigger and in a dark colour (likely black or dark grey).
- Add or confirm a descriptive tooltip for clarity.
- Use the default "Add Block" styling but within the project’s specific style guidelines.

**Comment by elzadj** [comment]
@Olekrut @ckp267 changed the styles, basically copied the styles of the default one. 

The toolltip + hover:

Add-a-New-Post-‹-MaxiBlocks-—-WordPress-10-30-2024_06_52_PM

The inserter + hover 
[Edit-Page-‹-MaxiBlocks-—-WordPress (1).webm](https://github.com/user-attachments/assets/62c0d73d-2046-4670-a0a8-c65f832a3700)

The inserter + hover on black bg
[Edit-Page-‹-MaxiBlocks-—-WordPress (2).webm](https://github.com/user-attachments/assets/4c457ea9-9564-4ea7-939d-c6ba0e4e387e)

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
