### PR TITLE
Issue 5561: pagination and repeated CL content

### LINKED ISSUE #5561: Pagination bug
### Description

If you have blog with 2 posts per page and you have published only 3 posts or If you have blog with 9 posts per page and you have published only 13 posts > you will not see pagination link to next page.
you can see next page if you will add posts more than  ( 2x per page amount )

### Step-by-step reproduction instructions

1) publish 3 posts (not more)
2) load blog with 2 post per page
3) check pagination on frontend ( you can't see 3rd post )

### Screenshots, screen recording, code snippet

https://jam.dev/c/cdf8edc6-866d-40f8-abe8-4b618f7d7a62

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

1. Hides repeated content for CL (posts only for now, no ACF or Woo).
2. Shows the last page in pagination, even if it's not full of posts.
3. Hides pagination if it's only one page.
4. Sets "items per page" by children count in the editor (was always 3 before).

Fixes #5561

# How Has This Been Tested?

1. Please do not test with block patterns with static text ('Posted by, 'Author', etc.), or remove that text in the editor. This is going to be another PR.
2. You need to re-save the page with the blog if you enabled pagination on master, and posts per page is not 3.
3. Please test complex columns and rows too, ```justify-content: space-between;``` was removed from the default row styles to fix columns when we don't have a full set of posts on a page.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Enhanced block rendering to handle empty content scenarios more gracefully.
	- Improved dynamic content handling across various components to support repeated posts.
	- Introduced new attributes and conditions in block components to refine content editing and display based on dynamic content settings.
	- Added new dynamic content types and enhanced pagination logic for better content management.
  
- **Bug Fixes**
	- Adjusted CSS styles to improve layout consistency when certain classes are applied.

- **Refactor**
	- Updated several components to utilize new state management hooks for better performance and reliability.

- **Style**
	- Removed specific CSS properties to align with new design guidelines.

- **Documentation**
	- Updated internal component documentation to reflect new features and changes.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/ff5a629b-92f8-4322-952b-a1a349d3dc1e
when we have empty columns one under one > big space
2) not sure how it should work with patterns like blog 73
https://jam.dev/c/e8214d6b-b4ed-431f-a1f1-8e9704c310aa
3) https://jam.dev/c/372cfcd0-50e1-4bc9-a074-ad871905fb12
some of blogs are invisible
[blogs.txt](https://github.com/maxi-blocks/maxi-blocks/files/15181136/blogs.txt)

**Comment by elzadj** [comment]
> 1. https://jam.dev/c/ff5a629b-92f8-4322-952b-a1a349d3dc1e
>    when we have empty columns one under one > big space
There is a svg icon that is not connected to DC. Basically, the same thing as with "Posted" text, it stays.

**Comment by elzadj** [comment]
@Olekrut could you please check block 73 on master too? It looks weird on frontend when I choose by category - by date - old new.

**Comment by elzadj** [comment]
> https://jam.dev/c/ff5a629b-92f8-4322-952b-a1a349d3dc1e
> when we have empty columns one under one > big space

Add DC link to that svg. That's going to fix it and hide it.

**Comment by elzadj** [comment]
Added an option to make Text static to link it to current DC / CL:

screenshot-wordpress local-2024 05 03-16_52_57

**Review by Olekrut — APPROVED** [review]
I ve noticed a few  problems. Will be need to remake blog patterns
1) dividers ( cant be DC )
2) wrapper group with dc text and enabled link, > wrapper group cant have dc link in this case - example - blog 3 and 97

**Comment by elzadj** [comment]
> I ve noticed a few problems. Will be need to remake blog patterns
> 
> 1. dividers ( cant be DC )
> 2. wrapper group with dc text and enabled link, > wrapper group cant have dc link in this case - example - blog 3 and 97

Let me see if I can figure something out. Need to fix conflicts anyway.

**Comment by elzadj** [comment]
And need to extend the code for CL / DC for ACF and Woo

**Comment by elzadj** [comment]
> I ve noticed a few problems. Will be need to remake blog patterns
> 
> 1. dividers ( cant be DC )
> 2. wrapper group with dc text and enabled link, > wrapper group cant have dc link in this case - example - blog 3 and 97

Please recheck these 2. I've added DC for dividers with one field "Static":

screenshot-wordpress local-2024 05 06-15_22_24

And fixed the empty groups not hiding automatically.

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
