### PR TITLE
issue-2501 Fixed

### PR DESCRIPTION
**Pull request by FitseTLT**

### CODE REVIEW

**Review by Alejandro9kgm — APPROVED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
This issues hasn't been fix as just one of the three requested fixes has been done. Here's a video:

https://user-images.githubusercontent.com/50477222/151936362-3383317a-554f-4e25-9f3c-1a43b6e7b947.mp4


So, things necessary to fix:

- [ ] 1. On changing from palette to custom, custom should take the colour of palette as commented on video.
- [ ] 2. The button `Inherit Colour/Background from Button` is not working as explained on the issue and in the video.
- [ ] 3. Icon gradient background doesn't work also

**Review by Alejandro9kgm — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
Looks like the Icon BG colour resets on the editor reload: 

https://user-images.githubusercontent.com/2401618/152826560-82e38887-6731-449c-a104-55a5a67308cb.mp4

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Found an error when tried gradient:

https://user-images.githubusercontent.com/50477222/152985960-e1220026-ad4a-468f-bd85-f8d7917a3c73.mp4

**Review by Naaaaiix — APPROVED** [review]
> @Naaaaiix Couldn't reproduce the error you are claiming
> 
>  Edit.Page.maxi-blocks.WordPress.-.8.February.2022.mp4 
> .

Oh right, my fault 😅 I'm on WP 5.9 as I'm currently working on #2504 lol

The broken test can be updated, so onces done this PR is approved by my side. Good job @FitseTLT 😸

**Review by bilouStrike — APPROVED** [review]

**Pull request closed without merging**
