### PR TITLE
Adds back current and current archive options

### LINKED ISSUE #5504: Relation: get current is gone
### Description

Relation: get current is gone

### Step-by-step reproduction instructions

1) check relation in DC

### Screenshots, screen recording, code snippet

image

image

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Adds back Get current and Get current archive options for DC and CL that were hidden in the UI.

Fixes #5504 

# How Has This Been Tested?

Please test it in all places in the editor you can think of, on 6.5 and 6.4.3 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved the logic for adding new items in the options array to prevent duplicates and ensure only allowed items are added.
	- Refined the condition for including new items based on `allowedTemplateTypes` to ensure unique items are added.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/039cddc7-7370-4abd-830f-64f7136fe26f
Is not fixed

**Comment by elzadj** [comment]
> https://jam.dev/c/039cddc7-7370-4abd-830f-64f7136fe26f Is not fixed

@Olekrut  It is, maybe cache, or npm start failed?

screenshot-wordpress local-2024 03 19-12_56_40

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) wp6.4.3 and wp6.5-rc3
1.1) I see get current archive, but not **get current** for post
1.2) get current archive should be visible only for archive templates, no?
image

**Comment by elzadj** [comment]
> 1. wp6.4.3 and wp6.5-rc3
>    1.1) I see get current archive, but not **get current** for post
>    1.2) get current archive should be visible only for archive templates, no?

@Olekrut :
1.1 Get current on a post (both wp versions):

screenshot-wordpress local-2024 03 20-17_03_58

screenshot-wordpress local-2024 03 20-17_04_35

screenshot-wordpress local-2024 03 20-17_06_13

1.2 I don't see it, at least on 6.5, please provide the pattern's code:

screenshot-wordpress local-2024 03 20-17_13_58

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
