### PR TITLE
Issue 3574 - right width on small breakpoints

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Width on small breakpoints is now set to `.is-${mobile||tablet}-preview` element instead of `.edit-post-visual-editor`, because this is where gutenberg sets width for responsive. Also hid scrollbar on small breakpoints.

Fixes #3574

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [x] Check that when clicking maxi responsive buttons, width of editor is correct for that breakpoint.
-   [x] Check that when clicking gutenberg preview buttons, their preview width is set.
-   [x] Check that scrollbar on S and XS breakpoints is hidden in all browsers.

**_ Pre-Code Testing _**

-   [x] Check that when clicking maxi responsive buttons, width of editor is correct for that breakpoint.
-   [x] Check that when clicking gutenberg preview buttons, their preview width is set.
-   [x] Check that scrollbar on S and XS breakpoints is hidden in all browsers.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — CHANGES_REQUESTED** [review]
I'm still not getting the same values as I have them in the dashboard.
XL, L and M are 10px less than the backend.
XS and S add 2px to the backend values. 

If you need screenshots or video, let me know.

**Review by Marko64 — APPROVED** [review]

**Review by Fybex — CHANGES_REQUESTED** [review]
Changes broke editor look with iframe
Before:
image
After: 
image

I think we shouldn't change place where we're changing width on breakpoints, we just should set width 100% where gutenberg adds theirs width

**Review by Fybex — CHANGES_REQUESTED** [review]
With maxi responsive button s width - 767px
with gutenberg button s - 780

Should be always 767px

**Review by Fybex — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
Cool! 👏 

This should make library developing faster, and a closer experience between EE and VE 💯

**Pull request merged**
