### PR TITLE
Text Maxi - Toolbar link

### PR DESCRIPTION
**Pull request by Naaaaiix**
Fixed Toolbar Link issue on Text Maxi. To test:
- Add a link in general (not selecting any text)
- Remove the link
- Add a link in selected text
- Remove that link
- Add more than one link selecting different part of the text
- Remove more than one link

Tests has been done also in this branch. If you have any other test I could do, please suggest them here 👍

### CODE REVIEW

**Review by Alejandro9kgm — APPROVED** [review]

**Review by javadsamiee — COMMENTED** [review]
I saw this console error

https://user-images.githubusercontent.com/65819265/115671603-f0141280-a35f-11eb-9dbc-f0f02892dca0.mov

**Review by Alejandro9kgm — APPROVED** [review]

**Review by javadsamiee — COMMENTED** [review]
After "Remove Link" repeatedly I saw this console error

image


image

**Review by javadsamiee — COMMENTED** [review]
I saw this one

https://user-images.githubusercontent.com/65819265/115825475-beae4c00-a41e-11eb-810b-8c170d8f5cdd.mov

**Review by javadsamiee — APPROVED** [review]
Tada  🥳

**Pull request merged**
