### PR TITLE
Issue 3324 - shape divider responsive

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Implemented responsive on shape divider.

Fixes #3324 

# How to test?
Change shape divider settings on different breakpoints.

# Test checklist

**_Front/Back Testing_**

-   [x] Test the component in normal state in sidebar
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-3 points on responsive

**_Pre-Code Testing_**

-   [ ] Test the component in normal state in sidebar
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-3 points on responsive
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]
Not related to this PR, but just mentioning what I noticed:
- Looks like divider height has some limit
- Unit is a dropdown, but you can only select PX,. Should we add other units, or remove the dropdown?

**Review by FitseTLT — CHANGES_REQUESTED** [review]
Nice. Only just U need to add responsive controls below the shape divider.

**Review by FitseTLT — CHANGES_REQUESTED** [review]
The responsive control should be below the shape divider selector as we have no responsive options for it.

**Review by FitseTLT — CHANGES_REQUESTED** [review]
Looks like we need migrators for these too.

**Review by Marko64 — APPROVED** [review]
If I tested correctly, I think it works.
I used the pattern shared 'shapedividermigrator.txt'. Loaded it on an old branch and updated the page. Than switched to this branch and made sure it works after page reload.

**Review by FitseTLT — COMMENTED** [review]
Shape divider colors set on the previous branches will not be applied to this branch. It would be nice if the shape divider color set on the previous branches will be set for shape-divider-color-general.

**Review by FitseTLT — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
