### PR TITLE
Issue 2927 - Video maxi

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Video maxi.

I removed reduce black borders switch, because ways to reduce them are by zooming in video, which cuts off part of content which is not expected, or choosing correct aspect ratio or size of video, which users do themselves.

Fixes #2927 

# How Has This Been Tested?

Test block with different settings, check if it looks and works as supposed.
# Test checklist

**_Front/Back Testing_**

-   [ ] Test the video on backend
-   [ ] Test the video on frontend
-   [ ] Check video settings work
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_Pre-Code Testing_**

-   [x] Test the video on backend
-   [x] Test the video on frontend
-   [x] Check video settings work
-   [x] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — CHANGES_REQUESTED** [review]
Still see this one: 
- Video popup: if you reduce the height you can see the placeholder image behind:

I think we need to add overflow: hidden; for the overlay div.

**Review by Marko64 — APPROVED** [review]

**Review by Fybex — CHANGES_REQUESTED** [review]
Border on frontend always has black colour, box-shadow don't work at all on frontend.

Also, what about transitions? Should we add them for Video maxi here or in a new issue?

**Review by Fybex — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
Looks good, just need to fix the bugs ^

**Review by Naaaaiix — APPROVED** [review]
@TeksPeks my most personal congratulations; I was at the expectation to review this branch, and I was expecting to be impressive, but it has overpassed my expectations. If I should have to give a punctuation would be a 101/100; no big issues, all clean and simple on its complexity, perfect organized and powerful. Amazing, I'm impressed. Thanks for your dedication 👏 🎉 

PS: @elzadj merge when you consider the errors you found are fixed 👍

**Review by elzadj — APPROVED** [review]

**Pull request merged**
