### PR TITLE
Issue 5300: DB version warning

### LINKED ISSUE #5300: DB warning on plugin install
### Description

Need to adjust the MySQL warning styles, make it dismissible + add mariaDB detection.

### Other plugins or websites examples

_No response_

### How to implement it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Adds warning for MariaDB, makes it dismissible, changes some styles + text for it.

Fixes #5300 

# How Has This Been Tested?

To test, up the version in plugin.php on your local, line 27 for mySQL
``` define('REQUIRED_MYSQL_VERSION', '8.0'); // change to something like 10.0 ```
line 28 specifically for MariaDB 
```define('REQUIRED_MARIADB_VERSION', '10.4'); ; // change to something like 11.4 ```
You can test mariaDB on staging, the plugin is already installed there, but please also test on your local.

You then should see 

screenshot-stagingdemo maxiblocks com-2023 12 08-15_39_35

or a similar warning for MySQL on local. You should be able to dismiss it, and it should stay hidden if you dismissed it. To see it again, remove maxi_blocks_db_notice_dismissed option from your options table on local.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the warning
-   [x] Test that it's dismissible

**_ Pre-Code Testing _**

-   [ ] Test the warning
-   [ ] Test that it's dismissible
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Style Updates**
  - Improved the visual presentation of admin notices with updated styling.

- **New Features**
  - Enhanced admin interface with dismissible notices and style resets upon dismissal.
  - Implemented version checks for database compatibility and relevant user notifications.

- **Documentation**
  - Updated internal documentation to reflect changes in function names and purposes.

- **Bug Fixes**
  - Fixed issues with admin notice dismissal not persisting correctly after plugin updates.

### CODE REVIEW

**Review by Olekrut — APPROVED** [review]

**Review by Marko64 — CHANGES_REQUESTED** [review]
FF is acting weird with dismissing. When you press X the message is dismissed but it comes back on reload. Only after dismissing for the second time the message is dismissed for good.

**Comment by elzadj** [comment]
@Marko64 can't recreate on FF 120.0.1, could you please make me a video?

**Comment by Marko64** [comment]
Could be my localhost too, it's very slow.
https://github.com/maxi-blocks/maxi-blocks/assets/19425503/571a594d-818c-4d64-abf0-62d41b6bb9b9

**Comment by elzadj** [comment]
@Marko64 to exclude your localhost - test on staging too.

**Comment by Olekrut** [comment]
> FF is acting weird with dismissing. When you press X the message is dismissed but it comes back on reload. Only after dismissing for the second time the message is dismissed for good.

I can't re-create it on FF

**Pull request merged**
