### PR TITLE
Issue 2835 - infinite slider loop

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Slider infinite loop.

Fixes #2835

# How Has This Been Tested?
Test loop both on backend and frontend.

# Test checklist

**_Front/Back Testing_**

-   [x] Check if loop works on backend
-   [x] Check if loop works on frontend
-   [x] Change first/last slides, and check if loop works on backend
-   [x] Same on frontend

**_Pre-Code Testing_**

-   [x] Check if loop works on backend
-   [x] Check if loop works on frontend
-   [x] Change first/last slides, and check if loop works on backend
-   [x] Same on frontend
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — CHANGES_REQUESTED** [review]
I see two issues:
1. The - and + buttons do not work yet. Perhaps this wasn't yet implemented and you planned to add it later?
2. The backend doesn't work even with the dragging for me. 

Attaching a video:
https://user-images.githubusercontent.com/19425503/172783322-1d4e2053-10d3-4f7a-9101-3eff124d5d60.mp4

**Review by Marko64 — APPROVED** [review]
Ignore me. Once again I am not able to replicate the issues I could before. Have to figure out why is that happening to me. If  I didn't make a video I'd thought I'm crazy lol.

**Review by Fybex — CHANGES_REQUESTED** [review]
Order and switching is broken if select Slides from List view, on switch loop current slide is changing what is as well can be fixed

Also, sometime can't change slide from first attempt, need to click a few times to change the slide or I'm pressing the '+' but get slide, which was the left, but I can't reproduce it always which is quite confusing 🤔 

https://user-images.githubusercontent.com/46112160/173050151-3ef64ea5-8e74-4742-9554-6261406c7b2f.mp4

**Review by Fybex — APPROVED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Found some bugs on backend:

https://user-images.githubusercontent.com/50477222/173564542-b0104771-fa95-4a1c-9f8b-b52e5a1f1946.mp4

👍

**Pull request closed without merging**
