### PR TITLE
Issue 5361 - Support Yoast Duplicate Post plugin duplicate

### LINKED ISSUE #5361: Bug with displaying frontend on different pages Round 2
### Description

Was similar in https://github.com/maxi-blocks/maxi-blocks/issues/5155

### Step-by-step reproduction instructions

1) create page with container ( light tone )
2) duplicate page ( i ve used Yoast Duplicate Post plugin for it )
3) change tone to dark on duplicated page and publish 
4) check tone on frontend for first page

### Screenshots, screen recording, code snippet

https://jam.dev/c/53033064-019f-4097-8509-d0c840614e8a

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Fybex**
# Description

### Merge after #5368 

Fixes #5361 

Updates blocks' `uniqueID` on Yoast Duplicate Post plugin duplicate

# Test checklist

**_ Front/Back Testing _**

-   [x] Check if the issue problem is gone

**_ Pre-Code Testing _**

-   [ ] Check if the issue problem is gone
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors

## Summary by CodeRabbit

- **New Features**
  - Introduced a new filter to maintain unique block IDs when duplicating posts.
  - Added functionality to ensure the integrity of block styles and IDs after duplication.

- **Enhancements**
  - Improved the handling of block content and styles in the editor.
  - Enhanced the state management for block styles, allowing for more efficient updates and caching.

- **Bug Fixes**
  - Fixed an issue where block content might not correctly merge due to incorrect array checks.
  - Addressed a potential problem with block ID conflicts by refining the duplication logic.

- **Refactor**
  - Streamlined the logic for recursive block style computations.
  - Refined attribute management within the editor for better performance and reliability.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/647d0586-e868-4320-8951-817107a56fee  **( without using duplicate post )**
Take a look on button with arrow and IB related with it, probably smth was broken from https://github.com/maxi-blocks/maxi-blocks/issues/5155
2) https://jam.dev/c/db83b64b-9ba2-4a3c-b792-6887d7052e3e  **( with using duplicate post )**
Looks like fixed, but need to merge https://github.com/maxi-blocks/maxi-blocks/pull/5368 first with this brunch
But take a look to button from SML-PRO-102 here again, IB does not work correct but in another way

**Comment by Fybex** [comment]
> 1. https://jam.dev/c/647d0586-e868-4320-8951-817107a56fee  **( without using duplicate post )**
>    Take a look on button with arrow and IB related with it, probably smth was broken from [Bug with displaying frontend on different pages #5155](https://github.com/maxi-blocks/maxi-blocks/issues/5155)

Derived into #5386 

> 2. https://jam.dev/c/db83b64b-9ba2-4a3c-b792-6887d7052e3e  **( with using duplicate post )**
>    Looks like fixed, but need to merge [Issue 5360 - Fix styles on block tone change #5368](https://github.com/maxi-blocks/maxi-blocks/pull/5368) first with this brunch
>    But take a look to button from SML-PRO-102 here again, IB does not work correct but in another way

Merged #5368 here, fixed IB on duplicate

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/af0ac34c-695e-4849-8a3b-4e9d8fb2edce
colour for button`s icon bg is not working correct
2) and IB is not fixed for duplicate

**Comment by Fybex** [comment]
> 1. https://jam.dev/c/af0ac34c-695e-4849-8a3b-4e9d8fb2edce
>    colour for button`s icon bg is not working correct
> 2. and IB is not fixed for duplicate

Both going to be fixed in #5386, it's related
Test here only if Yoast Duplicate works please 👍

**Comment by Fybex** [comment]
https://github.com/maxi-blocks/maxi-blocks/assets/46112160/87c33849-1690-436e-8107-bfc5d7ab0a8a

Found and fixed bug with bg layers as well, also check if #4405 is fixed on yoast duplicate as well

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
I'm getting this when I'm cloning, need to initialize ``` $blocks_post``` or add checks for it:

```
[08-Jan-2024 14:10:36 UTC] PHP Warning:  Undefined variable $blocks_post in /home/elzadj/Work/Gutenberg/dev/wp-content/plugins/maxi-blocks/core/class-maxi-styles.php on line 1402
[08-Jan-2024 14:10:36 UTC] PHP Stack trace:
[08-Jan-2024 14:10:36 UTC] PHP   1. {main}() /home/elzadj/Work/Gutenberg/dev/index.php:0
[08-Jan-2024 14:10:36 UTC] PHP   2. require() /home/elzadj/Work/Gutenberg/dev/index.php:17
[08-Jan-2024 14:10:36 UTC] PHP   3. require_once() /home/elzadj/Work/Gutenberg/dev/wp-blog-header.php:19
[08-Jan-2024 14:10:36 UTC] PHP   4. include() /home/elzadj/Work/Gutenberg/dev/wp-includes/template-loader.php:106
[08-Jan-2024 14:10:36 UTC] PHP   5. wp_head() /home/elzadj/Work/Gutenberg/dev/wp-includes/template-canvas.php:17
[08-Jan-2024 14:10:36 UTC] PHP   6. do_action($hook_name = 'wp_head') /home/elzadj/Work/Gutenberg/dev/wp-includes/general-template.php:3052
[08-Jan-2024 14:10:36 UTC] PHP   7. WP_Hook->do_action($args = [0 => '']) /home/elzadj/Work/Gutenberg/dev/wp-includes/plugin.php:517
[08-Jan-2024 14:10:36 UTC] PHP   8. WP_Hook->apply_filters($value = '', $args = [0 => '']) /home/elzadj/Work/Gutenberg/dev/wp-includes/class-wp-hook.php:348
[08-Jan-2024 14:10:36 UTC] PHP   9. wp_enqueue_scripts('') /home/elzadj/Work/Gutenberg/dev/wp-includes/class-wp-hook.php:324
[08-Jan-2024 14:10:36 UTC] PHP  10. do_action($hook_name = 'wp_enqueue_scripts') /home/elzadj/Work/Gutenberg/dev/wp-includes/script-loader.php:2262
[08-Jan-2024 14:10:36 UTC] PHP  11. WP_Hook->do_action($args = [0 => '']) /home/elzadj/Work/Gutenberg/dev/wp-includes/plugin.php:517
[08-Jan-2024 14:10:36 UTC] PHP  12. WP_Hook->apply_filters($value = '', $args = [0 => '']) /home/elzadj/Work/Gutenberg/dev/wp-includes/class-wp-hook.php:348
[08-Jan-2024 14:10:36 UTC] PHP  13. MaxiBlocks_Styles->process_content_frontend('') /home/elzadj/Work/Gutenberg/dev/wp-includes/class-wp-hook.php:324
[08-Jan-2024 14:10:36 UTC] PHP  14. MaxiBlocks_Styles->get_content_meta_fonts_frontend($id = 15147, $content_key = 'maxi-blocks-styles') /home/elzadj/Work/Gutenberg/dev/wp-content/plugins/maxi-blocks/core/class-maxi-styles.php:1041
[08-Jan-2024 14:10:36 UTC] PHP  15. MaxiBlocks_Styles->get_content_for_blocks_frontend($id = 15147, $passed_content = *uninitialized*) /home/elzadj/Work/Gutenberg/dev/wp-content/plugins/maxi-blocks/core/class-maxi-styles.php:1060
```

The IB are not cloning (like for Story Mix Light SML-PRO-106), but as I understand, that's another issue?

**Comment by elzadj** [comment]
I'm going to fix the $blocks_post warning

**Pull request merged**
