### PR TITLE
Issue 3295 - fix image size and crop options

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
In image-maxi imageData was no longer in props, as we got rid of HOC which did that. And in background image ImageCropControl was passed wrong mediaID. Also fixed ImageCropControl as it was acting weird.

Fixes #3295 and #3198 

# How to test?
Check image size is appearing in dimension tab. Check crop control loads in background control. And check if crop control works.

# Test checklist

**_Front/Back Testing_**

-   [x] Check image size is appearing in dimension tab
-   [x] Check crop control loads in background control
-   [x] Test crop control
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload

**_Pre-Code Testing_**

-   [x] Check image size is appearing in dimension tab
-   [x] Check crop control loads in background control
-   [x] Test crop control
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]

**Review by Fybex — CHANGES_REQUESTED** [review]
Custom Image size and Custom Background image size not working

**Review by Fybex — APPROVED** [review]
Nvm about my comments higher, I'm blind

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Good job, glad to see the crop working again 🚀 

There's this glitch that jumps a bit, not a big issue and nothing to be afraid of for the moment, but I share it just to have in mind:


https://user-images.githubusercontent.com/50477222/174055176-94b37746-b96c-4838-b05b-55e91c0f5168.mp4

**Review by Naaaaiix — APPROVED** [review]
Awesome 👏 

Fix conflicts and lets merge it 🥳

**Review by Naaaaiix — APPROVED** [review]

**Pull request merged**
