### PR TITLE
Issue 2926: Accordion Maxi

### PR DESCRIPTION
**Pull request by FitseTLT**
# Description
Accordion Maxi

Fixes #2926 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — CHANGES_REQUESTED** [review]
1. Boxed - Simple layout issues:
https://user-images.githubusercontent.com/19425503/178688927-9904a218-4680-4eff-84a0-9892eb137b5a.mp4

2. "Pane closes when another opens" option doesn't work

**Review by Marko64 — CHANGES_REQUESTED** [review]
Noticed one more thing:
When you change the icon it doesn't reflect the changes until you click on a pane. Can we swap the icon immediately instead?

**Review by Marko64 — APPROVED** [review]

**Review by Fybex — CHANGES_REQUESTED** [review]
Good job 🎉 

A few things:

- is it okay? looking not good...
image
- let's move all controls related with accordion/pane to components folder inside block folder

**Review by Fybex — CHANGES_REQUESTED** [review]

**Review by Fybex — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
The effects used for creating the open/close animations are done using inline styles; I think it would be lighter, easier and cleaner to used CSS animations linked to classNames in both parts: editor and frontend.

**Review by Naaaaiix — COMMENTED** [review]
Found a couple of things:
1. Strange class on frontend:
Captura de Pantalla 2022-08-05 a las 13 42 05

2. There's a non-used `editor.scss` on Accordion and Pane folder
3. Is Pane creating duplicate css?
Captura de Pantalla 2022-08-05 a las 13 48 43

4. Spacing should appear when is more than a pane, if not has any sense. Also, transition in seconds instead of ms:
Captura de Pantalla 2022-08-05 a las 15 35 03

5. Animation is not looking excellent: it shows part of the content when open/close

https://user-images.githubusercontent.com/50477222/183088921-d9dd6c0a-9316-4f59-8f68-2e973a8d21fa.mp4

6. On clicking on the `title` element, the pane actions open/close.
7. Is there any reason to have a Row as a default block? 🤔 
8. Accordion needs, at least, flex-child options if not all flex settings 👍

**Review by Naaaaiix — APPROVED** [review]
Just a small movement of lines; once done can be merged 😸

**Review by Naaaaiix — APPROVED** [review]

**Pull request merged**
