### PR TITLE
Issue 2652 - BlockIndicators enhancement

### PR DESCRIPTION
**Pull request by Naaaaiix**
# Description

This PR aims to fix the issue we've been defining for long time on #2652. The current actions done are:
1. Renamed `Indicators` component for `BlockIndicators` to avoid confusion with the settings indicators.
2. Refactored `BlockIndicators`, reducing the code and enhancing the logics.

Some known issues:
1. ~~Styles are a mess, once merged we can make them fancier~~ 👍 
2. When padding top or margin is 0, is hard to access to the handler on the same space of the Row boundary
3. When scrolling to 0, we can overpass the limit with the handle and then it comes back to the correct position.
4. ~~While scrolling, editor's bottom scrollbar appears.~~
5. In some situations (when value is below 30px), the padding blue line is overlapping the text.

~~I'd like to request, even knowing these issues, to have a first test to see if it works as expected and to share what things we might improve. Thanks~~ 😸 

Fixes #2652 

# How Has This Been Tested?

Create a Container Maxi and test the block indicators. Testing with another Container below to see how they interact will help also 👍 

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the block indicators on a Container Maxi
- [x] Test the block indicators between 2 Container Maxi
- [ ] Test reloading after save and in frontend

**_ Pre-Code Testing _**

-   [x] Test the block indicators on a Container Maxi
- [x] Test the block indicators between 2 Container Maxi
- [x] Test reloading after save and in frontend
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by kyrapieterse — APPROVED** [review]

**Review by ckp267 — APPROVED** [review]
Works great now!!!! @Naaaaiix approved - let's move to styling.

All systems go for BETA!

**Review by elzadj — APPROVED** [review]

**Review by Fybex — APPROVED** [review]
Approving, but wrote about a few minor things.

**Review by Olekrut — CHANGES_REQUESTED** [review]
yes, everything is ok, except thing with Margin-bottom/
maybe should be changing margins for picked Container?

**Review by myroslavve — APPROVED** [review]

**Review by MeltingWings1 — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) appender is overlapping word padding (low priority)
image
2) triggering indicators on click is reducing sometimes only on first click https://jam.dev/c/984afcff-30f5-40b1-8de6-f2ef30ccb2ae
3) if containers have equal margins, impossible to change margin for second container ( low priority) https://jam.dev/c/32f5e0d7-5fb2-4ce8-bb68-3c1e75481bbd
4) https://jam.dev/c/87e7cc38-6407-4ee4-9fc6-02baaec8c352 toolbar is overlapping margin value, maybe need to move toolbar or word - margin:value;/padding:value;?
5) margin indicator is not visible if it set only for one of neighbors containers https://jam.dev/c/5bd67d4f-79b4-4588-b746-74cd99560b6b

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
