### PR TITLE
Issue 4992 - typography responsive bug

### LINKED ISSUE #4992: Typography responsive bug old patterns
### Description

Smith happened with typography.. if to change smth ( colour, size, line-height, etc ) values are inheriting to XXL
have noticed only for PTL-PRO-01, maybe problems with migrator. There are errors in the console

Master

### Step-by-step reproduction instructions

1) Load PTL-PRO-01
2) Try to change smth from typography and take look to other values

### Screenshots, screen recording, code snippet

https://jam.dev/c/d87c7d94-5f81-4849-963c-f5e387918a88

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description

Fixes #4992 

Old PR: https://github.com/maxi-blocks/maxi-blocks/pull/5014

# How Has This Been Tested?
Checked that PTL-PRO-01 looks right after editing it.

# Test checklist

**_Front/Back Testing_**

-   [ ] Check PTL-PRO-01 after editing it.

**_Pre-Code Testing_**

-   [ ] Check PTL-PRO-01 after editing it.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Refactor**
	- Improved attribute handling logic for better performance and maintainability.
	- Streamlined logic for setting attributes with new conditions for enhanced user experience.
	- Updated text formatting functions to provide more consistent and reliable text styling.

- **Tests**
	- Expanded attribute testing to cover new scenarios and ensure robustness.
	- Updated text formatting tests to align with the latest code changes.

- **Bug Fixes**
	- Adjusted test values to reflect correct behavior in end-to-end tests for the "Column Maxi" component. 

- **Documentation**
	- No visible changes to end-user documentation in this release.

### CODE REVIEW

**Comment by Olekrut** [comment]
so in this issue you tried to fix responsive mechanism?
not sure, that is possible, but we have 2 cases:
1) XL is base > set values and units for L, XL and XXL > then change base BP to XXL and check how they inherit after changes
2) XXL is base  > set values and units for L, XL and XXL > then change base BP to XL and check how they inherit after changes

**Comment by myroslavve** [comment]
> so in this issue you tried to fix responsive mechanism? not sure, that is possible, but we have 2 cases:
> 
> 1. XL is base > set values and units for L, XL and XXL > then change base BP to XXL and check how they inherit after changes
> 2. XXL is base  > set values and units for L, XL and XXL > then change base BP to XL and check how they inherit after changes

made XXL behave the same as other breakpoints,
and how it works is (for base `xxl`):
if we saved attribute on `xxl` breakpoint only - it is saved as `general` and this attribute is same on all breakpoints, so when someone with other screen size edits this attribute it changes on all breakpoint, like it would on your screen size.

if we saved attribute on `xxl` and any other breakpoint (`l` for example) - it is saved both as `general` and `xxl`, and this attribute is different on `xxl` and `l`, so when someone edits with `l` as base breakpoint it will edit `l`, but will remain the same on `xxl`, same would happen when editing from original `xxl` base breakpoint. 

Also, since XXL was changed check https://github.com/maxi-blocks/maxi-blocks/issues/4695 and https://github.com/maxi-blocks/maxi-blocks/pull/4821 please.

**Comment by myroslavve** [comment]
Fixed https://jam.dev/c/2d10b57c-9929-45d9-aad0-c34740feed7b,

as for https://jam.dev/c/6adf9b24-8596-4163-94ed-cf34286f6212, could reproduce it for other settings on master as well, so seems not related, also if you change numbers slower it will work right because the bug is happening because gutenberg doesn't have time to save attributes before the next attribute change. Will create a separate issue for this

**Review by Olekrut — CHANGES_REQUESTED** [review]
Load any pattern from library, ( made on XL base )
Change smth on XXL base - > it is changing XL values 
https://jam.dev/c/87e8d352-226c-4fb5-a3bf-ffe25c661134

**Comment by myroslavve** [comment]
> Load any pattern from library, ( made on XL base ) Change smth on XXL base - > it is changing XL values https://jam.dev/c/87e8d352-226c-4fb5-a3bf-ffe25c661134

It is expected for now, will fix patterns in separate issue. Wrote about it earlier:

> And also this only fixes the problem for new blocks, so won't fix https://github.com/maxi-blocks/maxi-blocks/pull/5014#issuecomment-1671673082, will fix patterns in another issue (migrator won't work, so will specifically fix patterns)

**Review by Olekrut — CHANGES_REQUESTED** [review]
I understand that this issue about typography, but need to introduce it for all features
example, opacity does not work correct 
https://jam.dev/c/b5684cfe-d46a-41eb-b8d9-4f56c0fc5249
the same for BG values

**Comment by kyrapieterse** [comment]
Make a new issue @Olekrut otherwise we are stuck in PR ping pong 🏓. Let's count this game won and start a new set with the other settings 🙏

**Comment by Olekrut** [comment]
https://jam.dev/c/f3857a56-5d48-4c70-b604-200f2276b041
looks like this fix is very slowing Maxi due change font-size

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
