### PR TITLE
Issue 3889 - Transform reset fix

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #3889 

# How Has This Been Tested?
Checked if problem from #3889 is fixed, checked if transform-origin isn't broken after small refactor and transform control functionality in general on responsive, hover, etc 

# Test checklist

**_ Front/Back Testing _**

-   [x] Test if reset works as expected on responsive, on general
-   [x] Test if transform origin isn't broken after refactor
-   [x] Test if transform control functionality in general on responsive, hover, etc works as expected

**_ Pre-Code Testing _**

-   [ ] Test if reset works as expected on responsive, on general
-   [ ] Test if transform origin isn't broken after refactor
-   [ ] Test if transform control functionality in general on responsive, hover, etc works as expected
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]

**Review by moroz-art-dev — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
[reset for rotate.webm](https://user-images.githubusercontent.com/88893350/202774163-7dd53914-23cc-42da-b9a8-42eb72de2486.webm)

**Review by Rustam198804 — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
1)

[reset is not working correct ( related with responsive values).webm](https://user-images.githubusercontent.com/88893350/203943418-4c0e9c20-8db7-4a61-a694-af075ec32b63.webm)

2)

[inheariting values after enable and disable hover.webm](https://user-images.githubusercontent.com/88893350/203946341-bb9ea064-d1a0-4a1b-9f87-df3408741c77.webm)

3) need to remove unit (%) from default values ( transform - translate)
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
[inherut values.webm](https://user-images.githubusercontent.com/88893350/205075153-78d36370-2bed-4c5d-9c08-f511712c5d70.webm)

if set values for L first and then set for Base (XL) - Values for L are dropping

**Review by Olekrut — CHANGES_REQUESTED** [review]
[values inheriting not from base breakpoint.webm](https://user-images.githubusercontent.com/88893350/205251830-7585f9cb-051a-4632-a1b2-33beb4ca78c7.webm)

**Review by Naaaaiix — APPROVED** [review]
Lovely refactoring job, apart from the fix. Congrats @Fybex 👏 

PS: still needing @Olekrut approval 👍

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
