### PR TITLE
Issue 5034 - Switch to latest posts for DC and CL if no tags exist on the site and relation is by tag

### LINKED ISSUE #5034: Need automatic swap relation to last posts
### Description

Due creating blogs, I am use relation: by category,
image
 but customer will not have this category,
image
 so when they download our blog pattern, relation should automatically swap to "by date" 
image

### Other plugins or websites examples

_No response_

### How to implement it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description

Fixes #5034 

# How Has This Been Tested?
Inserted [PBGL-PRO-55.txt](https://github.com/maxi-blocks/maxi-blocks/files/12362427/PBGL-PRO-55.txt) on local and checked if it switches to another category. Also changed its relation to by-tag, deleted all tags on my local and checked if it switches to by-date.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Insert [PBGL-PRO-55.txt](https://github.com/maxi-blocks/maxi-blocks/files/12362427/PBGL-PRO-55.txt) on local and check if it switches to another category.
-   [ ] Change relation to by-tag, delete all tags on local and check if it switches to by-date.

**_ Pre-Code Testing _**

-   [ ] Insert [PBGL-PRO-55.txt](https://github.com/maxi-blocks/maxi-blocks/files/12362427/PBGL-PRO-55.txt) on local and check if it switches to another category.
-   [ ] Change relation to by-tag, delete all tags on local and check if it switches to by-date.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### Summary by CodeRabbit

Release Notes:
- Bug Fix: Modified `getDCMedia` function to handle cases where `data` is undefined or null, preventing potential errors.
- Bug Fix: Updated `getDCOptions` function to set new values for `relation` and `order` based on certain conditions.
- Refactor: Made changes to `withMaxiContextLoop` component to import necessary dependencies, add props, and update attributes based on context loop.
- Bug Fix: Modified `get_post` function to handle scenarios where WP_Query returns an empty result and the "dc-relation" attribute is in the list of predefined order relations.
- Bug Fix: Updated `getDCOptions` function to conditionally set new values for `prefix` and `order` properties.
- Refactor: Made changes to `withMaxiContextLoop` component to import dependencies, add props, and update attributes based on context loop.
- Bug Fix: Modified `get_post` function to handle cases where posts are empty and handle specific cases for "by-category" and "by-tag" relations.
- New Feature: Added a new method `get_validated_orderby_attributes()` to the class `class-maxi-dynamic-content.php` to validate and retrieve orderby attributes based on the `dc_relation` value.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
1.1) create a few posts with only new category
1.2) update page with blog pattern from issue
1.3) remove new category
1.4) update frontend for page ( not editor ) , you will see screenshot
1.5) if reupdate editor, everything will be ok, because all posts will have cat "Uncategorized"

and need to fix this one before https://github.com/maxi-blocks/maxi-blocks/issues/5047

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) > Not sure, but I think this is right, for creator it is logical that we fall back to another tag, but user wouldn't expect to see all posts with tag2, if he clicked on a page to see posts with tag1. But if that doesn't make sense, write it here, I will make frontend fall back to another tag as well.

You are discussed it with @elzadj here 
https://github.com/maxi-blocks/maxi-blocks/issues/5034#issuecomment-1682173699
so, is not right...

2) so i should remake, created blog patterns?

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/bd415f0d-bc4c-4da9-978f-0ad51b3514d4
if to remove all tags and refresh editor we get warning for a few sec, is it ok?
take a look to 1:21 on video

and the same warning on frontend
image

**Comment by TeksPeks** [comment]
moved to https://github.com/maxi-blocks/maxi-blocks/pull/5170

**Pull request closed without merging**
