### PR TITLE
Issue 3966 - Bug with hovered shapes on button-block

### PR DESCRIPTION
**Pull request by elzadj**
# Description

We were generating a lot of redundant svg code. And I'm sure we still do.
Check the screenshots and use the editor code from https://github.com/maxi-blocks/maxi-blocks/issues/3966

Fixes #3966

# How Has This Been Tested?

Tested our 3 types of svgs (shape, line, filled) as button icons. Shape doesn't need ```stroke``` styles, line - ```fill``` styles. 

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the Button Icon with hover state in sidebar. As many different svg icons as you can.
-   [x] Test other svg (Icon block, shape, etc.) just in case
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the Button Icon with hover state in sidebar. As many different svg icons as you can.
-   [ ] Test other svg (Icon block, shape, etc.) just in case
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Rustam198804 — APPROVED** [review]

**Review by Marko64 — APPROVED** [review]
Icon colours are not responsive - this is in master too, and I think it's a known case, I forgot, but mentioning it just in case.

**Review by Naaaaiix — COMMENTED** [review]
Good job, works perfect 👍

**Review by Marko64 — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
Perfect ✌️ 😸

**Review by Olekrut — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
Master, so bug with hovered shape on button only when toggle enabled

[shape hover.webm](https://user-images.githubusercontent.com/88893350/204510972-67ab20ed-51b0-43c5-b047-e60ef356667f.webm)

on this brunch: problem with transition 

[button`s transition.webm](https://user-images.githubusercontent.com/88893350/204511284-80a81a0a-d2ab-4271-9ea9-5ee28fe506f0.webm)

**Review by MeltingWings1 — APPROVED** [review]

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
