### PR TITLE
New issue 1676

### PR DESCRIPTION
**Pull request by javadsamiee**

### CODE REVIEW

**Review by elzadj — CHANGES_REQUESTED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
Need to fix the custom color and the fill - image issues mentioned in the prev comment ^

**Review by elzadj — APPROVED** [review]

**Review by Alejandro9kgm — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
Cool work with the preview @javadsamiee  !

I've found a bug: cannot change the image when a Cloud shape is applied. The image changes when I choose any of the default shapes. Also the preview shows the image too - maybe it's connected to the bug? 

Here is a video:

https://user-images.githubusercontent.com/2401618/123386654-91595800-d59f-11eb-894d-03265eaf82e5.mp4



The error is:

```
utils.js:82 Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at generateDataObject (utils.js:82)
    at onSelect (edit.js:193)
    at MediaUpload.onSelect (media-utils.js?ver=616bc0cc8a736b395d853ac5e7de94cd:893)
    at p (backbone.min.js?ver=1.4.0:2)
    at f (backbone.min.js?ver=1.4.0:2)
    at c (backbone.min.js?ver=1.4.0:2)
    at h.Collection.n.trigger (backbone.min.js?ver=1.4.0:2)
    at h.Collection._onModelEvent (backbone.min.js?ver=1.4.0:2)
    at p (backbone.min.js?ver=1.4.0:2)
    at f (backbone.min.js?ver=1.4.0:2)
```

Another bug - this round shape looks weird, some parts of it are just black:

Edit-Page-‹-Local-Wordpress-—-WordPress (13)

**Review by elzadj — APPROVED** [review]
Well done! :+1:

**Review by Naaaaiix — APPROVED** [review]
Good job @javadsamiee 😸

**Review by Naaaaiix — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
