### PR TITLE
Fix sc font

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Fixes fonts not working on frontend when you switch a SC without changing / saving a page. 

How to re-create on master:

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.08.12-16_32_14 (1).webm](https://github.com/user-attachments/assets/c42c13f4-b3c1-4cee-96da-74eea39e3a38)

# How Has This Been Tested?

Test for newly created or imported from the cloud patterns first, change 3-5 SCs without touching the page content. You can create a couple of control pages with new patterns, and change the SC on another page's editor.

Then test old pages that you created on master. This branch has a scheduled event to check DB and convert wrong fonts to sc fonts. Usually takes several minutes to run. You can check if it's finished by search for ```maxi_blocks_sc_fonts_migration_done option``` in the options table, it should have value 1 after it's done.
Check 3-5 different SCs like that.

Check custom fonts working and staying the same, too (new patterns and old from master).

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Implemented a background migration process for handling font styles, enhancing user experience by ensuring seamless updates.
  
- **Bug Fixes**
	- Adjusted the logic in the font retrieval process to correctly handle style avoidance, improving accuracy in font selection.

- **Documentation**
	- Updated relevant documentation to reflect changes in font migration and retrieval processes.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/1fcb1e71-5854-4ac7-8dd7-9dd7823c9633
It is working, not for all SC's ( fonts )
Noticed for Sangria and Gollum

**Comment by myroslavve** [comment]
> https://jam.dev/c/1fcb1e71-5854-4ac7-8dd7-9dd7823c9633 It is working, not for all SC's ( fonts ) Noticed for Sangria and Gollum

For me both Sangria and Gollum are working, and played around with other style cards, those seem to be working as well

**Comment by Olekrut** [comment]
> For me both Sangria and Gollum are working, and played around with other style cards, those seem to be working as well

Idk, As you can see on video, it happens after few SC's. And i ve re-created it a few times, so just try to load more SC's

**Review by Olekrut — APPROVED** [review]

**Comment by elzadj** [comment]
Poly font exists only in 400 (regular), so when we use it for H in SC, it can't be loaded, because 500 and 700 do not exist. I'm sure we have other fonts like this too, but not a lot.

**Review by myroslavve — APPROVED** [review]

**Pull request merged**
