### PR TITLE
Issue 4879 - Video border and box-shadow transition 

### PR DESCRIPTION
**Pull request by Marko64**
Fixed transition for Video Maxi (border and box shadow). Fixed by correcting the hover status prop.

Fixes #4879

# How Has This Been Tested?

**_ Front/Back Testing _**

-   [x] Add a video block and test transition for border and box-shadow.

**_ Pre-Code Testing _**

-   [x] Add a video block and test transition for border and box-shadow.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### Summary by CodeRabbit

**Refactor:**
- Updated class name `videoClass` to `${blockClass}__video-container` for better consistency.
- Modified `hoverProp` values for improved hover effect handling.
- Introduced new functions `getWrapperObject` and `getWrapperHoverObject` for more flexible style generation.
- Adjusted the `getStyles` function to accommodate new wrapper styles.

**Style:**
- Added a `margin: -1px;` property to enhance element styling.
- Set `width` property to 100% in `.popup` class for full-width popups.

> 🎉 "Hoppity hop, code doesn't stop, 🐇
> Refactoring done, isn't it fun? 💻
> Styling's neat, truly a feat, 🌟
> With every PR, we raise the bar!" 🚀

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/5f031b78-a012-4125-a800-e94dfae54d6e
1) is not working on frontend
2) working on backend only for picked video block

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) image
border-width on hover, take a look to white space next to video ( right and bottom )
[border-hover-bug.txt](https://github.com/maxi-blocks/maxi-blocks/files/11948761/border-hover-bug.txt)
2) hover for canvas border is not working at all

**Review by Olekrut — CHANGES_REQUESTED** [review]
point 1 is not fixed//
point 2 is fixed

**Review by Olekrut — APPROVED** [review]

**Review by darimshlk — APPROVED** [review]

**Review by myroslavve — CHANGES_REQUESTED** [review]

**Review by myroslavve — CHANGES_REQUESTED** [review]
Replied in the thread

**Pull request closed without merging**
