### PR TITLE
Issue 5561: woo and custom post types

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Fixes 5561 for Woo and CPT

# How Has This Been Tested?

Same as for posts, but this time 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Refactor**
	- Optimized dynamic content rendering by improving repeated post checks and enhancing attribute handling for products and carts.
	- Updated component structures to include new properties for conditional rendering based on specific conditions.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) some PHP notice, but it disappeared after refresh
image
image
2) https://jam.dev/c/86cd45f0-b676-4d27-a177-258c9266ee37
[3devdemomaxiblockscom.WordPress.2024-05-06.zip](https://github.com/maxi-blocks/maxi-blocks/files/15224270/3devdemomaxiblockscom.WordPress.2024-05-06.zip)
some of the products are repeating, 
3) is previous issue about CL/DC work here ?
image

**Comment by elzadj** [comment]
@Olekrut re-test please, all aside point 3

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) ACF texts are not hidding 
https://jam.dev/c/80054fb0-a472-4f33-b6e0-0d56103465f2

**Comment by elzadj** [comment]
> 1. ACF texts are not hidding
>    https://jam.dev/c/80054fb0-a472-4f33-b6e0-0d56103465f2

Fixing this one.

Hard to hide in case when the post exists, but the ACF doesn't have any content. Pagination continues to work, because, well, the post exists :thinking:

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
