### PR TITLE
issue-483

### PR DESCRIPTION
**Pull request by abder**
This PR aims to fix the issue mentioned in #483 

Note. 
@javadsamiee I just changed hte buttons UI, I didn't  have that white background in the input 
Screenshot from 2020-09-24 14-26-54

### CODE REVIEW

**Review by Naaaaiix — APPROVED** [review]
Good job @DOUARA 👍 

Waiting for @javadsamiee review to merge 🙏 😄

**Review by javadsamiee — COMMENTED** [review]
It's better to have a transition for buttons hover

`transition: all 0.5s ease;`

image

**Review by javadsamiee — APPROVED** [review]
Very good

**Review by Naaaaiix — APPROVED** [review]
Awesome 👍

**Pull request merged**
