### PR TITLE
Style Card Manager UI update

### PR DESCRIPTION
**Pull request by Rustam198804**
# Description

Fixes #3284 

Please execute this in your console.log on the localhost where you test
```wp.data.dispatch('maxiBlocks/style-cards').resetSC()``` to reset the SCs

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the SC Editor - everything you can
- 
**_ Pre-Code Testing _**

-   [ ] Test the SC Editor - everything you can
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ckp267 — APPROVED** [review]
This is ready for Beta! Excellent work everybody @elzadj @Rustam198804 @Marko64 and @ckp267 - Merge this to the moon!

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) order, I guess, more logical to make similar settings near
image
2) 2.1) maybe better if make for SC labels alignment - left? 
2.2) words are touching sides
image
3) to make hover and active state for BP tabs as like everywhere
image
4) icons (overlapping parts) looks weird if change color opacity ( is it expected?) 
[dont think that it is related with this issue]
https://jam.dev/c/fed5c787-232e-43e7-b691-3b8ad1c56aa6
image
5) Maybe have sense to add BG gradient as well?
image
6) SC settings preview for button`s BG colour (hover) are not working correct https://jam.dev/c/866c1315-93c3-409b-afa4-040ffd26fd6d
7) Sometimes SC Tab is disappearing (error in console 
Cant re-produce on purpose. But have seen 2 times
https://jam.dev/c/abda2851-145b-4455-83d9-c5ba20fa6736

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://github.com/maxi-blocks/maxi-blocks/pull/4211#pullrequestreview-1275166593
point 6 is not fixed

**Review by Olekrut — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
Good job team, it has been a tough one. Left some non-relevant comments, so my suggestion is to merge it and create an issue that links to the PR and fixes the possible issues related with what I've left there 👍

**Pull request merged**
