### PR TITLE
Styles with PHP

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Alpha version for checking style bugs, **not for merging**

Now styles are saved per a block, not per a page. 
A php style processor added to serve as a style generator to save styles without opening the editor.

Please randomly check _new_ blocks and patterns with different settings for style bugs and list them here.

**IMPORTANT:** deactivate and activate the plugin after switching to the branch, need it to create new DB tables.

**IMPORTANT:**  Saving a page takes some time (depends on the amount of blocks on the page), please w8 for it to finish before checking the frontend (look on the Update button). This is for tests only, later we will plug that php function to archives, FSE, maxi dashboard, etc. to work without user waiting for it on each page saving.

Known issues:
- FSE is broken
- the new DB table is not cleaned when we remove a block
- reusable blocks are broken 
- there are logs in the console and php, debug log ignore them, this is still work in progress

### Summary by CodeRabbit

Release Notes:

- New Feature: Added new functions for generating position styles, shape divider styles, shape styles, size styles, SVG styles, transform styles, transition styles, typography styles, z-index styles, icon transitions, selectors, alignment text styles, clip path styles, custom formats styles, flex styles, hover effects background styles, icon styles, image shape styles, link styles, margin and padding styles, opacity styles in the MaxiBlocks plugin.
- Bug Fix: Fixed issues related to missing or incorrect styles in various blocks.
- Documentation: Added inline documentation for the newly added functions and classes.
- Refactor: Improved code logic and performance in style helper functions.
- Style: Updated CSS styles for better consistency and readability.
- Test: Added unit tests for the new functions and classes.
- Chore: General code cleanup and organization.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) Search Icon reveal is not working on frontend
2) try to add reusable block to FSE (home) - error
image
3) try to copy/paste nested block (Icon SVG) - error
https://jam.dev/c/cfda3a22-ec7b-46b3-be5a-34bd509559b2
4) IB is not working

**Review by Olekrut — CHANGES_REQUESTED** [review]
1.1) new issue with icon reveal on search block
https://jam.dev/c/f0df60e3-8ac0-439e-8944-11aad324d433
1.2) old search block with icon reveal is not working
https://jam.dev/c/af29c80d-ac12-4ed1-aa1c-a7c0e9f5711e
2) wrong size for accordion's icons on frontend
https://jam.dev/c/7d96d09a-1239-446a-aa6f-8373ff8fa0f1
3) weird labels for blocks
https://jam.dev/c/09fb2750-240b-4681-a20b-1a17c2230f8c
4)  Slider - overlapping
image
5) IB is not working yet

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://github.com/maxi-blocks/maxi-blocks/issues/4990
idk, but fixed in this brunch


1) FSE does not look great
https://jam.dev/c/9e260ae2-aa61-4080-8c7c-0106efcb46fb
image
2) IB is not working on FSE.
IB is working on simple page 👍 
3) new search-block, icon reveal is not working correct
https://jam.dev/c/9473c715-d3fc-46f9-a308-298030897388
4) aspect ratio for video-block is not working
5) error if remove container with IB, Myro has fixed it in another issue, maybe need update this brunch to master?
https://jam.dev/c/3cdd8c56-05ce-4d8a-8cd9-13d7765360fa

**Review by Fybex — CHANGES_REQUESTED** [review]

**Review by Olekrut — APPROVED** [review]

**Review by Marko64 — CHANGES_REQUESTED** [review]
Something with the icon in the button quick styles:
https://github.com/maxi-blocks/maxi-blocks/assets/19425503/67a29ac9-b995-4b38-9dc6-29e8628c31be

When you duplicate a block, the duplicated block's styles affect the original one:
https://github.com/maxi-blocks/maxi-blocks/assets/19425503/de7cca4c-f56c-4c1b-a0c8-55cba47e1888

**Review by Marko64 — APPROVED** [review]
Duplicating and button styles issues fixed.

I can't find anything else.

**Review by Olekrut — APPROVED** [review]
Everything looks OK

**Pull request merged**
