### PR TITLE
Added popover abstraction

### PR DESCRIPTION
**Pull request by MeltingWings1**
# Description

⚠️ To make this branch work need to do `npm ci`, popover dependency was updated. ⚠️ 

Created a popover component from the Wordpress popover component and replaced it in all places.

Fixes #3878 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Naaaaiix — COMMENTED** [review]
Looks good, well done @MeltingWings1 👍 

To end it, would be good to:
1. Check and fix styles: some popovers of the Toolbar doesn't fit with the prev styles.
2. Clean unnecessary code: found some old non-necessary code in files like `src/components/maxi-popover-button/index.js`
3. Needs to work on WP 6.0; to build the environment for it use `WP_ENV_CORE="WordPress/WordPress#6.0" npm run wp-env start`

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
adding space to container after click on it

**Review by Marko64 — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/e709af43-831c-4153-a1e3-891652bb7d84
toolbar don't left next to picked block

**Review by Olekrut — CHANGES_REQUESTED** [review]
[Toolbar doesn't follow to block after move up,down.webm](https://user-images.githubusercontent.com/88893350/209687423-539a438c-4d91-475a-a6e2-413c74b75b5f.webm)

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/0cdf9523-fab9-45a5-8ea8-00ed99d9418d
much better! But toolbar is appearing only after hover in

**Review by Olekrut — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
appear horizontal scroll on responsive, maybe because there are invisible blocks with translate. IS need to add overflow:hidden for all containers? 
[popover.txt](https://github.com/maxi-blocks/maxi-blocks/files/10428025/popover.txt)

**Review by Olekrut — CHANGES_REQUESTED** [review]
Weird behavior with horizontal scroll
https://jam.dev/c/cf3d1d6a-793b-40ea-a630-e7f03247153a

**Review by darimshlk — APPROVED** [review]

**Review by Olekrut — APPROVED** [review]

**Review by Fybex — CHANGES_REQUESTED** [review]

**Review by Fybex — APPROVED** [review]

**Review by elzadj — APPROVED** [review]
Looks ok to me, @Naaaaiix do you want to take a look? It's a really complex one

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Awesome job @TeksPeks, glad to see it done finally! lol
Left some small things to change, but here's a list of some aspects we might review also, but not in this PR. Let's unblock the rest of related issues and leave these points as things to check in future. But I see some things that we might simplify in future:
1. `placement` vs `position`: not sure why we need 2 ways to set the correct position
3. `unstyled`: I think we aren't using this a lot
4. `animation`: are we using it?
5. `arrow`: I think just component uses it, but not sure if we are modifying the arrow from that component, so probably need to check the responsibility is relying on the correct component.

Thanks @TeksPeks! 👏

**Review by Naaaaiix — APPROVED** [review]
🚀

**Pull request merged**
