### PR TITLE
Issue 5017 - Advanced CSS

### LINKED ISSUE #5017: Custom css for inner blocks
### Description

~Any SC change affects both Maxi and Gutenberg blocks, we can't edit SC for them separately. Would be great to have an option to change:
Only Maxi blocks (default)
Both with the same SC settings
Separately with different SC settings (need to think on the UI for that)~

For an example, if we want to change  'bottom-gap' for Gutenberg blocks, we also forced to change it for all Maxi blocks, and then need to change each Maxi block's 'bottom-gap' individually.

Ok, so we concluded with that idea:

a Custom CSS text area, that affects the block and allows you to add inner blocks selectors + css. Should be separated from the current Custom Css we have. Maybe let's name it "Advanced CSS"? 

### Other plugins or websites examples

_No response_

### How to implement it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #5017 

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/2d513dec-b443-44c6-83d6-3ad1a3582918

# How Has This Been Tested?
Checked if the new tab - Advanced CSS works as described in the issue, checked if the custom css tab works as before after the changes.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test Custom CSS tab (some parts of code was abstracted, check if it works as before)
-   [x] Test Advanced CSS tab with different blocks, css
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload

**_ Pre-Code Testing _**

-   [ ] Test Custom CSS tab (some parts of code was abstracted, check if it works as before)
-   [ ] Test Advanced CSS tab with different blocks, css
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

### Summary by CodeRabbit

Release Notes:

- New Feature: Added support for advanced CSS code parsing and customization in various blocks.
- Bug Fix: Fixed CSS control functionality in the custom CSS component.
- Refactor: Improved code structure and modularity in the style helper functions.
- Style: Updated CSS class names and selectors for better UI consistency.
- Test: Added comprehensive test suite for the advanced CSS parsing function.
- Documentation: Added documentation for the new advanced CSS features.
- Chore: Renamed a function and updated its hooking action in the core class file.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) On frontend, have this warning for any page and post, even without Maxi blocks
image
2) Column has 2 Advanced CSS tab
https://jam.dev/c/6d016a95-d482-4979-b06d-bdadda151188

**Review by Olekrut — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
Need Responsive support

**Review by Olekrut — CHANGES_REQUESTED** [review]
Not sure, that is a bug, and we can do smth with it, but classes on VE and VV are different, so some of the styles are not displaying on backend
https://jam.dev/c/1a764436-be3d-404b-881d-35522af00893

**Comment by Olekrut** [comment]
> > Not sure, that is a bug, and we can do smth with it, but classes on VE and VV are different, so some of the styles are not displaying on backend https://jam.dev/c/1a764436-be3d-404b-881d-35522af00893
> 
> We can't do anything with it unfortunately, you should try to use only given by backend classes to accomplish your goals 👍

use only given by FRONTEND, it is more important

**Review by Olekrut — APPROVED** [review]

**Comment by Fybex** [comment]
> > > Not sure, that is a bug, and we can do smth with it, but classes on VE and VV are different, so some of the styles are not displaying on backend https://jam.dev/c/1a764436-be3d-404b-881d-35522af00893
> > 
> > 
> > We can't do anything with it unfortunately, you should try to use only given by backend classes to accomplish your goals 👍
> 
> then use only given by FRONTEND, it is more important

yy, of course, I meant frontend🤦 👍

**Review by elzadj — APPROVED** [review]

**Pull request merged**
