### PR TITLE
Issue 4133 - Border radius unit

### PR DESCRIPTION
**Pull request by Marko64**
The border radius unit in the hover state is now synced with the normals state unit.

Fixes #4133 

# Test checklist

**_ Front/Back Testing _**

-  [ ] Add any block and change the border radius unit, Make sure that the unit changes in the hover state too.
-  [ ] Check that border radius works in general.
- 
**_ Pre-Code Testing _**

-  [ ] Add any block and change the border radius unit, Make sure that the unit changes in the hover state too.
-  [ ] Check that border radius works in general.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/4b967f36-f2a7-434c-80d1-b8a83d13f372
Can't change units on Hover state

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/a51cd1b1-bc85-43ae-a3e6-a5e70cd5ba58
much worse, can't change value and unit anywhere

**Review by Olekrut — CHANGES_REQUESTED** [review]
Is not charm, unfortunately( bug as before https://github.com/maxi-blocks/maxi-blocks/pull/4156#pullrequestreview-1230895150

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/08255125-5100-46d5-a799-0062e12516e0
weird, yes, it is working for me as well now, but have noticed 2 bugs anyway
1) reset button on hover is dropping unit to PX, not to unit on Normal state
2) if we set unit for hover state, changing unit on normal state as well, should be logic as for values

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
This issue hasn't been fixed; check what's commented on #4268 to understand it better 👍

**Review by Olekrut — APPROVED** [review]
fixed in https://github.com/maxi-blocks/maxi-blocks/pull/4281

**Pull request closed without merging**
