### PR TITLE
Fixes bug on editor style responsive mechanism

### PR DESCRIPTION
**Pull request by Naaaaiix**
# Description

This branch aims to fix an issue that makes the editor doesn't look correctly on small devices and breaks the way it looks on editor compared with the frontend. It was looking like:

https://user-images.githubusercontent.com/50477222/218682186-63729177-e7ff-4d62-adba-c47f1a144b29.mp4

Fixes #4356 

# How Has This Been Tested?

Get the code editor from the issue and check the responsiveness on the editor side. Should looks like:

https://user-images.githubusercontent.com/50477222/218682633-7a384035-3a9a-4223-a289-f756a5e52adc.mp4

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the steps commented above
- [ ] Test random patterns and check them changing the size of the screen

**_ Pre-Code Testing _**

-   [ ] Test the steps commented above
- [ ] Test random patterns and check them changing the size of the screen
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/fc0d1ed5-7058-413d-97c5-d72b058486ce
choose M size in Chrome for browser window ( base BP is S)  and try to change maxi BP to M, and you will see

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
the same as previous, but change BP to XS

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/cd32f5fb-321e-4c4b-8f0c-7a306748029e
Compare flex basis for this row on XS, when your base BP = XL and S

**Review by Olekrut — APPROVED** [review]
Yes, agree) main point is fixed)

**Review by darimshlk — APPROVED** [review]

**Review by elzadj — APPROVED** [review]
fingers-crossed-jenny-hagel

**Pull request merged**
