### PR TITLE
Block migrator with transforrm

### PR DESCRIPTION
**Pull request by Naaaaiix**
# Description

This PR is a mix of #3435 and #3443 that has been discussed from [this comment](https://github.com/yeahcan/maxi-blocks/pull/3435#pullrequestreview-1028773281). Basically it contents the migrator for the new targets support on TransformControl and a new methodology for `blockMigrator` that allow a structure capable to unify the different migrators at once. The migrator for Transform has been approved on #3435, so doesn't need many checks; what is most important is the way `blockMigrator` deals with the combination of migrators.

# How Has This Been Tested?

Check [this comment](https://github.com/yeahcan/maxi-blocks/pull/3435#issuecomment-1175997023)

# Test checklist

**_ Front/Back Testing _**

-   [x] Test [this comment](https://github.com/yeahcan/maxi-blocks/pull/3435#issuecomment-1175997023) 

**_ Pre-Code Testing _**

-   [ ] Test [this comment](https://github.com/yeahcan/maxi-blocks/pull/3435#issuecomment-1175997023)
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]

**Review by Fybex — COMMENTED** [review]
Created in master block with previous transform attribute, and it's not migrate. Maybe I don't understand sth, works with old branches where all migrators isEligible, but not in master, where we need only transformMigrator

**Review by Fybex — APPROVED** [review]
Easy and powerful, great migrators maxi basis

**Review by myroslavve — COMMENTED** [review]
Cool!

One little thing: might be better if `getMigratorsCombinations` returns migrators in reverse order as recommended in [gutenberg doc](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/#:~:text=The%20deprecations%20in%20the%20array%20should%20be%20in%20reverse%20chronological%20order.%20This%20allows%20the%20block%20editor%20to%20attempt%20to%20apply%20the%20most%20recent%20and%20likely%20deprecations%20first%2C%20avoiding%20unnecessary%20and%20expensive%20processing.), to apply the most recent and likely deprecations first.

Also `src/extensions/styles/migrators/test/utlils.js` - typo

**Review by myroslavve — APPROVED** [review]

**Review by elzadj — APPROVED** [review]
Just w8 for us to hit version 100 :smile_cat:

**Review by FitseTLT — APPROVED** [review]

**Pull request merged**
