### PR TITLE
Issue 4935 - IB for BG layers

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Fixed:
 - BG styles not generating on IB.
 - BG opacity resetting when set to 0.
 - was unable to change BG height or width on master, fixed that.

https://github.com/maxi-blocks/maxi-blocks/assets/53875005/27841b07-4654-421e-abe6-f7035aa8767c

**Also, I don't think that wrong BG on https://devdemo.maxiblocks.com/pure-image-light-pil-pro-part-1/ -№2 is related to this, background is added without IB there.**

Fixes #4935

# How Has This Been Tested?
Checked that BG styles work on IB. Checked that BG opacity can be set to 0 on IB. Checked that BG height and width can be changed on IB.

# Test checklist

**_Front/Back Testing_**

-   [x] Check that BG styles work on IB.
-   [x] Check that BG opacity can be set to 0 on IB.
-   [x] Checked that BG height and width can be changed on IB.
-   [x] Check that the settings work on frontend.

**_Pre-Code Testing_**

-   [ ] Check that BG styles work on IB.
-   [ ] Check that BG opacity can be set to 0 on IB.
-   [ ] Checked that BG height and width can be changed on IB.
-   [ ] Check that the settings work on frontend.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
bug looks like fixed, but...

Also, I don't think that wrong BG on https://devdemo.maxiblocks.com/pure-image-light-pil-pro-part-1/ -№2 is related to this, background is added without IB there.

I guess related, because we have IB there for BG layer
if copy/paste pattern from devdemo to master, it will not fix this pattern, but it works if download pattern from library
so need a migrator?

**Review by Olekrut — APPROVED** [review]
so, ok, will solve problem by manual

**Review by Fybex — COMMENTED** [review]
Resolve conflicts please @TeksPeks

**Review by Fybex — CHANGES_REQUESTED** [review]
https://github.com/maxi-blocks/maxi-blocks/assets/46112160/332edec1-8bfe-429e-af98-447325f54836



[code editor](https://github.com/maxi-blocks/maxi-blocks/files/11958329/4935.txt)

**Review by Fybex — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
