### PR TITLE
FSE templates + inserter 

### LINKED ISSUE #5497: FSE drops backend styles after closing Block Inserter with patterns
### Description

Site Editor looses all styles if you browse custom pattern in the Block Inserter. Looks like only if you browse the same pattern that is loaded to the template you have opened.

### Step-by-step reproduction instructions

1. Open a FSE template
2. Open Block Inserter - Patterns - All (or My patterns)
3. Load any patterns with maxi blocks
4. Close the inserter.

### Screenshots, screen recording, code snippet

[screencast-mail.google.com-2024.03.13-17_15_58.webm](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/b4f6ed5b-eda4-46c5-8e54-82fd745d2408)

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Fixes the issue, a fatal error when you create a Front Page template on 6.5RC2, optimizes preview image code.

Fixes #5497

# How Has This Been Tested?

Please check that the bug with styles from the issue's video is not present anymore, and that the patterns preview images work ok in FSE and Block inserter.

You also can test by editing a FSE pattern and opening Block Inserter - Patterns - All patterns with the same pattern you are editing right now. Styles must stay ok after you close the inserter.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Enhanced `MaxiBlock` component to support conditional rendering based on preview iframes availability.
	- Improved `MaxiToolbar` with conditional rendering capabilities and robustness checks.
- **Bug Fixes**
	- Fixed an issue in the API handling where `null` values in the `fonts` array could lead to errors.
	- Addressed a minor issue in `MaxiBlock` where a falsy `marginValue` could disrupt styling.
- **Refactor**
	- Optimized pattern preview handling in `MaxiBlockComponent` for better performance and reliability.
	- Removed unused code in `ResponsiveSelector` to streamline control flow.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
Well done

only one question about rendering, backend is rendering only after reload page
https://jam.dev/c/20adbd7b-6044-456a-821b-29a9ed79296e

**Comment by elzadj** [comment]
> Well done
> 
> only one question about rendering, backend is rendering only after reload page https://jam.dev/c/20adbd7b-6044-456a-821b-29a9ed79296e

Please give me the code of the patterns you add

**Comment by elzadj** [comment]
Try now please @Olekrut

**Review by Olekrut — CHANGES_REQUESTED** [review]
Better, the rendering after insertion is correct, but after closing the styles are broken, you have to click on each one for the correct view
https://jam.dev/c/584638ed-b39f-4c04-acec-7ce255f05798

**Comment by elzadj** [comment]
@Olekrut this issue is for re-usable (synced) patterns: https://github.com/maxi-blocks/maxi-blocks/pull/5495
Please check the original issue's video, and what you do in yours. Use not-synced pattern to test, please.
I can't fix reusables until #5495 is merged.

**Comment by elzadj** [comment]
@Olekrut re-test it, please, I've merged changes.

**Comment by Olekrut** [comment]
> Better, the rendering after insertion is correct, but after closing the styles are broken, you have to click on each one for the correct view https://jam.dev/c/584638ed-b39f-4c04-acec-7ce255f05798

 Looks like everything is fine,  except this

**Review by Olekrut — CHANGES_REQUESTED** [review]
wp6.5-rc3 - not fixed
https://jam.dev/c/ddaab642-7c15-458a-a3d7-6f8ad432a6ff
wp6.4.3
https://jam.dev/c/add70f44-7d1c-441f-ab5c-3848065c9086

**Comment by elzadj** [comment]
@Olekrut Can't re-create on both: 

[screencast-mail.google.com-2024.03.20-17_38_48.webm](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/ac5d9c71-55fc-4301-a1cc-1ba3a1906947)


Please do this after switching to that branch: F12, right click on the reload icon near the page addrss -> Empty cache and hard refresh. 

Then try again. If it's still there, please provide me with the patterns code you are using.

**Comment by elzadj** [comment]
The row width is weird sometimes

screenshot-maxithemedev dev600 com-2024 03 20-19_51_57

image (27)

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
