### PR TITLE
Issue 5383: plugin check

### LINKED ISSUE #5383: Plugin check
### Description

Use https://wordpress.org/plugins/plugin-check/ to check our plugin, and fix all you can.
Note: do it after ```npm run build``` and ignore all the dev staff, like warnings from node_modules folder, etc.

### Other plugins or websites examples

_No response_

### How to implement it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Fixes all Errors and majority of warnings from https://wordpress.org/plugins/plugin-check/

Fixes #5383 

# How Has This Been Tested?

Ideally, need to test everything, but I'm going to list the parts of the plugin that were changed the most:

1. Plugin's Dashboard.
2. Fonts, including local fonts.
3. DC date.
4. Woo DC price.
5. Default style card load.
6. Core blocks, so need to test saving, IB, frontend, cloud, etc.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Improved handling of Google Maps API key setup.
  - Enhanced file and folder deletion process using WordPress filesystem functions.

- **Bug Fixes**
  - Fixed issues related to JSON encoding by replacing `json_encode` with `wp_json_encode`.

- **Refactor**
  - Updated URL parsing, date formatting, and content processing functions for consistency and reliability.
  - Restructured significant portions of the codebase for better maintainability and performance.

- **Style**
  - Minor formatting adjustments to ensure proper code indentation and readability.

- **Security**
  - Enhanced output sanitization using `wp_kses_post`.
  - Improved security for database version notice message using `sprintf`.

- **Chores**
  - Removed redundant code and updated methods to best practices for file operations and data handling.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
There are fewer warnings, but they are still there

**Comment by elzadj** [comment]
> There are fewer warnings, but they are still there

Most of them are false positives on WP DB cache, you can google them.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) local fonts are not uploading

**Review by Olekrut — APPROVED** [review]
When i am disabling local fonts, fonts are disappearing from source in inspector ( before removing) Is it correct? 
In general works good
image
image

**Comment by elzadj** [comment]
> When i am disabling local fonts, fonts are disappearing from source in inspector ( before removing) Is it correct?
 
@Olekrut No, they are not disappearing for me until I remove them, could you re-check please? Maybe not in inspector, but in a file manager.

**Comment by Olekrut** [comment]
@elzadj oo, yes, everything is fine if look in file manager

**Pull request merged**
