### PR TITLE
Issue 4909 - Accordion Custom CSS improvements

### PR DESCRIPTION
**Pull request by Marko64**
Fixes #4909 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [x] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by darimshlk — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
hmm... After some thought
Need to add after and before for Content and Icon
And after and before for Pane, Pane header, Pane content, Icon should be in accordion CSS list as well, not only for Pane CSS list
just CSS for pane should have higher priority

**Review by Olekrut — CHANGES_REQUESTED** [review]
1.1) need to add CSS for Pane in Accordion list
1.2) need to add after and before  for pane header content as well

2) https://jam.dev/c/96c982bf-54fd-4cc0-a8c2-d246a14d5fbb
CSS for accordion's after and before is adding to pane as well

3) Cant to add CSS to Pane header
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://github.com/maxi-blocks/maxi-blocks/pull/4911#pullrequestreview-1486238892
point 3 is not fixed

image
image

the same for Pane content and Pane icon


2) Can be solved in this PR UI request?
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/7dc900e3-8230-4e4b-acbc-1122b1ff7415
after is not working correct on backend
2) https://jam.dev/c/5539e3df-4760-41d5-9e24-e017f12d726d
if to add CSS to after pane, it is adding to after accordion as well
3) before pane is not working ( for pane, not accordion )
image

**Review by Olekrut — APPROVED** [review]

**Review by myroslavve — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
