### PR TITLE
Support chat integration

### PR DESCRIPTION
**Pull request by Naaaaiix**
# Description

Implements chat support to beta branch

#3931 

# How Has This Been Tested?

Clicked on:
1. Responsive toolbar `help` button
2. Any block toolbar '?' icon
3. On Modal/Library `help` icon on the top-right corner
4. On Maxi dashboard, support tab

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the commented places above

**_ Pre-Code Testing _**
-   [ ] Test the commented places above
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) Chat is appearing only after second click to icon in toolbar
https://jam.dev/c/6628716d-3a64-42ba-b9e2-547846166f0e
2) Maybe need a simple hover for cc-xkyq cc-qvio?
image
image
3) is need to remove it from help before we add it? or add comment, that it will be added later?
image
4) need a bit of love with it
image

**Review by Marko64 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/19425503/217768051-e5ec7460-29fc-4cff-a425-86bad6e29d5f.mp4

**Review by Olekrut — APPROVED** [review]
Point 1 is fixed) 
points 2-4 are left,  but as I understand, they should not be fixed here

**Review by Marko64 — APPROVED** [review]
Better 👍

**Review by elzadj — APPROVED** [review]

**Pull request merged**
