### PR TITLE
Issue 5100 - hide DC blocks on frontend

### LINKED ISSUE #5100: Dynamic Content (DC) - Hide block on frontend if there is no content
### Description

If we don't have value for some of DC Text block (Image, button, etc.) on frontend it should be invisible

### Step-by-step reproduction instructions

_No response_

### Screenshots, screen recording, code snippet

_No response_

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Added a switch that lets users choose if blocks should be hidden on the frontend when there is no content.
By default it is true.

Fixes #5100

# How Has This Been Tested?
Checked if blocks with no content are hidden on frontend.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check if blocks with no content are hidden on frontend.

**_ Pre-Code Testing _**

-   [ ] Check if blocks with no content are hidden on frontend.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Introduced a new "Hide Content" option for dynamic content when no content is found.
	- Added the ability to select the source for dynamic content via a new control.
	- Implemented a toggle switch to control the visibility of dynamic content.

- **Enhancements**
	- Dynamic content now receives additional classes for better styling control based on content conditions.
	- Improved the user interface for dynamic content components with formatting and localization enhancements.

- **Bug Fixes**
	- Fixed the issue where empty states for dynamic content were not correctly handled.
	- Adjusted logic to ensure proper checks for taxonomy-related conditions.

- **Style**
	- Added CSS class for hiding elements when the "Hide Content" feature is activated.

- **Refactor**
	- Refactored dynamic content handling to improve the detection of empty states.
	- Updated migrators to handle new dynamic content hide property.
	- Streamlined attribute handling in MaxiBlock components for dynamic content status.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
Errors
https://jam.dev/c/8efce622-fac4-4bcf-8940-64574e6ecaae
try to load any blog on this brunch

**Comment by TeksPeks** [comment]
> Errors https://jam.dev/c/8efce622-fac4-4bcf-8940-64574e6ecaae try to load any blog on this brunch

Fixed, made default for hiding false, because errors were about that blocks were changed (hidden) without user action, which actually could make someone's page look wrong when they update page without knowing it has changed

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
does not work good with Images and tags


and can you pls update this brunch to master with Woo, want to check them as well

I guess, it should be enabled by default

**Comment by TeksPeks** [comment]
> does not work good with Images and tags

fixed.

> and can you pls update this brunch to master with Woo, want to check them as well

updated.

> I guess, it should be enabled by default

enabled by default for new blocks, for old still made disabled, for the reason I wrote higher: blocks will look different even though user didn't change them.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) looks like CL does not work correct at this brunch, maybe need to merge with master?
https://jam.dev/c/37e94395-4982-4e67-ae1a-dccb3a9d6223
2) no content are not hiding on frontend
3) is it expected? if use dc tag link, text block is disappearing on backend but not on frontend
https://jam.dev/c/12983356-4fde-468c-91a3-be9065cf2ad9

**Comment by TeksPeks** [comment]
> 1. looks like CL does not work correct at this brunch, maybe need to merge with master?
>    https://jam.dev/c/37e94395-4982-4e67-ae1a-dccb3a9d6223

merged master, although I didn't have this problem.

> 2. no content are not hiding on frontend

fixed.

> 3. is it expected? if use dc tag link, text block is disappearing on backend but not on frontend
>    https://jam.dev/c/12983356-4fde-468c-91a3-be9065cf2ad9

fixed.

**Review by Olekrut — CHANGES_REQUESTED** [review]
Some of DC are not working, check them during fix test pls

Some DC blocks are hidden, even though they are there.
https://jam.dev/c/2f3231de-cd5e-45bc-907f-9e3612a12ca4 - posts
https://jam.dev/c/db80a4f6-44f0-4a1a-b736-7903f2ddb7c8 - products
https://jam.dev/c/c17437c2-015a-464b-b2ea-6de3312d67ff - site
https://jam.dev/c/832761bc-ceeb-465d-b76e-641ef4615971 - page
etc... Guess, you understand...
all DC blocks are here  
[DC all, except tags and cats.txt](https://github.com/maxi-blocks/maxi-blocks/files/13679565/DC.all.except.tags.and.cats.txt)

For Post categories and tags, Product categories and tags get errors ( only this brunch )
https://jam.dev/c/b4dadf0b-e68b-48d2-8d0b-d9ec16ecd0b3
because I am putting them to another file 
[DC tags and cats.txt](https://github.com/maxi-blocks/maxi-blocks/files/13679562/DC.tags.and.cats.txt)

**Comment by TeksPeks** [comment]
> Some of DC are not working, check them during fix test pls
> Some DC blocks are hidden, even though they are there. https://jam.dev/c/2f3231de-cd5e-45bc-907f-9e3612a12ca4 - posts https://jam.dev/c/db80a4f6-44f0-4a1a-b736-7903f2ddb7c8 - products https://jam.dev/c/c17437c2-015a-464b-b2ea-6de3312d67ff - site https://jam.dev/c/832761bc-ceeb-465d-b76e-641ef4615971 - page etc... Guess, you understand... all DC blocks are here [DC all, except tags and cats.txt](https://github.com/maxi-blocks/maxi-blocks/files/13679565/DC.all.except.tags.and.cats.txt)

fixed

> For Post categories and tags, Product categories and tags get errors ( only this brunch ) https://jam.dev/c/b4dadf0b-e68b-48d2-8d0b-d9ec16ecd0b3 because I am putting them to another file [DC tags and cats.txt](https://github.com/maxi-blocks/maxi-blocks/files/13679562/DC.tags.and.cats.txt)

if I paste code editor on master, and select column it breaks for me, also doesn't seem like code that is changed in this branch is related to this error.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) CL for page and frontend for Page DC are not looking correct
image
image

2) warning on frontend for first file
image
3) About Error for second file
There is error yet
frontend after trying to publish.
Frontend:
image
Backend:
image
4) Product test:
Rating and prices are visible = 0, but it does not have value in product
image
5) The same for cart test
image
6) hided even if there are Link and bio for author 
image
7) hided even if there are some of Media  
image

Check pls all of them next time

**Comment by TeksPeks** [comment]
> 1. CL for page and frontend for Page DC are not looking correct
>    image
>    image

can't reproduce, also doesn't seem related, only thing changed in this PR is adding new DC setting, so it shouldn't affect other settings.

> 2. warning on frontend for first file
>    image

see the same on master, also not related to this PR as well.

> 3. About Error for second file
>    There is error yet
>    frontend after trying to publish.
>    Frontend:
>    image
>    Backend:
>    image

I wrote in previous comment that can also reproduce on master so not related.

> 4. Product test:
>    Rating and prices are visible = 0, but it does not have value in product
>    image

for prices and average rating made it hidden, but for review count 0 is normal value so didn't hide it.

> 5. The same for cart test
>    image

fixed, hid everything that doesn't have value

> 6. hided even if there are Link and bio for author
>    image

if you disable hide on frontend option, you can see on frontend that content is not found, so it is not right, but not related to hiding, will fix in another issue.

> 7. hided even if there are some of Media
>    image

same as previous.

for all errors that I wrote that they are not related, will create an issue.

**Review by Olekrut — APPROVED** [review]
Need to fix https://github.com/maxi-blocks/maxi-blocks/issues/5363
but, guess, we can work with it

**Review by elzadj — APPROVED** [review]

**Pull request merged**
