### PR TITLE
Issue 5259: CL

### LINKED ISSUE #5259: Blog, bug with categories
### Description

Some of blogs auto change category in DC after update

### Step-by-step reproduction instructions

1) check PBGL-PRO-03, PBGD-PRO-03

### Screenshots, screen recording, code snippet

image

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

1. Fixes CL not working when you change category, author or tag
2. Adds working CL to Container - needs deep test.

Fixes #5259 

# How Has This Been Tested?

Use this code to test, or create new Container, etc. 

[test-blog.txt](https://github.com/maxi-blocks/maxi-blocks/files/13451719/test-blog.txt)

Also please test imported blogs from Template Cloud.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Introduced a new attribute for context loop handling, enhancing block interactions and relationships.
  - Added conditional rendering for a new UI component to improve user control over block settings.

- **Improvements**
  - Updated the behavior of the `relationOptions` to provide more consistent and expected outcomes.

- **Bug Fixes**
  - Implemented a conditional check to prevent issues during array merging operations, ensuring stability and reliability.

- **Refactor**
  - Streamlined attribute validation processes to improve performance and maintainability.
  - Adjusted data structures to better support block hierarchy and interactions.

- **Chores**
  - Updated global data structures to exclude specific attributes from certain operations, maintaining data integrity.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
In general looks awesome

1) accumulator does not work for Rows if enable CL for container
But the same if put these 3 rows to one column or group, so maybe it is impossible, guess, i asked it from the begin creating this feature
https://jam.dev/c/d87043f5-d68b-479d-ba0f-0267e8e0831a
2) need to move CL to settings instead of Advanced
image

**Comment by elzadj** [comment]
@Olekrut 

I've enabled Accumulator for rows inside container, columns, groups. 

But there is a problem - it does not work for grandchildren. If we have Container - Row 1 (works) - Columns (does not work), Row 2 (works) - Columns (does not work). The same if Column - Rows - Columns - blocks - works for Rows.

A question - should it be automatically turned on for grandchildren? Or do we need some kind of Toggle "Affect children" / Affect grandchildren"?

If I auto-enable it for grandchildren, the code works for both children and grandchildren at the same time, and then in the second Row we skip 1 accumulator at the beginning:

screenshot-wordpress local-2023 11 24-12_47_22 (2)

Not sure how to resolve it.

**Comment by Olekrut** [comment]
I guess, better toggle, children by default

**Comment by elzadj** [comment]
@Olekrut I've added the toggle to Container, Column and Group, please test.

**Review by Olekrut — APPROVED** [review]
Not sure for 100%, but looks like works good, only problem with speed.


https://github.com/maxi-blocks/maxi-blocks/assets/88893350/f9b6e6b2-02f9-443f-923c-de9589fa0bbf

**Pull request merged**
