### PR TITLE
Issue 4786 - Enqueue Roboto on editor when maxi plugin is enabled

### LINKED ISSUE #4786: Font-weight:bold for all settings ( for admin as well )
### Description

_No response_

### Step-by-step reproduction instructions

1) Create new page
2) download Accountant Page APT-01
3) publish and refresh editor
4) download SC Wally and activate it
5) update and refresh editor
6) check font-weight

### Screenshots, screen recording, code snippet

[screencast-wordpress.local-2023.04.27-18_27_14.webm](https://user-images.githubusercontent.com/88893350/234914697-da220a13-92ea-47a5-b379-ba451dd9011e.webm)

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Now roboto with weight 400 is always loaded in block editor when maxi plugin is enabled.

Fixes #4786 

# How Has This Been Tested?
Reproduced steps from issue, and for navigation in SC changed font from roboto both in light and dark SC. Checked that font weight is not bold.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Integrated Google Fonts ('Roboto') into the block editor for improved text styling while editing.
	- Added a custom stylesheet for enhanced typography and readability in the application.

### CODE REVIEW

**Review by elzadj — CHANGES_REQUESTED** [review]
@myroslavve please download roboto files and put them in a folder in the plugin, and enqueue from there. We can't permanently add google font link like that, that's a gdpr issue, and also if a user wants local fonts, we, again, can't load it from google.

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]

**Comment by elzadj** [comment]
And I think the more appropriate path for the font is ```/core/admin/fonts/roboto```

@ckp267 do we need to change something in license / readme for the plugin if we include roboto files there?

**Comment by ckp267** [comment]
> And I think the more appropriate path for the font is `/core/admin/fonts/roboto`
> 
> @ckp267 do we need to change something in license / readme for the plugin if we include roboto files there?

@elzadj I don't about the font path but for the license we are already covered in the license.txt file

---
https://github.com/maxi-blocks/maxi-blocks/blob/master/license.txt

Google Font API https://fonts.googleapis.com/css2?family=Roboto (and others)
Licence https://developers.google.com/fonts/faq#can_i_use_any_font_in_a_commercial_product
Google fonts from https://fonts.gstatic.com (like https://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf)
Google fonts json from https://github.com/jonathantneal/google-fonts-complete

---

**Review by elzadj — APPROVED** [review]
Looks great, tx. We may extend it to the MaxiBlocks Dashboard lately (it was designed with Roboto in mind).
@Olekrut re-test it pls, just in case, thanks.

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
