### PR TITLE
Issue 5079 - DC custom post type and custom taxonomies support

### LINKED ISSUE #5079: DC - Custom Post Types support
### Description

Support for CPT and custom taxonomies needed.
We need to consider manually created CPT (PHP) and other plugins beside ACF.

### Step-by-step reproduction instructions

_No response_

### Screenshots, screen recording, code snippet

_No response_

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description

- Added custom post types and custom taxonomies under a custom types group in DC type selection
image

For them, you can select same options as for posts and tags/categories if they support it.

Fixes #5079 

# How to test?
1. Add custom post types to your site, you can do that with different plugins, I did it with ACF
image

2. For different custom post types, check different supports options, and if the post doesn't support, for example, title should not be in `fields` selection
image
image

3. When editing custom post types, `current` relation should be working for the post type you are editing:
image

# Test checklist

**_Front/Back Testing_**

-   [ ] Test with different supports for custom post types.
-   [ ] Test CL for custom post types.
-   [ ] Check frontend.
-   [ ] Same 1-3 points for custom taxonomies.
-   [ ] For custom post types check if `current` relation option works.

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Enhanced dynamic content handling with the introduction of custom post types and taxonomies.
	- New state management for dynamic content settings, improving user interaction and content customization.
	- Added ACF (Advanced Custom Fields) settings control for more granular content management.
	- Implemented a new Redux store for managing dynamic content configurations.

- **Bug Fixes**
	- Refined logic for determining content links, sources, and post types, ensuring accurate rendering of dynamic content.

- **Refactor**
	- Replaced various select instances with `useSelect` for optimized data fetching.
	- Streamlined the handling of post types and taxonomy options across components.
	- Updated components to utilize memoization and effect hooks for improved performance.

- **Style**
	- Adjusted default properties related to dynamic content sources for consistency.

- **Documentation**
	- Updated internal documentation to reflect changes in dynamic content handling and state management.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
Well done 🥇  Works good in general
Notes:
1) Smth wrong with DC links https://jam.dev/c/93a9723f-f415-4084-afd7-bca39babef31
looks like long rendering, but not sure
2) After 5-10 changes, ( enable links,  changing types, relations, etc ) > everything is freezing

**Comment by myroslavve** [comment]
> Well done 🥇 Works good in general Notes:
> 
> 1. Smth wrong with DC links https://jam.dev/c/93a9723f-f415-4084-afd7-bca39babef31
>    looks like long rendering, but not sure

can't reproduce, maybe you could share code editor on which it happens? it might help

> 2. After 5-10 changes, ( enable links,  changing types, relations, etc ) > everything is freezing

could reproduce this problem with some patterns, fixed. If not fixed for you, please share code editor on which it happens.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) Check errors if use custom taxonomies 
https://jam.dev/c/f7825030-74ba-434c-ada2-6a41bf555719
2) check how looks DC links for CPT elements on backend
image
image

**Comment by myroslavve** [comment]
> 1. Check errors if use custom taxonomies
>    https://jam.dev/c/f7825030-74ba-434c-ada2-6a41bf555719

was trying to reproduce but couldn't, could you share a code editor please?

> 2. check how looks DC links for CPT elements on backend
>    image
>    image

Fixed.

**Review by Olekrut — CHANGES_REQUESTED** [review]
if enable DC link for some element, then change source or target to element without DC link > you cant set link anymore, because you did not disable DC link for previous target
https://jam.dev/c/d2ad3aae-b98c-4301-9a23-5041f2dd2d4b
 
[DC link bug.txt](https://github.com/maxi-blocks/maxi-blocks/files/14447529/DC.link.bug.txt)

**Comment by myroslavve** [comment]
> Check errors if use custom taxonomies
https://jam.dev/c/f7825030-74ba-434c-ada2-6a41bf555719

Also, could you please share the code editor for this, or tell me what field you selected when the block crashed, because I cannot see it on video.

**Review by Olekrut — APPROVED** [review]
Cant re-produce bug with warning anymore

**Comment by elzadj** [comment]
Almost, need to merge it with the latest changes for 'Get current archive' option.

Making custom taxonomies work with it could be a separated issue.

**Comment by myroslavve** [comment]
> Almost, need to merge it with the latest changes for 'Get current archive' option.
> 
> Making custom taxonomies work with it could be a separated issue.

Merged, in this pull request I have changed `current` relation option to be pushed to `relationOptions` in `getRelationOptions` function instead of filtering it, because it was looking weird with filtering. So changed the `current-archive` the same way in this commit https://github.com/maxi-blocks/maxi-blocks/pull/5424/commits/a45be74d69e3c60de14ddabd5c9b7dc0a7945066, please take a look. 
Didn't change anything else, I think adding `current-archive` support for custom taxonomies would be better to do in another issue.

**Comment by elzadj** [comment]
> > Almost, need to merge it with the latest changes for 'Get current archive' option.
> > Making custom taxonomies work with it could be a separated issue.
> 
> Merged, in this pull request I have changed `current` relation option to be pushed to `relationOptions` in `getRelationOptions` function instead of filtering it, because it was looking weird with filtering. So changed the `current-archive` the same way in this commit [a45be74](https://github.com/maxi-blocks/maxi-blocks/commit/a45be74d69e3c60de14ddabd5c9b7dc0a7945066), please take a look. Didn't change anything else, I think adding `current-archive` support for custom taxonomies would be better to do in another issue.

Great, tx @Olekrut please re-test that part

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
