### PR TITLE
Issue-2489 Border reset acts weird

### PR DESCRIPTION
**Pull request by bilouStrike**
Fixes #2489

### CODE REVIEW

**Review by Naaaaiix — COMMENTED** [review]
Didn't finish with the review, as I need to check the helper better. It seems is breaking something of the 'background' styles. Anyway, the rest of the comments can be considered. Good job @bilouStrike 😸

**Review by elzadj — CHANGES_REQUESTED** [review]
The 'None' option does not have the active state:

Edit Page ‹ Local Wordpress — WordPress (18)

Comparing to the master:


Edit Page ‹ Maxi Blocks Testing Site — WordPress (3)

**Review by elzadj — APPROVED** [review]
@bilouStrike I've assigned you another issue with the border (I've noticed it while reviewing this one)  https://github.com/yeahcan/maxi-blocks/issues/2497

**Review by Naaaaiix — COMMENTED** [review]
Cool, commented some lines. About background situation and the test issues:

https://user-images.githubusercontent.com/50477222/150979094-73736081-7da3-4bf7-8823-b8972f65ea1f.mp4

Also, for future issues, please, label the branch like `issue-${numberOfTheIssue}`. In this case would be 'issue-2489'. Thanks 🙏

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
The positioning error I've commented on the last video is still there. Also, all the modified test that contains `.maxi-background-displayer{ top: -2px; left: -2px;}` are broken, so please, follow next steps:

- [ ] 1. Undo all changes on e2e and unit tests, leave as they were before you modifications.
- [ ] 2. Check the changes done on `src/extensions/styles/helpers/getBorderStyles.js` cause are creating this incorrect positioning of `.maxi-background-displayer`.
- [ ] 3. Ensure that tests like `e2e-tests/blocks/divider-maxi/__snapshots__/index.spec.js.snap` or `e2e-tests/blocks/group-maxi/__snapshots__/index.spec.js.snap` don't break; please, don't update the snapshots to make them work: old snapshots were correct 👍 

Onces all these steps done, we'll have a look to the broken tests together. Is important to preserve the integrity of the tests, and ensure we are not modifying them with incorrect code, as it will make them useless.

**Pull request closed without merging**
