### PR TITLE
Issue 3365 - IB on copy/paste, duplicate or download from Library

### PR DESCRIPTION
**Pull request by Naaaaiix**
# Description

@Olekrut was experiencing what @Fybex commented that could happen on [this comment](https://github.com/maxi-blocks/maxi-blocks/issues/3365#issuecomment-1281261912): when pasting content in a page with blocks that have IB settings, if some of the `uniqueID` coincide, the IB works incorrectly. It can happen 2 things:
1. When doing an IB action on the pasted content on frontend, the IB affects an unexpected block that was there before pasting the content.
2. The IB directly removes that relation, so creators lose part of their job.

This situation can happen with at least 3 actions:
1. Cloning blocks
2. Pasting blocks
3. Adding from Library

To understand it better, here's a detailed example of how we can test it:
1. Create a Group Maxi and add a Button Maxi inside.
2. Add some IB settings on Group to affect Button. Check them on frontend.
3. Clone or copy/paste that Group and check what happens on frontend: both Group Maxi are pointing the same Button Maxi.

This example it's a simple one, but on bigger pages with many patterns this issue can even remove some IB interactions. This branch aims to fix it 👍 

To do it, when is initialized and changes it's `uniqueID` as it already exist, it runs a script that compares the current editor entity and the previous one (getting it from the `undo` entity) and from there it updates the new blocks with the new `uniqueID`s. 

Fixes #3365

# How Has This Been Tested?

Reproduce the steps commented above and check the result on frontend. Also, can be tested pasting more than once the same pattern: on frontend the IB relations should be sync with the content 👍 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the steps commented above

**_ Pre-Code Testing _**

-   [ ] Test the steps commented above
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
error after duplicating or copy/paste group with IB

**Review by Olekrut — CHANGES_REQUESTED** [review]
Awesome, but small notice) would be good if it can be fixed
After move duplicated group with IB to another column > IB is disappearing
https://jam.dev/c/30586302-0422-4a6a-bf90-fe6b7a8ed958

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/14e37129-7f94-4d8d-84bc-e124dbf75a68
It is not braking pattern, but now we can have equal labels for blocks, is it ok?

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/e088c538-beca-4fdc-9402-9c5a15e9f2c4
[equal labels.txt](https://github.com/maxi-blocks/maxi-blocks/files/10696220/equal.labels.txt)

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
