### PR TITLE
Issue 4307 - NC text element bugs

### PR DESCRIPTION
**Pull request by Marko64**
1. Moved the text outside the SVG so it isn't affected by SVG viewBox. This fixes the font size issue.
2. Looks like a Roboto issue. Change to Oswald for example, it doesn't have so much space between 1 and 0 and has no space around the numbers. I think this is just a font thing and nothing we can fix.
3. Changed to 999, but do we really need that much?

Fixes #4307 

**_ Front/Back Testing _**

-   [ ] Test that the text works normally with and without the circle enabled.
-   [ ] Test that the text font size is the same with and without the circle enabled.

**_ Pre-Code Testing _**

-   [ ] Test that the text works normally with and without the circle enabled.
-   [ ] Test that the text font size is the same with and without the circle enabled.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/46e8e262-dc2e-46e6-9e24-9bee3c63471d
smth wrong with frontend 
position and colour

**Review by Olekrut — CHANGES_REQUESTED** [review]
I guess, your fix should not influence to NC without circle
https://jam.dev/c/463a499a-c3ba-4e44-9f93-d65886458595


image

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/8a30da72-9530-4266-b943-f654095a7cb0
is needing a migrator for existing patterns?

**Review by Olekrut — APPROVED** [review]

**Review by darimshlk — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Please, organize the migrator the same way it has been done for Button or modify the Button one to look like this one. Don't mind, just keep the structure please 👍

**Pull request merged**
