### PR TITLE
Optimization for Button Block

### PR DESCRIPTION
**Pull request by javadsamiee**

### CODE REVIEW

**Review by Naaaaiix — COMMENTED** [review]
Good job! Some comments, and one thing:
- Alignment: should be centered by default 👍

**Review by elzadj — CHANGES_REQUESTED** [review]
I'm getting 

```
react-dom.min.js:103 TypeError: Cannot read property 'general' of undefined
    at getLastBreakpointValue (webpack-internal:///53:69)
    at edit.render (webpack-internal:///468:140)
```

and 
    
```
Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at BackgroundDisplayer (index.js?dedb:34)
```
    
when I add a Container + Row (seems like the bugs are in the Row Block)

**Review by Naaaaiix — APPROVED** [review]
Cool, good job! There are some minor bugs to fix, but not a big deal. Didn't check Row Maxi as I understand you're working on it 👍

**Review by elzadj — CHANGES_REQUESTED** [review]
Much better, need to fix a couple of things:

1. Normal Row should be 1170px / 1790px by default. Refer to #745

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Cool, good job @javadsamiee ! 🥳 

What I'm not sure is if what @elzadj implemented on #766 is reflected there. Let's have a look and be sure before merging it please 🙏

**Review by elzadj — CHANGES_REQUESTED** [review]
Is it just me?

**Review by elzadj — CHANGES_REQUESTED** [review]
Bugs

**Review by elzadj — CHANGES_REQUESTED** [review]
Much better!

**Review by elzadj — CHANGES_REQUESTED** [review]
Much better!

**Review by elzadj — CHANGES_REQUESTED** [review]
Much better!

**Review by Naaaaiix — APPROVED** [review]
Didn't find any huge bug, so for me when fixing this little and minor bugs, can be merged 👍

**Review by Naaaaiix — APPROVED** [review]
Good improvements! 👍

**Review by elzadj — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
This looks weird

**Pull request merged**
