### PR TITLE
Issue 3106 - Transitions

### PR DESCRIPTION
**Pull request by Fybex**
# Description

New transitions realization. 

Now we can set to every property (which has hover) separate transition settings.
image

P.S. SVG's haven't transition support for a moment

Fixes #3106 

# How Has This Been Tested?
Checked all blocks transition correct work.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test transitions for all blocks
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)

**_ Pre-Code Testing _**

-   [x] Test transitions for all blocks
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — CHANGES_REQUESTED** [review]
Got it!

I've only found two issues:

Column border and Row border seem to not working. Everything else is great.

**Review by Marko64 — APPROVED** [review]

**Review by myroslavve — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
> `all 0.3s 0s ease;` added by default for .maxi-background-displayer divs, for button-maxi content and maybe a few places more. In other places by default we add `border 0.3s 0s ease, box-shadow 0.3s 0s ease`, so it works as expected +1

Understood, but I think we should not add these styles if the block does not have any border hover or box-shadow hover, etc. And we also should not add them in the dropdown too. Because we are kinda adding a transition to something that does not really exists. What do you think @TeksPeks @Naaaaiix ?

- Border transition on container doesn't work (it works on a Text Block tho):

https://user-images.githubusercontent.com/2401618/171149927-bab92e2a-0f09-416c-87c2-8e6b3754ff4e.mp4

**Review by Naaaaiix — COMMENTED** [review]
Cool, good job; big improvement 👍 

1. Border transition should affect also BackgroundDisplayer (I think is related with the error @elzadj commented); it makes it look strange:


https://user-images.githubusercontent.com/50477222/171274677-3d83489d-96a6-4aed-91d9-a9b79a3e9f3c.mp4



3. Please, move `src/extensions/styles/setTransitionToSelectors.js` and `src/extensions/styles/transitionAttributesCreator.js` to transitions folder 👍

**Review by Naaaaiix — COMMENTED** [review]
Good one, mostly done! 💪 

I still miss a toggle here to allow enabling/disabling easily the transition:
Captura de pantalla 2022-06-01 a las 10 39 03

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Ensure we keep the transition helper test updated also 👍 😸

**Review by Naaaaiix — COMMENTED** [review]
Please, add the unit test we commented on chat. Almost done, good job 👍

**Review by Naaaaiix — APPROVED** [review]
Awesome 🥳

**Pull request merged**
