### PR TITLE
Issue 5242 lists on wp 6.4.1

### LINKED ISSUE #5242: Shift + Enter for lists on Text Block on WP 6.4
### Description

Creating new list element on WP 6.4 has bugs. 

### Step-by-step reproduction instructions

Create List, put the cursor at the end of it, hit Shift+Enter

### Screenshots, screen recording, code snippet

_No response_

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

- Fixes slow editing of lists in Text Block on WP 6.4
- Fixes Enter for Lists in Text Block on WP 6.4. Please use **Enter** to create new li elements, as usual. As a fix for new elements at the end of the list it now adds "New list element" text.

Fixes #5242 

# How Has This Been Tested?

Test everything with lists and Text block in general, please. Old patterns, new lists, patterns from Cloud, etc.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Enhanced text editor with new keyboard shortcuts for list items.
  - Improved list editing and creation with version-specific behaviors.

- **Enhancements**
  - Updated toolbar components to support WordPress version-specific features.
  - Refined text conversion functions to maintain content fidelity across versions.

- **Bug Fixes**
  - Fixed issues with list item handling in rich text based on WordPress version checks.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
6.4
https://jam.dev/c/2afa5b6a-f047-40db-95e8-19dd5e391262
6.4.1
https://jam.dev/c/5338ac10-274c-46b8-8c8f-694b2a160c0c

list does not work correct in any case
enter, shift+enter, in the middle, and in the end

**Comment by elzadj** [comment]
@Olekrut Could you pls give me the lists code, or show, how you create them?

6.4.1:

[screencast-wordpress.local-2023.11.15-12_24_53.webm](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/b41fea56-a87e-4f54-856c-e45c8c1c2e77)

[screencast-wordpress.local-2023.11.15-12_26_50.webm](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/bc1da31e-710f-435d-b518-7b66f31c78bd)

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/d8409104-96a1-48e3-8012-439dc23afab6

[list bugs.txt](https://github.com/maxi-blocks/maxi-blocks/files/13365317/list.bugs.txt)

1) click Enter in the end of list> highlight text - new list item - type smth instead of it
2) ) click Enter in the middle of list > type smth
3) click shift enter in the End of list > list is dropping to simple text

**Comment by elzadj** [comment]
Updated everything, I don't think lists created or changed on the previous iteration of that branch are going to work, so use new, imported from Cloud, or saved first on the master for tests. And ignore shift+enter for now.

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/6918c00a-371c-4eb0-9508-2ac76a780882

check all points from previous comment
i ve not used Ctrl+Enter, only enter
and in some moment got error

https://jam.dev/c/c8616d5f-baad-4d1a-8348-3f00018b985d

**Pull request closed without merging**
