### PR TITLE
WordPress 6.6 fixes

### LINKED ISSUE #5608: WordPress 6.6
### Description

Maxi crashes on WP 6.6 beta 2

```
resolvers.js:4 Uncaught 
TypeError: Cannot read properties of undefined (reading 'mark')
    at ./src/extensions/store/resolvers.js (resolvers.js:4:22)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/extensions/store/index.js (controls.js:37:24)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/extensions/index.js (isInSiteEditorPreviewIframe.js:8:43)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/index.js (index.js:18:28)
    at __webpack_require__ (bootstrap:19:1)
    at startup:4:92
    at __webpack_require__.O (chunk loaded:25:1)
edit-post.js?ver=87f…7a7280f58a3cba:3273 Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client"

```

https://make.wordpress.org/core/6-6/

18 June 2024	Beta 3. 
25 June 2024	Release candidate 1.
2 July 2024	Release candidate 2. 
9 July 2024	Release candidate 3.
15 July 2024	Dry run for release of WordPress 6.6 and 24-hour code freeze.
16 July 2024	WordPress 6.6 is released.

### Step-by-step reproduction instructions

1. Update to wp 6.6 beta 2
2. Open the editor
3. Check the console, also the blocks are broken

### Screenshots, screen recording, code snippet

_No response_

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Please specifically test the problems listed in the issue, but also deep test everything else.

Note: please compare any bug you find with the master on 6.5.5, and create a new issue if it's present there too. This PR is about 6.6 fixes only.

Note 2: please ignore any ```Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".``` in the console if you see them.

Fixes #5608

# How Has This Been Tested?

1. Update to WP 6.6 with the beta tester plugin
2. Remove node_modules folder from your plugin's folder.
3. ```npm i --force``` - wait for it to finish.
4. ```npm start```

Test on WP 6.6 RC1 (or nighty one) and then make sure that WP 6.5.5 is ok too.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Bug Fixes**
  - Fixed double scrollbar issue in WordPress 6.6 within the editor.

- **New Features**
  - Enhanced query selectors for better editor component targeting.
  - Improved handling of custom taxonomies and post types.

- **Style**
  - Updated CSS for various editor components to ensure consistent styling and better visual editor handling.

- **Chores**
  - Updated dependencies to latest versions.
  - Refined Babel and Webpack configurations.

These changes enhance the overall editor experience with improved functionality, visual consistency, and up-to-date dependencies.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
- [x] 1) UI: missed space between Icon and block name - site and branch

image

- [x] 2) UI: horizontal scroll in sidebar - site and branch

image
Guess, some sidebar bugs related with it 
image
image

~~3) BG layer clip-path error - site and branch~~

~~https://jam.dev/c/b5110fae-f35e-4e81-ba90-634275127fc9~~

~~- [ ] 4) Footer 32 if to add caption to image. It gets height 0~~

~~https://jam.dev/c/af3c5400-a164-4249-a5d3-6ee1a8f814e4~~

- [x] 5) UI: Check icon is gone - site and branch

image

- [ ] 6) Looks like some of between appenders have wrong position and size

https://jam.dev/c/cf628dc7-298c-4c4f-9afa-c8a88dd5fe63

image
image

- [ ] 7) some of the fonts are not rendering correct on frontend ( IMPORTANT ) 

https://jam.dev/c/f3b639fb-69f9-4373-b315-b2941c0ef3ea

~~- 8) I don't see names of templates ( FSE )~~

~~image~~

- [x] 9) If to add some block to column or group or row to container, appender is moving to left top corner of template ( FSE )

https://jam.dev/c/2f706de2-3257-41ab-bc5a-4c6e2baf43f0
image



Looks like it is only tip of the iceberg, but branch on local works better
https://jam.dev/c/83877f8d-1535-4730-986c-d3edb0a27d0e

**Comment by elzadj** [comment]
> 8) I don't see names of templates ( FSE )

this was added in the theme, not plugin. We don't control other theme's templates or custom templates in other themes.

**Comment by elzadj** [comment]
6, 7 - can't recreate.

**Review by Olekrut — CHANGES_REQUESTED** [review]
- [x] 1) 1px space line between main toolbar and top WP component

image

- [x] 2) What is about Map markers?

image

- [x] 3) about №6 about previous list of bugs

https://jam.dev/c/7bcacab5-2615-4a61-8f89-df5d33fbc7b8
https://maxithemedev.dev600.com/index.php/test-6-6-2-2/

- [x] 4) most of them are fixed but some of them are invisible yet, for volumn on author template from video

https://jam.dev/c/0bb15a8a-246c-4dab-9641-759b3b065880

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
