### PR TITLE
Issue 5153 - DC. Fix categories and tags displaying on frontend

### LINKED ISSUE #5153: DC Categories and tags are not displaying on frontend
### Description

DC Cats and tags are not displaying on frontend

### Step-by-step reproduction instructions

1) Creat DC tags and cats
2) check frontend

### Screenshots, screen recording, code snippet

https://jam.dev/c/c81e8376-b90f-4402-a7f0-8d0d1c2e8929

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #5153 
# How Has This Been Tested?
Checked if categories and tags are displaying correct on frontend

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test if categories and tags are displaying correct on frontend

**_ Pre-Code Testing _**

-   [ ] Test if categories and tags are displaying correct on frontend
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors

### Summary by CodeRabbit

"Bug Fix and Refactor"

- Bug Fix: Updated the `get_post_or_page_content` function to return an empty string when the `$dc_field` is not set or it's not 'categories' or 'tags', ensuring accurate content retrieval.
- Bug Fix: Enhanced the `get_post` function to return `null` if the query result is empty, preventing potential errors with non-existent posts.
- Refactor: Optimized the `render_dc_image` function by introducing a new variable for storing image source data and adjusting the assignment of media caption. This improves code readability and efficiency.
- Refactor: Improved the `get_post_or_page_content` function by modifying the condition for returning an empty string and updating the assignment of `$post_data`, enhancing code robustness and maintainability.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
Is warning relate to this brunch?
image

[warn blog.txt](https://github.com/maxi-blocks/maxi-blocks/files/12702703/warn.blog.txt)

**Comment by Fybex** [comment]
> Is warning relate to this brunch? image
> 
> [warn blog.txt](https://github.com/maxi-blocks/maxi-blocks/files/12702703/warn.blog.txt)

Yes, that's right, thanks for the remark 👍.

**Review by Olekrut — CHANGES_REQUESTED** [review]
warn is not fixed for me yet
image

**Comment by Fybex** [comment]
> warn is not fixed for me yet image

Hm...I wasn't able to reproduce it on my branch, but I hope I've fixed it. The problem was in PHP DC image part, so I'm not sure if it was related exactly to this branch 🤔 So, check it again please @Olekrut, should be fixed 👍

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
