### PR TITLE
Pagination hidden content fix

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Fixes several issues with CL and pagination.

1. Fixes broken icon making content hidden for footers 103, 104, 105 + theme footer. 
2. Allows to use empty groups / columns (without DC blocks inside) for bg.
3. Fixes pagination bugs with blog patterns 12 and 24 (need to enable DC for all blocks).

# How Has This Been Tested?

Test pagination and block patterns in general. 
Test patterns with the listed footers. 
[Pure Footer Light PFL-PRO-105-broken-location-icon.txt](https://github.com/maxi-blocks/maxi-blocks/files/15390196/Pure.Footer.Light.PFL-PRO-105-broken-location-icon.txt)

Test patterns with empty content for special bg.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Enhanced dynamic block rendering to support additional parameters and improved content visibility management.

- **Bug Fixes**
  - Improved handling of inner blocks to ensure accurate rendering and visibility based on attributes.

- **Performance Improvements**
  - Optimized recursive checks for inner blocks, leading to more efficient content rendering.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
point 3
№12
image
author
№24
image

**Comment by elzadj** [comment]
> point 3
@Olekrut 
I've noticed that both "Posted by" and the divider don't have DC enabled from the cloud, could it be the reason? If not, please provide code for both, or a screenshot of the CL settings for both.

screenshot-wordpress local-2024 05 22-11_22_55
screenshot-wordpress local-2024 05 22-11_20_11

**Review by Olekrut — CHANGES_REQUESTED** [review]
[blog 12 and 24.txt](https://github.com/maxi-blocks/maxi-blocks/files/15401509/blog.12.and.24.txt)

**Review by Olekrut — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
empty column is not hidden
previous bugs are fixed

**Review by Olekrut — CHANGES_REQUESTED** [review]
Hidden for blogs are not working correct after changing cat in CL
https://jam.dev/c/bf0af755-3364-4f8e-be86-af8ce0c197df

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
