### PR TITLE
Issue 4811 - DC for background image

### LINKED ISSUE #4811: Need Dynamic Content (DC) background image
### Description

image

I guess, should be implemented for all blocks ( column and group = 100% )

### Other plugins or websites examples

_No response_

### How to implement it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description

Added DC for background image, works just like normal DC, you can add it in background image layer in Background / Layer tab:
image

The "hide if no content found on frontend" is enabled by default and you cannot change it for background DC.

Fixes #4811 

# How Has This Been Tested?
Checked that DC for background works on editor and on frontend with different background settings.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check that background DC works
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Enhanced background layers support with hover states in the MaxiBlocks.

- **Improvements**
  - Improved dynamic content rendering to handle background layers and hover states more effectively.
  - Updated image layer settings to support dynamic content changes for background images.

- **Refactor**
  - Streamlined rendering logic to conditionally manage background images and dynamic content updates.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) guess, should work with it as well
image
2) it is not rendering at this moment if change cat, only after disable/enable dc
https://jam.dev/c/b80caad7-8c32-4244-a3ae-b7f057187e54
3) Frontend is not working correct, not only for BG image
https://jam.dev/c/c9f4286a-c178-46e3-9e36-6b32f36dc81b

**Comment by myroslavve** [comment]
> 1. guess, should work with it as well
>    image

Was going to do it here, but it turns out to be quite complicated to do, so I suggest it be done in a separate issue.

> 2. it is not rendering at this moment if change cat, only after disable/enable dc
>    https://jam.dev/c/b80caad7-8c32-4244-a3ae-b7f057187e54

Fixed.

> 3. Frontend is not working correct, not only for BG image
>    https://jam.dev/c/c9f4286a-c178-46e3-9e36-6b32f36dc81b

Fixed.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) guess, looks ok now) 
one note: BG Size : custom does not work with dc, need to disallow or fix it
https://jam.dev/c/ade3fa0c-b974-4e08-a3a5-1bcc6030fff8
2) idk, related or no, but in some if tries i ve noticed these warnings
image

**Comment by myroslavve** [comment]
> 1. guess, looks ok now)
>    one note: BG Size : custom does not work with dc, need to disallow or fix it
>    https://jam.dev/c/ade3fa0c-b974-4e08-a3a5-1bcc6030fff8

Disabled it, if we ever need it we can create an issue.

> 2. idk, related or no, but in some if tries i ve noticed these warnings
>    image

couldn't reproduce these warnings, I'm not sure if they are coming from maxi even judging by the names of the files on your screenshot.

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
