### PR TITLE
Issue 5410 - Fix link change in lists

### LINKED ISSUE #5410: Impossible to make or change link for text in list
### Description

Impossible to make or change link for text in list

### Step-by-step reproduction instructions

1)
1.1) create Text list (few lines)
1.2) try to make a link for one of the lines
2)
2.1) load some footer from library with list
2.2) try to change link

### Screenshots, screen recording, code snippet

https://jam.dev/c/cbc834bc-497a-46e1-a771-aaf6f30402ee

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #5410 

# How Has This Been Tested?
Checked if it's again possible to add link in list, checked if lists speed doesn't become much worse

# Test checklist

**_ Front/Back Testing _**

-   [x] Test if it's possible to add link in list
-   [x] Test if lists speed doesn't become much worse

**_ Pre-Code Testing _**

-   [ ] Test if it's possible to add link in list
-   [ ] Test if lists speed doesn't become much worse
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

## Summary by CodeRabbit

- **Refactor**
	- Improved the handling of content changes in the MaxiBlockComponent to enhance performance and reliability.
	- Updated the logic for rich text changes to ensure more accurate formatting under specific conditions.
	- Restructured conditional blocks for better code organization and readability.
	- Adjusted the declaration and usage of specific functions within conditional blocks.

- **New Features**
	- Added functionality for migrating list items in HTML content to include line breaks between them.
	- Introduced new migrators for button styles and list items.

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/d57752c5-5c9c-4547-a8b9-9b0302c82063
removing link is breaking list

**Comment by elzadj** [comment]
As for the breaking tests - try to do ```npm install caniuse-lite --legacy-peer-deps``` and ```npx update-browserslist-db@latest```

**Comment by Fybex** [comment]
> https://jam.dev/c/d57752c5-5c9c-4547-a8b9-9b0302c82063 removing link is breaking list

Quite strange, I can't reproduce, can you retry and share code editor if issue remains 

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/d51ee496-61c5-4d72-8c28-7f3fefe49c35

**Comment by Olekrut** [comment]
@Fybex Everything is ok for new lists
try to load some footer with list and try it there

**Comment by Fybex** [comment]
> @Fybex Everything is ok for new lists try to load some footer with list and try it there

Added a migrator, thanks @Olekrut

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
