### PR TITLE
Lazy load and Suspense for blocks and inspectors

### PR DESCRIPTION
**Pull request by Naaaaiix**
# Description

This implementation doesn't improve the speed of Maxi, just generates the effect that everything is loading faster. It's an experiment and haven't tested to its last setting, but shouldn't give many problems. 

What to expect:

https://user-images.githubusercontent.com/50477222/221806099-a25dc958-78fe-40bb-98a8-fa1e4e0362f3.mp4

instead of:

https://user-images.githubusercontent.com/50477222/221806978-49700030-5f60-4f62-a120-ec2db6bd2d30.mp4

# How Has This Been Tested?

Tested creating new patterns and blocks, downloading from the Library and reloading a saved post. 

Please, share your thoughts and suggestions, this is just a prototype 🙏 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the commented above and whatever it comes to your head lol

**_ Pre-Code Testing _**

-   [ ] Test the commented above and whatever it comes to your head lol
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by kyrapieterse — APPROVED** [review]
Awesome

**Review by Olekrut — COMMENTED** [review]
actually it is good if I want to change smth in the top of page
but if I want to change smth in the bottom of page I should wait 47sec instead of 20sec
[test page.txt](https://github.com/maxi-blocks/maxi-blocks/files/10850362/test.page.txt)

**Review by Olekrut — APPROVED** [review]
Much much better) Bomb) 
except
https://github.com/maxi-blocks/maxi-blocks/pull/4443#issuecomment-1448140733
but anyway, I don't like it) Cant explain) It's like playing on an 8-bit console after the computer
If users like it, then okay.

as for me, better to add some interesting loader, maybe interactive) peoples like interactive

**Review by ckp267 — APPROVED** [review]
This is just DA BOMB. I approve it.

**Review by darimshlk — APPROVED** [review]

**Review by Marko64 — APPROVED** [review]
It does feel a bit better like this.

**Review by elzadj — APPROVED** [review]

**Pull request merged**
