### PR TITLE
Issue 4966 - disable links in higher blocks when tags/cats links enabled

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
The problem in the issue was that in pattern text had tags links enabled, and links on higher blocks weren't disabled.
Now links in higher blocks should be disabled when text has tags/categories links

Fixes #4966 

# How Has This Been Tested?
Checked that when tags/categories links are enabled in DC, links on containing blocks are disabled.

# Test checklist

**_Front/Back Testing_**

-   [x] Check that when tags/categories links are enabled in DC, links on containing blocks are disabled.
-   [x] Add links to the group blocks in [PBGL-PRO-02.txt](https://github.com/maxi-blocks/maxi-blocks/files/11904616/PBGL-PRO-02.txt) on master, check that on preview on this branch they are disabled.

**_Pre-Code Testing_**

-   [x] Check that when tags/categories links are enabled in DC, links on containing blocks are disabled.
-   [x] Add links to the group blocks in [PBGL-PRO-02.txt](https://github.com/maxi-blocks/maxi-blocks/files/11904616/PBGL-PRO-02.txt) on master, check that on preview on this branch they are disabled.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
but it is not right, I want DC link for main group or column and DC link for tags, cats, authors inside this group

**Review by Olekrut — APPROVED** [review]
Cool) not sure, but i guess, for nubby users will not be easy to understand it by first time ( that for DC links need to enable it for all equal by level blocks)

**Review by Fybex — CHANGES_REQUESTED** [review]
Invalid categories link(empty href)

To reproduce:
1. Create group-maxi
2. Add link to group-maxi
3. Then create DC text-maxi inside
4. And turn on category link
5. As a result, we have empty href for category link on frontend

[code editor](https://github.com/maxi-blocks/maxi-blocks/files/12038206/links_4966.txt)

image

**Review by Fybex — CHANGES_REQUESTED** [review]
Previous problem was fixed, but here one more: link toolbar setting is disabled even after text-maxi DC link block deletion

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/5dacc7ef-47ad-4bd3-b0c5-ee7382e7a67f

**Review by Fybex — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
