### PR TITLE
Issue 5407 - author, tags, categories DC links rework

### LINKED ISSUE #5407: Button. Author's DC link
### Description

1) Displaying is wrong on backend
2) we don't have settings for links ( colours, and impossible to remove underline) on frontend
3) DC link works only on button's text ( link doesn`t work on icon and button area )

### Step-by-step reproduction instructions

1) create button
2) set Author
3) Enable Author's DC link

### Screenshots, screen recording, code snippet

1) image
2) image

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description

- Fixed the original issue
- Moved *enable author/categories/tags links* to link settings link target dropdown
image

Fixes #5407 

# How Has This Been Tested?
Checked that author, tags, categories (for products as well) links work. Checked that migrator works, using blog patterns and this [code editor](https://github.com/maxi-blocks/maxi-blocks/files/14394242/editor.txt)

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test author, tags, categories (for products as well) links.
-   [ ] Check migrator with this [code editor](https://github.com/maxi-blocks/maxi-blocks/files/14394242/editor.txt) or blog patterns.
-   [ ] Check that the settings work on frontend

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Introduced configuration settings for rendering inline dynamic content (DC) links with customizable targets.
	- Enhanced logic for dynamic content link rendering, supporting different link targets.
	- Added new attributes `dc-link-status` and `dc-link-target` for improved link handling in dynamic content.
- **Refactor**
	- Streamlined link handling across various components, removing unnecessary state variables and imports.
	- Updated components and utilities to support new link target functionality.
	- Renamed and restructured constants related to link options for clarity and consistency.
- **Bug Fixes**
	- Fixed handling of null or undefined objects in the MaxiToolbar component to prevent errors.
- **Style**
	- Adjusted dynamic content and link styles to accommodate new link attributes.
- **Documentation**
	- Updated internal documentation to reflect changes in link handling and dynamic content rendering.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) need to add ability use DC cat and tags with button block
image
2) if use dc link on button block, there is displaying link is empty on backend, frontend is ok 
https://jam.dev/c/36fb9616-9e0b-4d0c-83a2-83c63f956b81
image
3) we dont have link colours on button block, if use link for it

**Comment by myroslavve** [comment]
> 1. need to add ability use DC cat and tags with button block
>    image

Seems to me like it should be in a separate issue, so created one - https://github.com/maxi-blocks/maxi-blocks/issues/5463

> 2. if use dc link on button block, there is displaying link is empty on backend, frontend is ok
>    https://jam.dev/c/36fb9616-9e0b-4d0c-83a2-83c63f956b81
>    image

can't reproduce, would be good if you could share a pattern it happens on.

> 3. we dont have link colours on button block, if use link for it

This seems unnecessary since the problem with underline was solved, and for buttons with link we can style them with the same settings used for regular buttons.

**Review by Olekrut — CHANGES_REQUESTED** [review]
Button-block, link should be adding to canvas area (wrapper) otherwise link will not work on designs where we are using BG Layers
https://jam.dev/c/2de04a6a-fe96-4f9e-b87f-9528d616a24d

**Comment by myroslavve** [comment]
> Button-block, link should be adding to canvas area (wrapper) otherwise link will not work on designs where we are using BG Layers https://jam.dev/c/2de04a6a-fe96-4f9e-b87f-9528d616a24d 

This is for button links generally, while this issue fixes author link, so will create an issue for this.

Also, could you please share a pattern or a video how to reproduce this:
> if use dc link on button block, there is displaying link is empty on backend, frontend is ok
https://jam.dev/c/36fb9616-9e0b-4d0c-83a2-83c63f956b81

**Review by Olekrut — APPROVED** [review]
@myroslavve almost sure that is related with https://github.com/maxi-blocks/maxi-blocks/issues/4978 or https://github.com/maxi-blocks/maxi-blocks/issues/5284 ( guess, the same, can close one of them if there are the same) . if it is easy you can fix, but it is another issue

**Review by elzadj — APPROVED** [review]

**Pull request merged**
