### PR TITLE
Issue 5314: IB preview in FSE

### LINKED ISSUE #5314: IB preview does not work on FSE
### Description

Master

### Step-by-step reproduction instructions

1) add patterns with IB to FSE template
2) check IB preview

### Screenshots, screen recording, code snippet

https://jam.dev/c/53579ba0-ac77-48bf-830f-db550c56d628

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Makes IB Preview work in FSE the same way as in usual Gutenberg Page Editor.

Fixes #5314 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the IB Preview in FSE Patterns
-   [ ] Test the IB Preview in FSE Templates
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Test the IB Preview in page editor

**_ Pre-Code Testing _**

-   [ ] Test the IB Preview in FSE Patterns
-   [ ] Test the IB Preview in FSE Templates
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Test the IB Preview in page editor
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Refactor**
	- Enhanced the application's compatibility with the site editor environment, including improved element handling and transitions.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
Warnings on FSE, backend. 
Even Attempt Block Recovery does not correct
https://jam.dev/c/a05b317c-ae1c-491b-a16d-a54b4b47de09 ( first 90sec )

Master brunch, load pattern with IB to FSE template > change brunch and check backend

**Comment by elzadj** [comment]
> Warnings on FSE, backend. Even Attempt Block Recovery does not correct https://jam.dev/c/a05b317c-ae1c-491b-a16d-a54b4b47de09 ( first 90sec )
> 
> Master brunch, load pattern with IB to FSE template > change brunch and check backend


Can't re-create it at all. @Marko64 could you try please? 

Screenshot from 2024-03-01 12-49-48

**Comment by elzadj** [comment]
@Olekrut ok, since I can't re-create it, could you please try again, and then give me the broken Gutenberg code from the template? Maybe then I can figure it out. Thanks!

**Review by Olekrut — APPROVED** [review]
LOL, idk, what is happened, but everything works already

**Pull request merged**
