### PR TITLE
Button Maxi style bug #2554

### PR DESCRIPTION
**Pull request by FitseTLT**
…ad of array in button maxi's style.js

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]

**Review by bilouStrike — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
Thanks! 
See the tests - border radius for shortcut 2 doesn't work, indeed. Can you figure out why, please?

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
As @elzadj  commented, if we are having a broken test with this implementation there are 2 options: or test was not working correctly (we need to believe they are correct) or something in the implementation run bad. Please, check which of both situations is the actual 👍

**Review by Naaaaiix — CHANGES_REQUESTED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Had a look at the broken tests, and they are right, so can be updated. What we see on them is that there's a part related with the `border-radius` which is removed. This happens because before the implementation `stylesCleaner` function couldn't affect the obj send by `style.js`; now this mentioned method can affect the object, it cleans it out, and removes part of the CSS that is not necessary 👍 

Other thing found, not sure if is related with this issue (if not, derive to a new one):

Captura de pantalla 2022-02-21 a las 16 41 17

**Review by Naaaaiix — CHANGES_REQUESTED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Please @FitseTLT , update tests 👍

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Found this CSS code:
`.maxi-button-block__icon svg > *{ fill: none; stroke: rgba(var(--maxi-light-color-1,255,255,255),1); margin-left: 5px;}`

the target `.maxi-button-block__icon svg > *` is affected by margin. It shouldn't be there 👍

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Captura de pantalla 2022-03-01 a las 13 37 26

🤔

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Still having this issue:

https://user-images.githubusercontent.com/50477222/156736677-c0707524-9fe7-4a70-8c3e-2386875bcd62.mp4

**Review by Alejandro9kgm — APPROVED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Still finding issues with the margin:
Captura de pantalla 2022-03-09 a las 9 28 29
Captura de pantalla 2022-03-09 a las 9 27 52

**Review by Naaaaiix — APPROVED** [review]
Cool, works good now 😸 

Fixed tests, onces checked this branch can be merged 👍

**Pull request merged**
