### PR TITLE
Issue 4515 - dc tags and cats

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Added categories and tags as options for posts in DC.

Fixes #4515 

# How Has This Been Tested?
Checked that tags and categories work in editor and on frontend.

# Test checklist

**_Front/Back Testing_**

-   [ ] Test tags and categories in DC on editor and frontend.

**_Pre-Code Testing_**

-   [ ] Test tags and categories in DC on editor and frontend.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/ca83d1fc-7cc9-47a5-8ebe-3c728483d0b3
1) dc links reference to post, not to category or tag
2) and need ability to add separate signs between them
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) on frontend visible only one cat or warning
 https://jam.dev/c/be0e7923-e384-4947-93da-ee55c868a669
backend
image
frontend
image

2) if turn on links > visible underline on frontend
image
image
3) if close editor and open again, we get 
image

**Review by darimshlk — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
Awesome) left one small thing) need to disallow ability, click on the link in the backend
it interferes
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/1c63e34f-c866-444f-9055-daff56f8d4a0

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
