### PR TITLE
Issue 5464: IB SEO score on frontend

### LINKED ISSUE #5464: IB - woo fixes
Ping me about this

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Optimizes IB script for SEO speed (and more) on frontend.

Fixes #5464

# How Has This Been Tested?

You need to compare the chrome Lighthouse score (both for mobile and desktop) on master and on that branch. This one should be much better.
Please do ```npm run build``` and always run lighthouse in incognito.
Also pls test IBs - new, old, from the cloud, in general.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Improved script loading strategies for enhanced performance: scripts related to 'relations' now load asynchronously, while others continue to defer.

- **Performance Improvements**
  - Optimized JavaScript logic for handling breakpoints and style generation, resulting in faster execution times.

- **Configuration Changes**
  - Updated default configuration to set "link-color-global" to false for better default styling.

- **Testing**
  - Streamlined end-to-end tests by removing unnecessary parameters for better test reliability.

- **Bug Fixes**
  - Enhanced content sanitization by replacing `wp_strip_all_tags` with `strip_tags` for more accurate content handling.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
Master:
Desctop:
image

mobile:
image

this brunch:
Desktop:
image
mobile:
image


Looks like mobile has problems now 

and have noticed errors in console
image
image

And backend loads very long, probably because there are a lot of blocks.
[woo part 1.txt](https://github.com/user-attachments/files/15848733/woo.part.1.txt)

**Comment by elzadj** [comment]
> Looks like mobile has problems now
Nope, please clear your cache, or remove the build folder and re-run ```npm run build```
'The page did not paint'... usually means Lighthouse can't run for some reason, usually cache https://stackoverflow.com/questions/55826735/how-to-fix-lighthouse-returned-error-no-fcp-when-running-google-page-speed-t

My results: 

Screenshot from 2024-06-17 11-39-51

>And backend loads very long, probably because there are a lot of blocks.
[woo part 1.txt](https://github.com/user-attachments/files/15848733/woo.part.1.txt)

A separated issue with woo DC / CL being slow.

**Review by Olekrut — CHANGES_REQUESTED** [review]
Is not awesome, but already without errors.

Desktop:
image

Mobile:
image


Guess, becasue need optimization, but attaching these videos
backend: frezzes and error of simple block ( 2nd-3rd re-update
https://jam.dev/c/f81f7051-3b7b-4b63-ae6c-238672072f26
frontend:  guess, because error dont work IB anymore
https://jam.dev/c/ddc9d6f4-3965-4105-9047-309cc734c116

**Comment by elzadj** [comment]
> Guess, becasue need optimization, but attaching these videos
> backend: frezzes and error of simple block ( 2nd-3rd re-update
> https://jam.dev/c/f81f7051-3b7b-4b63-ae6c-238672072f26

Local issue. Try to kill wp-env and install again. Or use the staging I've shared.

> frontend: guess, because error dont work IB anymore
> https://jam.dev/c/ddc9d6f4-3965-4105-9047-309cc734c116

Fixed.

**Review by Olekrut — APPROVED** [review]
Cool, desktop score looks much better, and i don't see error with IB
mobile is the same

**Pull request merged**
