### PR TITLE
Issue 3567 - accordion fixes

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Added more icon settings, more custom css targets, alignment for line, typography settings, separate settings for header and content, transitions. And fixed a bunch of bugs.

Fixes #3567 

# Test checklist

**_Front/Back Testing_**

-   [x] Test typography settings
-   [x] Test line settings
-   [x] Test icon settings
-   [x] Test pane settings
-   [x] Check that transitions work
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload

**_Pre-Code Testing_**

-   [x] Test typography settings
-   [x] Test line settings
-   [x] Test icon settings
-   [x] Test pane settings
-   [x] Check that transitions work
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — APPROVED** [review]

**Review by Marko64 — APPROVED** [review]
What do you think, would it be good to add typography settings for panes too?

**Review by Fybex — CHANGES_REQUESTED** [review]
1. Pane maxi, on the highest level we have 4 tabs, the same approaches on the first version were used on search-maxi, but was changed to nested tabs. We need to be consistent, so you can take a look on this https://github.com/maxi-blocks/maxi-blocks/blob/master/src/blocks/search-maxi/inspector.js#L110-L357 and do the same in Pane 👍
2. Clip path isn't working in header, content background inspector tab, as MVP we can remove it for a moment 👍 
3. Icon position isn't working

**Review by Fybex — COMMENTED** [review]
Good job, also we can replace `SelectControl` with `AxisPositionControl` for position, we are using it in `search-maxi` and `IconControl` 👍

**Review by Fybex — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
Looks great, good job @TeksPeks ✌️ 

Check why the tests are breaking and let's merge this beauty 👍

**Pull request merged**
