### PR TITLE
Issue 2576 - CustomCSS BackgroundDisplayer

### PR DESCRIPTION
**Pull request by Fybex**
Fixes #2576 

What was changed:
1. Create two new utils to background displayer: getBgLayersSelectorsCss, getBgLayersCategoriesCss.
2. Add this utils in inspector.js and styles.js in all components which has backgroundDisplayer ability:
          - column-maxi
          - divider-maxi
          - group-maxi
          - image-maxi
          - number-counter-maxi
          - svg-icon-maxi
3. Add situational ability to have category label and value (in this case it was needed)
4. Remove canvas background selector/category (he don't need to, his target is equal to canvas selector) and functions getCategoriesCss where was checked his availability.

Now we can set CustomCss to every background layer 🎆

How to test;
Set CustomCss to different background layers. Try to swap, delete them, etc.

Screens:
image
image

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Well done @Fybex ! 😻 

Some small points:
1. CustomCSS need more specificity on CSS and should be able to overwrite native component styles. As can be seen on this example, the opacity set from CustomCSS is not taken as the rgba is overwriting it:
Captura de pantalla 2022-03-28 a las 10 47 12

2. In case 'background hover' CustomCSS has some styles and then creator removes background hover status again, CustomCSS shouldn't render the styles anymore (`opacity:1` at the end):
Captura de pantalla 2022-03-28 a las 10 52 39

**Review by Naaaaiix — COMMENTED** [review]
Just few small things, we are almost done! 🥳

**Review by Naaaaiix — APPROVED** [review]
Time to update the tests! 

Such a great job, congrats @Fybex 🎉

**Review by Naaaaiix — APPROVED** [review]
Finally 😭 lol congrats @Fybex 🥳

**Pull request merged**
