### PR TITLE
Local fonts fix, 404 for google fonts fix

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Brings back Local Fonts, fixes them for SC. Also adds back some optimizations for local fonts that we lost along the way.
Fixes google fonts 404 errors when trying to load non-existent font weights. 

This is not a full optimization PR, we still need code refactoring for fonts.

Fixes #4757

# How Has This Been Tested?

Fonts settings in different variations. Different SCs, custom fonts, local and not. 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test local fonts disabled and enabled
-   [ ] Test different SCs
-   [ ] Test custom fonts
-   [ ] Mix 1-3 and test
-   [ ] Check that backend works and saves the settings after the editor reload

**_ Pre-Code Testing _**

-   [ ] Test local fonts disabled and enabled
-   [ ] Test different SCs
-   [ ] Test custom fonts
-   [ ] Mix 1-3 and test
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Local fonts doesn't work for FSE, so header and footer appear without font style:


https://github.com/maxi-blocks/maxi-blocks/assets/50477222/21500b2b-61e9-45bb-8c89-d2001df75a5e

**Review by Naaaaiix — COMMENTED** [review]
Awesome, seems the FSE fonts are working now. What I see is that we are loading same font twice, which can have an impact on SEO:

Captura de Pantalla 2023-05-12 a las 12 30 41

'Exo 2' font is loaded twice in the image. Do you think it worth trying to avoid duplicate?

**Review by Olekrut — CHANGES_REQUESTED** [review]
not sure, that it is related with this issue. On master the same
https://jam.dev/c/fe039dfe-3f55-41bc-87f9-b16e5ea0dd30
SC is not working on backend
only FSE

**Review by Naaaaiix — APPROVED** [review]
> Let's try this - we make the id for the template fonts css the same as the possible id from SC, so wp_enqueue_style works only for one of them 🤔 mvp in its minimum
> 
> @Naaaaiix

hahahahahaha that's called `squeeze the lemon` in my country lol 

In terms of logics seems a good one and it works. Let's pray to the holy HAL 9000 for it anyway 👐

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
