### PR TITLE
Issue:3290 NC text alignment option

### PR DESCRIPTION
**Pull request by FitseTLT**
# Description
Added text alignment option for NC

Fixes #3290 

# How Has This Been Tested?
Tested Text alignment option is working for NC

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [x] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]

**Review by Fybex — APPROVED** [review]
All works, but some minor things to consider:
1. Should we show `textAlign` even when circle is showed? 🤔 
2. Should `textAlign` have `center` by default?

**Review by Fybex — CHANGES_REQUESTED** [review]
image

**Review by Marko64 — APPROVED** [review]

**Review by Fybex — CHANGES_REQUESTED** [review]
All good,  just delete code from previous implementation with one more alignment and:

**Review by Fybex — APPROVED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
The idea is good, but IMO is overcomplicated and can be confusing for creators. I think it will be easier if we:
1. Remove the new toggle for `Set widht to fit content`
2. When removing the circle it directly disappears width options on `Number` accordion
3. Instead of using `fit-content`, use `auto` which has better compatibility between browsers
4. Instead of using CSS to overwrite BlockResizer styles using `!important` use its API method `updateSize`. You can find different examples on our blocks, like Column Maxi 👍

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Tests results are quite strange; they seem to share some error. Try to trace them please 👍

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Check it deeper, e2e tests shows something is broken 👍

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Still finding some small issues 👍 

https://user-images.githubusercontent.com/50477222/176224852-a95261c8-dda1-4b55-b2e6-ef155c675bf2.mp4

**Review by Marko64 — APPROVED** [review]

**Review by Fybex — APPROVED** [review]
Not sure, but maybe on auto we should just remove resizing as we are doing in image-maxi with BlockResizer showHandle prop 🤔  Just thoughts 👍

**Review by Naaaaiix — COMMENTED** [review]
Much better, thanks @FitseTLT 😸 🤟 

I agree with @Fybex, in order to keep the coherence with Image Maxi and in what is IMO a better UX, when auto is enabled the resizable handles should disappear 👍 the use of BlockResizer showHandle prop will help on it

**Review by Naaaaiix — APPROVED** [review]

**Pull request merged**
