### PR TITLE
Issue 5486 - validation for ACF DC attributes

### LINKED ISSUE #5486: UI confusion with ACF and DC CPT
### Description

Found a bit of a confusion with the UI if we create CPT with AFC (y, you can do it). 
They show under both sources: Wordpress and ACF, but only the WP one works. 

Not sure what's the best way to fix it here - hide it under ACF, or just make it work there too.

### Step-by-step reproduction instructions

1. Add CPT and CT with ACF
2. Check the DC / CL options
3. Choose ACF - your created CPT

### Screenshots, screen recording, code snippet

screenshot-wordpress local-2024 03 06-12_43_03

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Added validation to ACF attributes, so now DC blocks update when changing ACF group or source to ACF in CL.

Fixes #5486 

# How Has This Been Tested?
Inserted pattern from issue (PBGL-PRO-101), changed source to ACF in row CL, and checked that DC blocks updated.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Insert pattern from issue (PBGL-PRO-101), change source to ACF in row CL, and check that DC blocks update.

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Enhanced the `ContextLoop` component to support new parameters for improved content management.
  - Updated the `ACFSettingsControl` component for more efficient fetching and setting of ACF groups and fields.
  - Added new utility functions in `utils.js` for handling ACF attributes and options, enhancing data retrieval processes in WordPress environments.
  - Modified the `DynamicContent` component to include additional properties and arguments for enriched customization and control flow.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/e8b3cd4d-f58c-4b01-8ec5-47fa3cdba5d8
I have errors

**Comment by Olekrut** [comment]
I cant re-produce bug from previous comment anymore, but have another, is not the same, correct?
https://jam.dev/c/792453a2-f410-4528-9f0d-a6981cbaf14b
https://jam.dev/c/8dbadac1-e2b8-46c6-b360-a484df8fc7cc

**Comment by myroslavve** [comment]
> I cant re-produce bug from previous comment anymore, but have another, is not the same, correct? https://jam.dev/c/792453a2-f410-4528-9f0d-a6981cbaf14b https://jam.dev/c/8dbadac1-e2b8-46c6-b360-a484df8fc7cc

Didn't really understand the bug from the video, but I suppose that the problem is that the DC had post ids and content instead of movie ids when you changed CL, I checked it and cannot reproduce it, so could you share here if it is not the bug you were talking about, or any other details?

**Comment by Olekrut** [comment]
https://jam.dev/c/181dec66-0d1f-443c-b9b9-7f2261c9351e
does not work on frontend and images on backend dont work correct sometimes

**Comment by Olekrut** [comment]
image
example of acf content for post
image
[acf-export-2024-05-01.json](https://github.com/maxi-blocks/maxi-blocks/files/15176318/acf-export-2024-05-01.json)

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/181dec66-0d1f-443c-b9b9-7f2261c9351e
example of acf content for post
image
[acf-export-2024-05-01.json](https://github.com/maxi-blocks/maxi-blocks/files/15176318/acf-export-2024-05-01.json)

**Comment by myroslavve** [comment]
> https://jam.dev/c/181dec66-0d1f-443c-b9b9-7f2261c9351e does not work on frontend and images on backend dont work correct sometimes

The frontend problem was fixed here https://github.com/maxi-blocks/maxi-blocks/pull/5560, just wasn't merged on this branch,

and I couldn't reproduce the problem with images on editor, even after I tried doing exactly what you did, also not related so if you keep seeing it, please create an issue for it.

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/b95cbb74-2861-4295-91f4-8ccdbe906cfb
images are not rendering on backend

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/8e5ef71a-355b-4cc7-93a2-4e8757d7ce53
images are not working yet for backend

**Comment by myroslavve** [comment]
> https://jam.dev/c/8e5ef71a-355b-4cc7-93a2-4e8757d7ce53 images are not working yet for backend

Can't reproduce anymore, could you check again?

**Comment by myroslavve** [comment]
> https://jam.dev/c/8e5ef71a-355b-4cc7-93a2-4e8757d7ce53 images are not working yet for backend

Fixed.

**Review by Olekrut — APPROVED** [review]
okkk,, it works better now, but with delay about 5-10sec
https://jam.dev/c/232ebf4d-be99-40aa-a69d-2c717e6ccf47

**Review by elzadj — CHANGES_REQUESTED** [review]
1. Getting 
```
withMaxiDC.js:197 TypeError: Cannot read properties of null (reading 'return_format')
    at _callee2$ (getDCMedia.js:86:13)
    at tryCatch (regenerator-runtime.js?ver=0.14.0:64:40)
    at Generator.invoke (regenerator-runtime.js?ver=0.14.0:299:22)
    at Generator.next (regenerator-runtime.js?ver=0.14.0:124:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
  ```
  for images after switching to ACF. Same ACF data as @Olekrut shared.
Screenshot from 2024-05-08 13-42-46

2. The ACF content loads only after I click inside the Row:
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.05.08-13_43_44.webm](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/fe04c43c-7fa5-4ac2-b895-7287571e0afd)

WP 6.5.3

**Comment by myroslavve** [comment]
> 1. Getting
> 
> ```
> withMaxiDC.js:197 TypeError: Cannot read properties of null (reading 'return_format')
>     at _callee2$ (getDCMedia.js:86:13)
>     at tryCatch (regenerator-runtime.js?ver=0.14.0:64:40)
>     at Generator.invoke (regenerator-runtime.js?ver=0.14.0:299:22)
>     at Generator.next (regenerator-runtime.js?ver=0.14.0:124:21)
>     at asyncGeneratorStep (asyncToGenerator.js:3:1)
>     at _next (asyncToGenerator.js:22:1)
> ```
> 
> for images after switching to ACF. Same ACF data as @Olekrut shared. Screenshot from 2024-05-08 13-42-46
> 
> 2. The ACF content loads only after I click inside the Row:
>    [screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.05.08-13_43_44.webm](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/fe04c43c-7fa5-4ac2-b895-7287571e0afd)
> 
> WP 6.5.3

Fixed both points.

**Review by elzadj — APPROVED** [review]

**Pull request merged**
