### PR TITLE
Change fragments

### PR DESCRIPTION
**Pull request by Alejandro9kgm**

### CODE REVIEW

**Review by javadsamiee — COMMENTED** [review]
I see some Fragment remaining yet, search all plugin and change them

image

**Review by javadsamiee — APPROVED** [review]
Good job 👍🏻

**Review by javadsamiee — COMMENTED** [review]
Also these errors
image

**Review by Naaaaiix — APPROVED** [review]
Cool! Good job @Alejandro9kgm 😸

**Pull request merged**
