### PR TITLE
Issue 4008 - booleans on responsive

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
- modified `cleanAttributes` to keep boolean attributes.
- migrated `full-width` attributes from string to boolean.

Fixes #4008

# How Has This Been Tested?
Checked that the issue was fixed. Checked that migrator works, [here is code editor to test](https://github.com/maxi-blocks/maxi-blocks/files/11063996/fullwidthcodeeditor.txt) (button should be full width and container should not be full width).

# Test checklist

**_Front/Back Testing_**

-   [ ] Check that the issue has been fixed.
-   [ ] Check migrator with given code editor or with patterns from library.
-   [ ] Check that backend works and saves the settings after the editor reload

**_Pre-Code Testing_**

-   [ ] Check that the issue has been fixed.
-   [ ] Check migrator with given code editor or with patterns from library.
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — APPROVED** [review]

**Review by darimshlk — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
is not fixed https://jam.dev/c/5ffe7a78-16af-4608-b039-c6a08f28e896

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/6ed11a01-e965-40ad-8e18-5d3e5066bb8b
need to check for all toggle buttons

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
We definitely need to add 1.0.0, 1.0.1 and 1.1.0 version to the migrator. Our next release version is 1.1.1

**Review by Naaaaiix — APPROVED** [review]
Awesome job @TeksPeks 👏

**Review by elzadj — APPROVED** [review]

**Pull request merged**
