### PR TITLE
Issue 5022 - Canvas hover toggle for Icon, Transform, CustomCSS

### LINKED ISSUE #5022: Hover toggle for blocks with canvas
### Description

https://2devdemo.maxiblocks.com/maxi-buttons/
for example,  button #7
https://jam.dev/c/76bc6ba7-a5fe-4a6c-94c4-193a20c00e73
i want to make work them together in any case) but sometimes they should work separately) so need a toggle

### Other plugins or websites examples

_No response_

### How to implement it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #5022 

# How Has This Been Tested?

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/d4aaeedb-29ba-481b-a9a8-a7de0f5ed718

code editor: [https://2devdemo.maxiblocks.com/maxi...](https://2devdemo.maxiblocks.com/maxi-buttons/)

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test if new toggle works in `IconControl`
-   [ ] Test if new toggle works in `TransformControl`
-   [ ] Test if new field works in `CustomCSS`
-   [ ] Test if other icon styles work without changes

**_ Pre-Code Testing _**

-   [ ] Test if new toggle works in `IconControl`
-   [ ] Test if new toggle works in `TransformControl`
-   [ ] Test if new field works in `CustomCSS`
-   [ ] Test if other icon styles work without changes
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Introduced hover effect customization for icons and SVG elements.
  - Added toggle switches for new hover attributes in the inspector panel.
  - Implemented new selectors for hover states on canvas elements.

- **Enhancements**
  - Improved the logic for applying transform styles to elements.
  - Streamlined the creation of CSS selectors for pseudo-elements.

- **Refactor**
  - Refactored hover target logic for button icons.
  - Optimized transform string generation with new utility functions.

- **Style**
  - Updated hover styles for better user interaction feedback.
  - Adjusted CSS generation to support new hover features.

- **Documentation**
  - Updated inline documentation to reflect changes in hover and transform functionalities.

- **Bug Fixes**
  - Fixed issues with incorrect hover state application on certain components.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
Looks awesome))
1) i guess, responsive support is unneeded) we can leave it visible only for base breakpoint
2) make all switches enabled by default

**Comment by Olekrut** [comment]
@Fybex add to them as well field with canvas:hover

**Review by Olekrut — CHANGES_REQUESTED** [review]
Great) Everything works good) 
left only it icon`s hovers and hope we will not back to it anymore
image

and need to make toggle for these 4 settings as well, just in case, can be useful
image

**Comment by Fybex** [comment]
> Great) Everything works good) left only it icon`s hovers and hope we will not back to it anymore image
> 
> and need to make toggle for these 4 settings as well, just in case, can be useful image

1. added new selectors to icon custom css 
2. deriving it into #5270

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
change order
group similar fields
for all pls
Example:
Custom CSS for icon
Custom CSS for icon hover
Custom CSS for icon canvas hover

**Review by Olekrut — APPROVED** [review]

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
