### PR TITLE
Issue-2900 : Number Counter new features

### PR DESCRIPTION
**Pull request by bilouStrike**
FIxes: #2917 2900

### CODE REVIEW

**Review by Alejandro9kgm — APPROVED** [review]

**Review by FitseTLT — CHANGES_REQUESTED** [review]

**Review by FitseTLT — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
The default is medium, not thin 
Edit Page ‹ Local Wordpress — WordPress (6)

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Not sure what happens, but many tests are broken 🤔

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
SVG Icon block alignment doesn't work 👍

**Review by Naaaaiix — APPROVED** [review]
Thanks for the fixes @bilouStrike , good job 😸 

Last test to fix, I think we just need to rollback the old snapshot 👍

**Review by Naaaaiix — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
