### PR TITLE
Issue 3331 - Search maxi

### PR DESCRIPTION
**Pull request by Fybex**
# Description

#### Major changes:
- created maxi-search block
- created inspector-icon, based on `IconControl`
- added prefix supports or disable some options in many controls, helpers
- made changes in `copy-paste` to be able to set multiply prefixes to each block in copy-paste file(needed to search-maxi work)
- updated `transitions` related code to be able to have it in a correct way in search-maxi, made this contol more flexible

P.s. Design isn't fully match final result

Fixes #3331 
# How Has This Been Tested?
Tested all search-maxi functionality

# Test checklist

**_ Front/Back Testing _**

-   [x] Test the search-maxi in general
-   [x] Test if SVG's (svg-icon-maxi, button-maxi icon works fine, made a lot of changes)
-   [x] Test if `copy-paste` works fine in other blocks too
-   [x] Test if `transition` works find in other blocks too
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points for the toolbar
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second

**_ Pre-Code Testing _**

-   [ ] Test the search-maxi in general
-   [ ] Test if SVG's (svg-icon-maxi, button-maxi icon works fine, made a lot of changes)
-   [ ] Test if `copy-paste` works fine in other blocks too
-   [ ] Test if `transition` works find in other blocks too
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]
Great job, love it.

Tested copy/paste, transitions and icons, everything seems to be normal. Tested that it works in general (tested adding, changing basic settings).

The new module is cool. Everything looks good. The only single thing that I didn't like, and isn't something related to your work, is that when you select the module, the orange outline covers the actual module border so we may want to think how to solve that.

**Review by FitseTLT — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
- Long-ish text on button looks weird 

sfsadfasdf – Local WordPress

- Use clip-path does not work for Button and Input Bgs (do we even need it there?)
- I think we should somehow process an empty input and show a notification if user tries to search for nothing. Not sure here :thinking:  
- Again, not sure when we should hide the placeholder - when we click inside the input, or when we start typing: 
[video-9903126-08f4a200021dd562fd0da86c97a70b55.webm](https://user-images.githubusercontent.com/2401618/178265128-f3713ac9-20fc-45c3-8071-b6256496b4c5.webm)

@ckp267 I recall we had the same question with Divi search, can you remind me what we decided then?

**Review by Marko64 — CHANGES_REQUESTED** [review]
Works good.
Noticed some border in the search settings panel:
Screenshot_2

**Review by Marko64 — APPROVED** [review]

**Review by kyrapieterse — APPROVED** [review]
Much better :)

**Review by Marko64 — APPROVED** [review]

**Review by FitseTLT — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Good job, looks fantastic ✌️ Left some comments 👍 lol

- When not in `general`:
Captura de Pantalla 2022-08-02 a las 10 48 46


PS: there are comments from my first review some weeks ago; is possible that the code has been modified since 👍

**Pull request merged**
