### PR TITLE
Issue 2340 background control UI

### PR DESCRIPTION
**Pull request by Rustam198804**
Fixes issue #2340

### CODE REVIEW

**Review by kyrapieterse — APPROVED** [review]
looks great! good job :)

**Review by Naaaaiix — COMMENTED** [review]
Well done, looks amazing! 😻 onces everything is fixed and the PR approved I'll fix the `unit-tests` incompatibilities to merge it 👍

**Review by elzadj — CHANGES_REQUESTED** [review]
Works and looks great, I've found just one small thing (shape layer):
Edit-Page-‹-Local-Wordpress-—-WordPress (78)

**Review by Naaaaiix — APPROVED** [review]
Magnific 👏 🥳

**Review by elzadj — APPROVED** [review]
:+1:  Great, thank you @Rustam198804 !

**Pull request merged**
