### PR TITLE
Issue 3414 - Full Size Editing (FSE) support

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Changes:
- changed `maxi-blocks-responsive` attribute logic, now it has `winBreakpoint` when breakpoint general, because of this `maxi-themes.scss`(SC styles) also has some changes
- in `styleGenerator` remove styles, breakpoints of which lower than current breakpoint (only for FSE)
- changed, modified many targets in `dom.js` to have FSE support
- rename `post` route to `styles`, add `isTemplate`, `templateParts` to `custom-data` and `styles` route to save FSE data to separate tables, which was created
- FSE `uniqueId` and `customLabel` has prefix `-template` or `${templatePartName}-template-part`

Fixes #3414

# How Has This Been Tested?

⚠️ BEFORE TESTING, DISABLE AND ENABLE PLUGIN TO ADD NEW DB TABLES ⚠️ 
⚠️ Not all themes support Full Size Editing, from defaults you can select twenty-twenty-two(three) theme ⚠️ 
Tested FSE in general, tested how works styles and custom data with different templates on posts.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test FSE editor in general (template, template part editors, template part preview in template part block, etc) 
-   [ ] Test how created in FSE templates are working in posts, pages (styles: block styles and style cards, custom data: relations, number-counter, etc)
-   [ ] Test with different themes, which support FSE
-   [ ] Check if default editor isn't broken (especially styles: block styles and style cards)
-   [ ] Check if posts from default editor isn't broken on frontend

**_ Pre-Code Testing _**

-   [x] Test FSE editor in general (template, template part editors, template part preview in template part block, etc) 
-   [x] Test how created in FSE templates are working in posts, pages (styles: block styles and style cards, custom data: relations, number-counter, etc)
-   [x] Test with different themes, which support FSE
-   [x] Check if default editor isn't broken (especially styles: block styles and style cards)
-   [x] Check if posts from default editor isn't broken on frontend

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Naaaaiix — APPROVED** [review]
Awesome 👏 🥳 

Couple of comments. About to keep working on it or what to do, I'll write you on the chat 👍

**Review by Olekrut — CHANGES_REQUESTED** [review]
[FSE.txt](https://github.com/maxi-blocks/maxi-blocks/files/10411943/FSE.txt)
1) Smth weird with column width after clicks ( grid broke)   https://jam.dev/c/b9c3cf1b-e605-43f2-a751-5a277d5d887e
2) wrong SVG colours in footer https://jam.dev/c/8f3dfd43-11d3-4395-a267-4f2834ac4580
3) Cant click to appenders inside Header`s and Footer`s a after save and reload page https://jam.dev/c/11f23c0d-14fa-483a-9cc1-81bfb761aca8

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) image
https://jam.dev/c/fe034d08-bd1f-4dd1-a02d-e342dd9ea74b
2) https://jam.dev/c/4c74ffbf-e91b-4491-a516-f9ed43074bef
grid is braking after open insert window

**Review by Olekrut — APPROVED** [review]
I have not found nothing anymore But have bad feeling) I guess, i skip smth

**Review by Marko64 — CHANGES_REQUESTED** [review]
When you add an image to the footer, it throws the following error:
`Fatal error: Cannot redeclare local_fonts_preload() (previously declared in /var/www/html/wp-content/plugins/Maxi-Blocks/core/class-maxi-styles.php:439) in /var/www/html/wp-content/plugins/Maxi-Blocks/core/class-maxi-styles.php on line 439`

**Review by myroslavve — COMMENTED** [review]
Can't find any bugs, left a couple of comments on code.

**Review by myroslavve — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
Getting a lot of 

```
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at start (components.js?ver=2415973c4227a31b8a15:52351:35)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=17.0.1:3942:16)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=17.0.1:3991:18)
    at invokeGuardedCallback (react-dom.js?ver=17.0.1:4053:33)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.js?ver=17.0.1:4067:27)
    at executeDispatch (react-dom.js?ver=17.0.1:8273:5)
    at processDispatchQueueItemsInOrder (react-dom.js?ver=17.0.1:8305:9)
    at processDispatchQueue (react-dom.js?ver=17.0.1:8318:7)
    at dispatchEventsForPlugins (react-dom.js?ver=17.0.1:8329:5)
    at react-dom.js?ver=17.0.1:8538:14
react-dom.js?ver=17.0.1:4088 
```
when I drag a block (an svg icon in that case) in FSE (it works tho). The theme is 2023.

**Review by elzadj — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
This is a masterpiece, tbh. Detailed, commented, clean, simple in its complexity and perfectly organized and integrated on Maxi. Congrats, it's hard to beat 👏

**Pull request merged**
