### PR TITLE
Issue 3304 - Transition `change all` toggle

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Question: should `transition-change-all` attribute be `true` or `false` by default 🤔 

Fixes #3304 

# How Has This Been Tested?
Added blocks and tested if change all transitions toggle logic work correct 👍🏿 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Test the block inside the grid (Container + Row + Column)

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — CHANGES_REQUESTED** [review]
A couple of things:

- Button icon doesn't seem to be affected with this.
- SVG icon; transitions don't seem to be working at all.

**Review by Marko64 — APPROVED** [review]

**Review by FitseTLT — CHANGES_REQUESTED** [review]
Disable transition is not working in responsive.

**Review by FitseTLT — APPROVED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Check this logics:
1. Enable some hover setting
2. Go to transition, select and disable transitions for it
3. Click on `Change all transitions`

Magic! 🪄 

Captura de pantalla 2022-06-16 a las 17 23 53

PS: commented with the team, set default as true 👍

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Buggy buggy 🕺 

https://user-images.githubusercontent.com/50477222/174335836-1bbfa36a-0209-44ac-8a10-cd82fa405325.mp4

PS: please, add unit tests for transition change-all and the possible scenarios 👍

**Review by Naaaaiix — APPROVED** [review]
Good job! 👏 

Only thing I see and if it's true let's open a new issue for it: is it necessary that the main block HTML element has also `top` and `left` transitions, or is just bg?
Captura de pantalla 2022-06-22 a las 20 26 14

**Pull request merged**
