### PR TITLE
Issue 4324 - clean up code for SC Editor

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Fixes #4324 

# How Has This Been Tested?

Test SC Editor - the SC Library modal, the confirmation dialogue boxes (when you activate or delete a card). 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the SC Editor
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same points on responsive

**_ Pre-Code Testing _**

-   [ ] Test the SC Editor
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same points on responsive
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Naaaaiix — APPROVED** [review]
Cleaner 👏 

What is commented is not necessary for beta, if you consider @elzadj to merge it and fix it later, no problem 👍

**Review by Olekrut — CHANGES_REQUESTED** [review]
image

**Review by ckp267 — APPROVED** [review]
"Boom shakalaka! This is so damn amazing, like a juggling flamingo riding a unicycle on a tightrope!"

Good to go...

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) maxi-accordion-control__item should be closing when we chose our SC 
https://jam.dev/c/e05f678b-efca-435b-a60a-410f386403a6
2) when we are giving name for customize card and clicking cancel, typed before label should be dropping
https://jam.dev/c/ac86d630-e2c0-41eb-bf04-61224cd03154
3) if we are changing font-family for dark tone in SC, it is not changing font-family in Sidebar
https://jam.dev/c/0d1ef5b5-5f55-4de3-a20f-14a6ffdb4f5c

**Review by Olekrut — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
Looks good, few details 👍 

Derive them into a new issue if necessary to prioritize beta; it works that is the important 👍

**Review by Naaaaiix — APPROVED** [review]
Looks good, few details 👍 

Derive them into a new issue if necessary to prioritize beta; it works that is the important 👍

**Pull request merged**
