### PR TITLE
Issue 439 

### PR DESCRIPTION
**Pull request by abder**
This PR aims to fix the issue described in #439 

Screenshot from 2020-09-22 18-23-01

### CODE REVIEW

**Review by javadsamiee — COMMENTED** [review]
I think it didn't need to add 'disableHorizontalPadding' to SettingTabsControl, you can fix it easily with CSS to specific component. we have this problem in video as-well so please inpect them in your browser and fix it with the only CSS . Blew image is related to background image. 

Pasted_Image_9_23_20__9_19_AM

P.S for !important be careful to use it, some time we don't need it

**Review by Naaaaiix — APPROVED** [review]
Much better, good job 👍 😄

**Review by javadsamiee — COMMENTED** [review]
I see some problems here

Pasted_Image_9_23_20__6_04_PM

Pasted_Image_9_23_20__6_06_PM

Pasted_Image_9_23_20__6_06_PM

**Review by javadsamiee — APPROVED** [review]
Good job man 👍

**Pull request merged**
