### PR TITLE
Issue 1276

### PR DESCRIPTION
**Pull request by javadsamiee**
Fix Axis Control for various values

### CODE REVIEW

**Review by Naaaaiix — APPROVED** [review]
Good job buddy! What you don't guess is that you fixed another issue lol PositionControl was under the same situation, so 2 birds in one shot 💪

**Review by Alejandro9kgm — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Some frontend error:
Captura de pantalla 2021-04-20 a las 16 30 55

**Review by Naaaaiix — COMMENTED** [review]
Cool! Some bugs fixed, and code looks much cleaner. Couple of things:
1. When doing changes, please request review to all the members. Even if it was approved, is important to recheck 👍 
2. Found this, I think is not the expected behavior:
Captura de pantalla 2021-04-22 a las 9 26 06

**Review by Naaaaiix — APPROVED** [review]
Yeaaaaah! 🥳

**Review by Alejandro9kgm — APPROVED** [review]

**Pull request merged**
