### PR TITLE
Issue 5078 - DC character limit label

### LINKED ISSUE #5078: DC. Toggle for unlimited characters
### Description

Sometimes character limit is unneeded, so need to add toggle button, when we want to disable it. Because content can be longer than 9999 characters.
image

### Other plugins or websites examples

_No response_

### How to implement it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Marko64**
Added a description text below the label.

Fixes #5078

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### Summary by CodeRabbit

- Style: Added a new CSS class `.dc-unlimited` with specific styling properties for the `DynamicContent` component when the character limit is set to unlimited.
- New Feature: Improved user interface by displaying a message indicating that a character limit of 0 represents unlimited characters in the `DynamicContent` component.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
I don't see description text below the label.

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
Maybe better to add it as info for date, because looks weird
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) image
Looks weird, I guess, will be better to move help icon here ( SC )
2) https://jam.dev/c/aa375ded-1603-40c8-8600-de6c092b5da9
Help Icon for DC Date is not working on this brunch

**Review by Olekrut — CHANGES_REQUESTED** [review]
Cool) Fixed) one small thing
image
I guess, need to align input field
maybe to add width:100% for maxi-info__help-trigger

**Comment by Marko64** [comment]
Created a new PR for this issue.

**Pull request closed without merging**
