### PR TITLE
Issue 4047 - select control reset

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Added reset button on `SelectControl`

Also:
 - Added `hideResetButton` prop to `SelectControl`, which hides reset button where, it is not needed, and applied it at some places.
 - Added `onReset` and `defaultValue` props to `SelectControl` for resetting values, and added default values to reset on most of `SelectControl` instances.

Fixes #4047 

# How Has This Been Tested?
Checked all `SelectControl`s look good (don't have reset button if it is not needed) and reset to correct values.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check that all `SelectControl`s you can find have reset button only if is needed.
-   [ ] Check that all `SelectControl`s you can find reset to the correct initial value (except for ANC unit select, those reset buttons are not part of `SelectControl` and are not related to this PR).

**_ Pre-Code Testing _**

-   [ ] Check that all `SelectControl`s you can find have reset button only if is needed.
-   [ ] Check that all `SelectControl`s you can find reset to the correct initial value (except for ANC unit select, those reset buttons are not part of `SelectControl` and are not related to this PR).
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — COMMENTED** [review]
Found only a few reset values that are possibly not right:

Text block
- Font weight default is 400 but resets to 100

Video
- Aspect ratio default is 16:9 but resets to none
- Icon position select is too small to fit the text now.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/fb3b886a-176d-4feb-a7ab-1448ee147276 -  responsive support, should not reset to default - (each block with topography: Text-block, button, map, NC, etc)
2) https://jam.dev/c/3d35a26e-da51-4c18-803c-fbc0b883ee6d - overflow - wrong reset - responsive support - maybe related with sync button
3) https://jam.dev/c/08cca0bd-96ef-48c0-b503-524bf9063488 - (image-block)  - caption position don't have responsive support and not sure that it need - I guess, just need remove reset button from here 
4) Clip-path type - working not correct - I guess, just need to remove reset button
image
5)Map-block - I guess, just need to remove reset button
image
6) NC-block -  I guess, just need to remove reset button
image
7) Search-block -  I guess, just need to remove reset button
image
image
8) Accordion -  I guess, just need to remove reset button
image

**Review by Olekrut — COMMENTED** [review]
1) image-block  just need remove
image

**Review by Olekrut — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Awesome job @TeksPeks, and brilliant review @Olekrut 👏 🥳 

Just one comment: not sure about the necessity of `hideResetButton`; maybe with just the fact of not having an `onReset` function, the button shouldn't appear, and we can remove one prop. What do you think @TeksPeks?

Waiting an answer to approve this PR 👍

**Review by elzadj — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]

**Pull request merged**
