### PR TITLE
Issue 5119 - Added: Text wrap

### PR DESCRIPTION
**Pull request by Marko64**
Added text wrap property in typography settings.

Fixes #5119 

Screenshot_10

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Introduced a new "Text wrap" option in the Typography Control with selectable choices to enhance text styling.

- **Enhancements**
  - Improved text styling logic to support text wrapping across various components.

- **Bug Fixes**
  - Corrected style application in the Text Maxi block when containing links.

- **Tests**
  - Added wait timeouts in e2e tests for headings and paragraphs to ensure stability.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) Not sure how to fix it, probably need a warning text or smth else.
White-space overwrite text-wrap. 
https://jam.dev/c/05c92863-f820-44ee-b91b-60f9116de30f
2) Similar settings, guess, better to make them  side by side
image

**Comment by Marko64** [comment]
Text wrap: controls how **text** is wrapped
White space: controls how **white space** is handled

They are similar, but still different settings. If they don't affect each other by default, I think that's OK. But makes sense to move the text wrap just above whit space.

**Comment by Olekrut** [comment]
Text-wrap is not working from SC
https://jam.dev/c/906924fc-6ea4-4dd5-8843-7b8f4bd69dfb

**Comment by elzadj** [comment]
And looks like the snapshots for ```npm test``` should be updated, it adds new attributes:
```
 +   "text-wrap-general": undefined,
    +   "text-wrap-l": undefined,
    +   "text-wrap-m": undefined,
    +   "text-wrap-s": undefined,
    +   "text-wrap-xl": undefined,
    +   "text-wrap-xs": undefined,
    +   "text-wrap-xxl": undefined,

```

**Review by Olekrut — CHANGES_REQUESTED** [review]
SC change value in sidebar it is not influence to text ( backend and frontend )
so text-wrap does not work from SC yet

**Comment by Marko64** [comment]
It was a Chrome issue so I didn't pick it up. Fixed now

**Review by Olekrut — APPROVED** [review]

**Comment by elzadj** [comment]
@Marko64 can't figure out why the tests are failing on github (they pass on my local). Any ideas?

**Comment by Marko64** [comment]
@elzadj These same tests fail on my local, even on master 🤔

**Comment by elzadj** [comment]
@Marko64 aha! Going to try to fix them.

**Comment by elzadj** [comment]
Both pass for me on master. I think it depends on if you destroy and re-install wp before testing, because of the sc-variables first generation.

**Comment by elzadj** [comment]
Fixed tests and merged master
@Olekrut could you pls check that the Text wrap still works as expected? Too many changes in master since this branch was created.

**Review by Olekrut — CHANGES_REQUESTED** [review]
white-space does not work from SC

**Comment by elzadj** [comment]
@Marko64 I don't think that's going to work, also we kinda re-write white-space with text wrap by default, that's not a good solution - what about people who set white-space to nowrap before?
@Olekrut what do you think?

**Comment by Marko64** [comment]
If the white space has the priority then text wrap won't work.

We can have a toggle to enable/disable text wrap and set it to disabled by default,
or we can leave as it is now (people control the wrap using the new text wrap setting) - probably only a few people changed the white space (can only guess)

**Comment by Olekrut** [comment]
I ve used White-space in patterns, hard to say, how many, but more than 50 for sure

> If the white space has the priority then text wrap won't work.
> 
> We can have a toggle to enable/disable text wrap and set it to disabled by default, or we can leave as it is now (people control the wrap using the new text wrap setting) - probably only a few people changed the white space (can only guess)

**Comment by elzadj** [comment]
@Olekrut let's try this one. Ping me if we need to add a note to White Space 'Could be rewritten by text wrap' or something like this.
Note: please reset SCs if you changed / created them on the previous iteration of that branch: 

```wp.data.dispatch('maxiBlocks/style-cards').resetSC()```

**Comment by Olekrut** [comment]
@elzadj 
if set text wrap balance > change resopnsive > set text wrap use white space > it is not working correct
image
the same for SC and sidebar settings

**Comment by elzadj** [comment]
@Olekrut we can't hide it on responsive, because it's a part of typography

**Comment by elzadj** [comment]
Fixed text-wrap responsive for blocks and remove it from SC for now - can' fix responsive for it when it depends on white spaces.

@Olekrut please test, but first reset SCs:
```wp.data.dispatch('maxiBlocks/style-cards').resetSC()```

**Review by Olekrut — CHANGES_REQUESTED** [review]
Is not fixed yet
1) set in sidebar white-space:nowrap; and text-wrap: balance; > change BP to L > change text-wrap to use the white-space >  does not work
2) Set in SC white-space:nowrap and set in sidebar text-wrap: balance; > change BP to L > change text-wrap to use the white-space >  does not work

**Pull request closed without merging**
