### PR TITLE
Issue 3388 - DC

### PR DESCRIPTION
**Pull request by Naaaaiix**
# Update 3/3/23
This PR is not for Text Maxi any more, now it includes DC for:
- Text Maxi
- Button Maxi
- Image Maxi
- Link component

🥳 

# Description

This PR replaces #4215

Basically does the same as the previous PR: it gives DC support to Text, Button and Image Maxi, and Link component. Changes done in this branch:
1. Replaces 'apiFetch' calls with 'entity' calls (WP method for Gutenberg)
2. Removes DC JS file from frontend
3. Adds e2e simple tests
4. Simplified the supported fields
5. Adds a new HOC for all future DC blocks (`withMaxiDC`)
6. Add support to update the content when loading the EE
7. Adds DC support as 'inspectorTab' to appear in settings sidebar
8. Creates DC folder with function and DC logics for future supported blocks
9. Reduced the re-renders
10. Increased the speed
11. Fixes errors

These are the expected actions you can do with DC depending on the block:
- [Text Maxi](https://docs.google.com/drawings/d/1G3LXxwKBRRQJUhSv81hcj3h3nHKlDbFuMqkW3WjnxNU/edit?usp=share_link)
- [Button Maxi](https://docs.google.com/drawings/d/1PRdr6TNC9JSB63eR7T3S_nqX-vwQ7Fx9L1B-WasI3K4/edit?usp=share_link)
- [Image Maxi](https://docs.google.com/drawings/d/13CFNIc1PLrQK-RukvJrlGIjvohNGuQ-IrqENLxB29UI/edit?usp=share_link)

Other actions and field support will be added in future, these are the simplest and most important ones. If a new one is necessary, please think on sharing a diagram like the one above.

Some known issues:
1. Styles might need some love
2. Using custom-date, the frontend is not exact sometimes. We need to reduce options or fix it somehow 👍 
3. On changing the type it returns a console error sometimes; doesn't affect the functionality
4. On Image Maxi, alt and caption components on the sidebar need to be checked. Didn't fix it as it need deeper look and I prefered to don't mix topics.
5. When enabling the link from DC on Link component of the Toolbar, you'll need to click out and it will update. It's an issue on the component that needs to be fixed apart.
6. Not sure how to deal when blocks like Image doesn't have any content on frontend, will fix it next week.
7. Part of the code needs to be cleaned, like 'dc-error' 👍 
8. Need to check the relation of Text Maxi with List options when DC.
9. It's probable that some options get in conflict with DC. Share the ones you find please.

PS: not sure if tests will pass 🤔 

Fixes #3388 

# How Has This Been Tested?

Created a block for each one of the diagram options. When 'get random', test reloading on frontend different times and seeing different values (ensure there's more than one type of element of what you want random). For custom date, test different values and see which ones are necessary and which one can we remove

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test DC for Text Maxi a loooooot! lol

**_ Pre-Code Testing _**

-   [ ] Same than before lol
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) Character limit is resetting to 150, not to default 100
https://jam.dev/c/6082ec60-4702-4b54-8c2d-962d555c1e0f
2) Chose Date > Click to custom Date > click to link which open tab in sidebar > then try to disable Custom Date > After clicking, everything freezes and I can't click anything else. Even cant refresh page. 
https://jam.dev/c/48d4061d-44a5-4fbb-a828-8ee8ee2d09a9
3) info icon for date at wrong place, and without styles
image
4) in the info window, I guess, better to add space after hyphen
image
5) between designations should be only 3 signs ( 2 spaces and separated sign between them)
image
6) here should be ability to add Categories and Tags which related only with curent post
image
7) We can add link, but this link is not working on frontend, cant click to it
image
8) maybe need character limit for CAT and TAG description as well?
image
9) Category > Parent is not working on backend, only on frontend
https://jam.dev/c/d087b320-172f-4b7d-a0c0-8bc266b9f332
10) Tags cant have parent, so need to remove it for Tags
image
11) it is not important, but if we dont have smth, maybe we can change "No content found" to "please add tags" or "please add Excerpt" or "please add Description" etc.
image
12) For type - Site nothing is not working or I do smth wrong?
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
5) we can add between letters more than 3 signs, need to limit it if possible
6) 
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
need to disallow ability to change image if we are enabling DC for Image
https://jam.dev/c/8bfa5041-afa7-44e1-bd73-7411fc7f98ae

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) @Naaaaiix should not link for Text DC use it?
image
2) Link to author is not working
https://jam.dev/c/5359b9cb-8c28-4f41-857e-735c81b1a0d0

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]
Works great :+1: 

I already see our clients asking "how can I show a custom post type" and "how to show a custom field?"  :smile: 

They already are lol later tho

image

**Pull request merged**
