### PR TITLE
Issue 4185 - Fix responsive attributes behaviour on temporary overlap from higher attribute

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #4185 

# How Has This Been Tested?
Checked in video from issue if other attributes were restored if changed attribute value didn't stop on the same value as other attrs is.

Cases from issue, but how it should look after fix (on this branch):
1.

https://user-images.githubusercontent.com/46112160/210411472-20501e0d-31d4-4b43-84f6-0580c3800a04.mp4

https://user-images.githubusercontent.com/46112160/210412620-cbb498ee-d7aa-4cf9-b8a7-a38eb39e13c1.mp4

(this video hasn't incorrect analogue in issue, but you can try to reproduce it by yourself in master to see incorrect result)

⚠️ also test how it works with transform-control, bug example: https://github.com/maxi-blocks/maxi-blocks/issues/4019#issuecomment-1367874399 ⚠️ 

2.
https://user-images.githubusercontent.com/46112160/210411460-e23f2d49-a400-4564-bcd8-4ce8c7d0f713.mp4

# Test checklist

**_ Front/Back Testing _**

-   [x] Reproduce videos
-   [x] Test if in other cases when attribute should/shouldn't disappear all works as expected

**_ Pre-Code Testing _**

-   [ ] Reproduce videos
-   [ ] Test if in other cases when attribute should/shouldn't disappear all works as expected 
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/3f2c0061-bf19-49b5-816d-312042720b05
1.2 point is not fixed

**Review by Marko64 — CHANGES_REQUESTED** [review]
Not sure if it's me, but I'm still getting the same from the first video:

https://user-images.githubusercontent.com/19425503/212916243-3a764af2-1a0a-4ad7-ade9-b3385e1abd52.mp4

**Review by Marko64 — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/9dac02b4-e21b-4079-919e-f31dacd4d5ae
if we set value for lower BP and then for higher, value for lower BP is overwriting

**Review by Olekrut — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
Simply beautiful, awesome job @Fybex 👏

**Review by elzadj — APPROVED** [review]

**Pull request merged**
