### PR TITLE
Issue-440

### PR DESCRIPTION
**Pull request by abder**
This PR aims to fix the issues described in #440. 

Notes: 
- autoplay has been fixed the way we discussed this on chat 
- videoControler have been removed 
- The spaces issue have been fixed in another PR #509 
- also the the media type has been fixed on clicking replace button

### CODE REVIEW

**Review by javadsamiee — COMMENTED** [review]
Good job

**Review by javadsamiee — COMMENTED** [review]
All of your translations needs text domain
`__('text', 'maxi-blocks')`

**Review by Naaaaiix — APPROVED** [review]
Well done, works perfectly! 👍

**Review by javadsamiee — APPROVED** [review]
Good job 👍

**Review by javadsamiee — COMMENTED** [review]
I saw these problems

Pasted_Image_10_1_20__10_02_AM

Pasted_Image_10_1_20__10_04_AM

Pasted_Image_10_1_20__10_04_AM

Pasted_Image_10_1_20__10_06_AM

**Review by javadsamiee — COMMENTED** [review]
It's better to use 0 instead of 0px in styles

**Pull request merged**
