### PR TITLE
Pagination for CL

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Adds a pagination option for CL in Row only (for now): 

screenshot-wordpress local-2024 02 08-15_00_42

screenshot-wordpress local-2024 02 08-15_07_22

# How Has This Been Tested?

Items per page must be equal to the amount of posts the pattern shows on the page.
Pagination in editor doesn't work as pagination, it's mostly for preview.
The styles are from P + hover and current from the SC colours.

- Please list other blocks we need the pagination for CL work with.
- Please list the style options we require, try to keep them simple. 
- Not sure where to add the style settings - SC (global for all) or per block?
- Not sure what to do with pagination for Media and Author types - should we hide it or maybe make it work? Theoretically, users may want pagination for them too :thinking: 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the pagination for posts with different combinations of settings
-   [ ] Test the pagination for woo products
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points in FSE

**_ Pre-Code Testing _**

-   [ ] Test the pagination for posts with different combinations of settings
-   [ ] Test the pagination for woo products
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points in FSE
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Added new public methods for dynamic content handling.
	- Introduced a new block type 'container-maxi' for enhanced block customization.
	- Implemented pagination styling for `.maxi-pagination` elements within blocks.
	- Added pagination controls and attributes for improved block customization.

- **Enhancements**
	- Optimized data accumulation and error handling in dynamic content rendering.
	- Improved pagination styles and colors for a more visually appealing user experience.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) row with pagination influence to width of blocks under
https://jam.dev/c/423b4dc7-4017-4821-930f-89788898526d
2) guess, if we are using styles for pagination from SC, then better to add separate typography styles inside CL tab. under pagination ( when it is enabled )
3) when we are clicking to 2, it should change first 3 products to 2nd 3 products at this page, no? Should not reference to another page... 
 https://jam.dev/c/04366986-7a52-4570-8705-25c80f1c3648
 4) Should depend on responsive width https://jam.dev/c/cb89fd8a-bebe-4589-a453-2df1d26aaa01
 Smth like it 
image
5) need to add some column-gap to "maxi-pagination"
6) i ve used woo from https://3devdemo.maxiblocks.com/woo-light-wl-pro-part-1/
Errors, that because it
image

**Comment by elzadj** [comment]
1. Could you give me the editor code, please?
2. Kkk, good idea, adding.
3. "Items per page must be equal to the amount of posts the pattern shows on the page." The number must be 3 here, not 4. Because you're showing 3 posts per page. When you add 4, it calculates the accumulator on the new page as ```$accumulator + $cl_pagination_per_page * ($pagination_page - 1)```, i.e. accumulator + 4, not accumulator + 3. And no, I can't guess that number automatically.
4. Ok, going to add something like this.
5. Adding the same way as 2
6. What's 633.js, where is it from? Please hover on the file and give me the full url. And maybe a jam video, if possible.

@Olekrut ^

**Comment by Olekrut** [comment]
https://jam.dev/c/6cb22c33-0465-4f14-b4ec-f915d498957b
[bug with pagination width.txt](https://github.com/maxi-blocks/maxi-blocks/files/14240359/bug.with.pagination.width.txt)
video for points 1 and 3

and some errors
image
image

but cant re-produce errors from point 6

**Comment by elzadj** [comment]
Pagination is buggy for plain links with ?p=123 in url, probably with other parameters too.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) pagination styles dont work for blog 97, because there CL enabled for column, need pagination for column ( guess, for group and container as well )

image
2) For current link not all styles work as well ( light and dark )
https://jam.dev/c/1edfce74-7669-48f0-b273-8c11526b509a
~3) link styles from SC dont work as well
image~
4) and check how should work pagination for blog 73
~5) Sometimes, i am using nowrap, if using fit-content for columns. Pagination div, should not be in the same block, 
image~

**Comment by elzadj** [comment]
> link styles from SC dont work as well
Should they? Why? These are not links inside a paragraph. No visited, no active (it has current). Not sure how to make them work when they are so different.

**Comment by elzadj** [comment]
- [ ] Media pagination
- [ ] Authors pagination
- [ ] Current link styles
- [ ] Sanitize all url strings
- [ ] Column pagination
- [ ] Group pagination
- [ ] Container pagination
- [ ] Check pagination for blog 73

**Comment by elzadj** [comment]
Blog 73:

screenshot-wordpress local-2024 02 19-16_24_51

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) would be good to add transition for hover
2) if we have a few rows with pagination on one page, posts are changing for all rows
https://jam.dev/c/e25d8114-1d78-4e08-ae4a-bb188e16722d
3) posts are changing, not correct by pagination if full amount of posts are not multiple of items per page 
https://jam.dev/c/49648145-9277-4d76-8bb5-43fc93444c1b
4) next and previous are disappearing earlier or later than should ( check video from point 3) 
5) pagination for container does not work 
https://jam.dev/c/81ef8fcb-6a96-40c4-805d-a16acaeb2bb8
[pagination container.txt](https://github.com/maxi-blocks/maxi-blocks/files/14336178/pagination.container.txt)
6) flexbox for pagination in single group looks not correct ( is not important )
image
7) Plain permalinks don't work yet
https://jam.dev/c/e51c92a8-949e-4452-a8dd-ee0943460884
8) Frontend - CL is not ok for Author, if hard, derive to new issue https://jam.dev/c/387d4fb8-9c70-4fce-8600-b998a3651a14

**Comment by elzadj** [comment]
1. Going to add css
2. That's how pagination works. We can't separate blog indexes on one page. 
3. That's how our CL works, unfortunately. We can cut the last posts and don't show them, or show the last post several times. I think cutting is better, but need to choose.
4. Save problem as 3
5. Fixing, let's also make it ```justify-content: space-around;``` by default, so it's not so wide?
6. Could you give me the code, please?
7. Sorry, what it has to do with the pagination at all? You need to reload the editor after you changed the permalinks, it's not AJAX, Gutenberg has no idea that you changed permalinks in another tab of your browser. Reload the editor, then open the new plain link it now shows, pagination will work:
Screenshot from 2024-02-21 13-03-49
8. Could you screenshot me your /wp-admin/users.php page, please? 

Thanks

**Comment by Olekrut** [comment]
6) just add any blog to single group and enable pagination
[pagination in the single group.txt](https://github.com/maxi-blocks/maxi-blocks/files/14359009/pagination.in.the.single.group.txt)
8) 
image

**Comment by elzadj** [comment]
@Olekrut Check now please, if authors are still broken, please give me the Gutenberg code, because (you guessed it), I can't re-create: 
screenshot-wordpress local-2024 02 22-15_53_01

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
