### PR TITLE
Navigation menus

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Add SC panel for global styles for Navigation block inside a Maxi container. 

screenshot-wordpress local-2024 01 29-15_41_59

# How Has This Been Tested?

Please reset your SC before testing ```wp.data.dispatch('maxiBlocks/style-cards').resetSC()```

and create a new custom SC.

Ignore failing tests.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test all the settings
-   [ ] Test responsive settings
-   [ ] Test in editor
-   [ ] Test in FSE
-   [ ] Test on frontend
- 
**_ Pre-Code Testing _**

-   [ ] Test all the settings
-   [ ] Test responsive settings
-   [ ] Test in editor
-   [ ] Test in FSE
-   [ ] Test on frontend
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Enhanced navigation handling within style cards, including support for nested navigation blocks.
	- Added new CSS rules for resetting margin properties in specific blocks.
	- Implemented dynamic loading and UI controls for navigation settings in style cards.
	- Improved handling of navigation menu visibility, including conditions for showing or hiding hamburger navigation.
- **Bug Fixes**
	- Fixed an issue where an error was not properly handled when retrieving terms, now returns an empty string in such cases.
- **Refactor**
	- Updated functions to include 'navigation' elements and handle additional margin and padding properties.
	- Enhanced selectors to support navigation-related style cards.

### CODE REVIEW

**Comment by elzadj** [comment]
Some questions:

1. Defaults for the desktop nav menu - I guess need to re-create the one from the psd, so we have less work with it later.
2. Defaults for mobile nav menu - do we want to change it by default? Like disable that underline hover that WP adds? 
3. Mobile menu breakpoint by default - 767px and down? See the prev. question - do we want to activate it by default?
4. What to do with people who already use a menu inside maxi container? Anyone from support @Marko64 ? I know sometimes people use nav menus in footer and sidebar. We can add a custom class to our nav menus even if they are inside maxi container, but then we need to tell people to add that class if they want the menu to be affected by SC. Not the best way. 
5. How to deal with people who use custom SC on the site. We can't just reset SCs, so I guess need a migrator to add new Nav settings.
6. Margin for menu items is not going to work, so I've added padding, but we can add margin to the whole menu, if required. 

Note: navigation block doesn't have custom css, but we can add them into the parent container. Again, not the best way, but it's an option.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) would be good to have ability to change arrow for submenu and arrow for link 
image
image
2) arrow gets colour from P but, guess it should get from link
3) would be good to add(overwrite) these settings 
image
4) would be good to add border styles as well, then we will have ability to add some interesting hovers by advanced CSS uses pallet colours
5) looks incorrect https://jam.dev/c/0ce5c89d-2c15-4e33-bfdd-acae74eaf9ba
6) ui 
image
7) need to add transition for link hover
8) check how looks menu on reponsive
image
9) would be good to have ability change colour for hamburger icon

**Comment by elzadj** [comment]
- [ ]  arrow colour the same as the menu item
- [ ] submenus z-index
- [ ] colour when Open on click
- [ ] transition for hover
- [ ] Burger colours

@Olekrut could you pls upload Gutenberg code of your testing page?

**Comment by elzadj** [comment]
6, 8 - adding z-index 10 to the parent container fixes it. I don't want to hard-code it because of our Container settings.

**Comment by elzadj** [comment]
@Olekrut done, please reset the SCs to see Mobile menu icon colour setting for the burger.

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) colour for sub menu link if enable open on click
[test nav.txt](https://github.com/maxi-blocks/maxi-blocks/files/14102885/test.nav.txt)
image
2) not very important
image
2.1) maybe possible to make some settings for sub-menu arrow - icon-size, line width
2.2) font-family influence to link arrow on backend but not on frontend
3) 
image
Typography should influence to hamburger words as well ( Menu and Close ), and would be good to separate them, because they can be differenced from links

**Comment by elzadj** [comment]
Going to fix colour and font, moved new settings to this issue (please add more to it, tx)

https://github.com/maxi-blocks/maxi-blocks/issues/5416

**Comment by elzadj** [comment]
@Olekrut fixed colour and fonts, please check

**Comment by elzadj** [comment]
Also fixed processing several navs on one page, now mobile settings work for all of them:

screenshot-wordpress local-2024 01 31-15_30_31

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/76558f16-e76c-4a8f-a336-d49b2b0e6d9b
when sub-menu is activated, colour should be like for hover in
 2) need to add our bg for sub menu, because Gutenberg`s colour will not be work with our SC. Not overwrite, just to make own

image

**Comment by elzadj** [comment]
@Olekrut added bg sum-menus options, please test.

**Review by Olekrut — APPROVED** [review]
Guess, possible work with it) Well done) 🥇

**Pull request merged**
