### PR TITLE
Small UI fixes

### PR DESCRIPTION
**Pull request by Rustam198804**
Fix issue #2324

### CODE REVIEW

**Review by kyrapieterse — APPROVED** [review]

**Review by elzadj — APPROVED** [review]
```data-name={lowerCase(item.label)}```

So if we rename something, the styles will break. Any ideas @Naaaaiix ?

**Review by Naaaaiix — COMMENTED** [review]
Well done @Rustam198804 👍

**Review by Alejandro9kgm — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Keep advancing, good job 😺 👍 

Most of the issues are related to CSS targets. There are 2 mainly things why we request to change it:
1. Basing CSS targets on `data-name`, which is finally the name of the tab, can be conflictive if in future we change the tabs label. If, for example, `dimensions` tab change its name to `abracadabra`, we'll need to change the CSS. If we can avoid it, is less things to think about and care in future 👍 
2. Every style should go inside its own component, and is important to use the components classes. This helps a lot when need to fix or improve the code.

Thanks for such a good job @Rustam198804 , keep pushing like that 💪

**Review by elzadj — APPROVED** [review]
@Rustam198804 
Found this, looks like a small bug: 

Add-New-Page-‹-Local-Wordpress-—-WordPress (3)
Add-New-Page-‹-Local-Wordpress-—-WordPress (2)

**Review by Naaaaiix — COMMENTED** [review]
Gorgeous 😺 

Just a last small thing to change, and will be ready.  Well done @Rustam198804 , good job and thanks for the patience 🙏 😄

**Review by Naaaaiix — APPROVED** [review]

**Pull request merged**
