### PR TITLE
Issue 3877 - Lists: items as inner blocks (list-item-maxi)

### LINKED ISSUE #3877: Text Maxi (List) update
With the WP 6.1 update, some functions have been deprecated. One of them is the `multiline` capacity that RichText was supporting that was at same time the base for our List feature on Text Maxi; it will be completely deprecated on WP 6.3, so for the moment we can still use it. But we need to re-think the whole block as the idea WP imposed is, instead of wrapping it on a RichText, is to have a 'list item' component (basically a `li` element) that we insert into a `list` wrapper (`ol` or `ul`) using InnerBlocks. The main idea can be seen on [this PR](https://github.com/WordPress/gutenberg/pull/42711), and I think the critic point and where we can check and learn is in [this concrete file diff](https://github.com/WordPress/gutenberg/pull/42711/files#diff-99bb126c574fb4790a60e7b6cf372c8a8bce3114f8a9740d0f92e47e74238724).

Want to take advantage of this commented Gutenberg PR to invite you checking [this hook](https://github.com/WordPress/gutenberg/blob/30c6b5b8183c7f0a26f22eba1a62f690206d1da6/packages/block-library/src/list/edit.js#L48-L73) they used for migrator. Can be an interesting for future migrators.

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #3877 

# How Has This Been Tested?
Each list item now is a separate block - `list item maxi`. I've checked if :
- all previous functionality works as before
- block settings like border, transitions, transform, etc work as expected
- it's more convenient to use and most of remained wp 6.4 bugs disappeared
- old templates migrate without problems

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test if basic list functionalities work
-   [ ] Test if switching between paragraph and ordered/unordered lists works
-   [ ] Test if it's possible to override styles from text-maxi in list-item block
-   [ ] Test if set/override settings from text-maxi works on responsive in list-item block
-   [ ] Test if links/custom format in list-item work
-   [ ] Test if text-maxi paragraph works as it worked before
-   [ ] Test if old patterns migrate without issues
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test if basic list functionalities work
-   [ ] Test if switching between paragraph and ordered/unordered lists works
-   [ ] Test if it's possible to override styles from text-maxi in list-item block
-   [ ] Test if set/override settings from text-maxi works on responsive in list-item block
-   [ ] Test if links/custom format in list-item work
-   [ ] Test if text-maxi paragraph works as it worked before
-   [ ] Test if old patterns migrate without issues
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Introduced advanced block attributes for list items, including typography, link styles, hover effects, and more.
	- Added an Inspector component for enhanced block settings and controls.
	- Implemented dynamic behavior for bottom gap display in text components.
	- Added new list handling components and logic for improved content management.
- **Enhancements**
	- Improved typography attribute generation for more customizable text styling.
	- Streamlined logic in toolbar components for better maintainability and efficiency.
- **Bug Fixes**
	- Adjusted e2e test cases for more accurate testing of text and list features.
- **Refactor**
	- Optimized block disable logic in the toolbar for enhanced performance.
	- Updated context usage and refactored content handling in toolbar components.
	- Simplified format value generation for text formats.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/6b5bfffd-3e71-4e86-9e10-4ac5dd53e826
[list 1.txt](https://github.com/maxi-blocks/maxi-blocks/files/14460355/list.1.txt)
old templates dont work correct
2) https://jam.dev/c/6f548a8e-1183-44ad-b517-eaa816e5815e
for new block as well , oi and ui, i dont see markers at all

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) guess, need to hide bottom-gap for list-items
https://jam.dev/c/d39a7b92-8932-4784-8818-a61de6d7c742
2) check topography settings for text list and list items, some of them are not working correct
https://jam.dev/c/d8a11c5e-775f-4813-9c39-39a06b1a567a
3) Default bottom-gap is not displaying on frontend
image
4) is possible to back ability - make 2nd, 3rd.... levels for ol ?
5) if make in one li text with <br> then change to P and again to list. > It is creating new li
https://jam.dev/c/77a74de1-cf19-4c0b-946a-becb25c22795

**Comment by kyrapieterse** [comment]
make a separate issue for anything we dont 100% need right now

**Comment by Fybex** [comment]
UPD: bottom gap is removed from list-item and is hidden in text-maxi when it's in list mode.

Created https://github.com/maxi-blocks/maxi-blocks/issues/5479 (point 4 request)

Give me list of needed to fix settings if there's any left 🙏
Word-spacing and text-indent work as expected, don't they?

**Review by Olekrut — APPROVED** [review]

**Comment by elzadj** [comment]
Great work! Please check the tests and what's with ```list-style-type: decimal;``` in them, thanks.

**Review by elzadj — APPROVED** [review]

**Pull request merged**
