### PR TITLE
Issue 4418 - replace vw and vh units with px units

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
vw and vh units are dependent on viewport size, which isn't changing on editor when we change a breakpoint, so now these units are replaced with px values which are calculated in our code.

vw calculations are based on breakpoint sizes instead of actual width of the editor content, because the tests return different vw sizes on different environments.

Fixes #4418 

# How Has This Been Tested?
Checked that vw and vh values look same on backend and frontend.

# Test checklist

**_Front/Back Testing_**

-   [ ] Check that vw and vh values look right on editor.
-   [ ] Check that vw and vh units are not replaced on frontend.

**_Pre-Code Testing_**

-   [ ] Check that vw and vh values look right on editor.
-   [ ] Check that vw and vh units are not replaced on frontend.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
Different sizes
backend
image
frontend
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/4d419186-79a7-4bdd-8df4-9c55e8493980

Wrong size for VW on XXL ( backend )

**Review by Olekrut — CHANGES_REQUESTED** [review]
XXL - difference = 30px for text with 16vw
backend
image
frontend
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
yes, perfect now, if look from base BP, but it is not good on backend if you look to not base BP

**Review by Olekrut — APPROVED** [review]

**Review by darimshlk — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
👏

**Pull request merged**
