### PR TITLE
Repeater: unique id

### LINKED ISSUE #5306: DC does not work correct with repeater
### Description

DC does not work correct with repeater

### Step-by-step reproduction instructions

1) create row ( 2 col )
2) add to first col - DC text and buttons ( enable links )
3) enable repeater
4) check frontend ( links are not correct as well )

### Screenshots, screen recording, code snippet

https://jam.dev/c/c3b35b25-a2f9-4261-aa9e-d6d51a6aacfd

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Fixes unique ID generation for repeater and broken blocks after you standardize the columns:

Screenshot from 2023-12-07 18-03-35

Known issues: repeated buttons styles start to change only after you reload the editor.

Fixes #5306 

# How Has This Been Tested?

Test repeater with and without standardizing the columns. Create container / row etc from 0, and try with imported patterns too.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Bug Fixes**
  - Enhanced error handling in the maxi-block extension to prevent runtime errors when `currentBlock` is undefined.
  - Improved validation logic in the repeater extension to ensure the existence of `column.clientId` before proceeding with structure validation.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
not sure, that is related, but similar to original issue, https://jam.dev/c/0589892b-92b0-4c4c-8da3-ae1f2eca5b84
if change accumulation, links for svg and group are not changing

**Comment by elzadj** [comment]
> not sure, that is related, but similar to original issue, https://jam.dev/c/0589892b-92b0-4c4c-8da3-ae1f2eca5b84 if change accumulation, links for svg and group are not changing

Could you please share the editor code?

**Comment by Olekrut** [comment]
> > not sure, that is related, but similar to original issue, https://jam.dev/c/0589892b-92b0-4c4c-8da3-ae1f2eca5b84 if change accumulation, links for svg and group are not changing
> 
> Could you please share the editor code?

[similar issue.txt](https://github.com/maxi-blocks/maxi-blocks/files/13613519/similar.issue.txt)

**Comment by elzadj** [comment]
@Olekrut not related to the IDs at all, made a new issue, could we please push this one? Thanks.

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
