### PR TITLE
Backend speed

### PR DESCRIPTION
**Pull request by elzadj**
# Description

What was addressed:

- Initial load / rendering speed in the Editor when you open a page in it
- Toolbar and breadcrumbs appearance speed when you click a block
- Hover styles when you hover something in the editor
- Showing the green block inserted on hover 
- Slowdown when you have a page opened in the editor for a long time
-  Slow render when you paste code as text
- Slow render when you use Ctrl / Ctrl
- Cloud modal

# How Has This Been Tested?

**Important**: Please do ```npm ci --legacy-peer-deps```, then ```npm build```, and clear your cache after that. 
Note: first load after that could be slow. 

Better test with a comparison with master on a site somewhere.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Added a new dependency for improved linting.
	- Updated existing dependencies to enhance compatibility.
- **Bug Fixes**
	- Improved error handling to prevent runtime errors in component rendering.
- **Refactor**
	- Simplified import statements across multiple components for better readability and maintainability.
	- Enhanced caching mechanisms in data retrieval functions for improved performance.
	- Extracted utility functions to improve readability and reusability.
	- Redesigned animations for smoother visual effects and better user interface responsiveness.
	- Redefined functions and updated dependencies in higher-order components for enhanced responsiveness.
- **Chores**
	- Removed unused dependencies to streamline the project.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/a216f7b9-180e-4115-b8d7-fb7989b4c0f3
loading of page after refresh looks the same 
2) https://jam.dev/c/8eb0d11c-1125-4b7f-937d-24dc2dc86734
Toolbar looks better, but time after select is the same or even a bit longer.
Hover, select after swap browser's tabs looks better.
 https://jam.dev/c/ccfc9698-60fa-4ce9-af82-08bf2238d6e4

**Comment by elzadj** [comment]
@Olekrut 
1. Please try with Children’s Party CSPY-PRO-01, here are my tests:
master:

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.08.02-18_42_43.webm](https://github.com/user-attachments/assets/cbbd1e0e-3aa7-46b6-8a13-421b174bd806)

this branch:

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.08.02-18_45_19.webm](https://github.com/user-attachments/assets/b077cdfd-5fd4-470f-8017-a707b5d88c4c)

**Comment by elzadj** [comment]
@Olekrut let's try this one

Important: Please do ```npm ci --legacy-peer-deps```, then ```npm build``` (do not do npm run start), and clear your cache after that (use 'empty cache and reload' in the editor, then close all pages on local / site, and open them again).

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/7d434c74-a267-4945-851f-60f3a9ff8f9d
Cleared cache before on local and test site.
Was tested speed of select after change tab.
Looks a bit faster, but it is +/-1sec.
About reloading of page with CSYP-PRO-01:
test site (with branch) and master = 45sec
local ( with branch ) = 1min 40sec, so maybe everything is not so bad as earlier, only local is weird

2) https://jam.dev/c/aee47191-c25c-4556-a91f-caa0b7cf87bc
i like how works toolbar now. Is possible to make the same with row schemes (column settings)?

**Comment by elzadj** [comment]
- [ ] more DC optimizations
- [ ] The columns chooser in the sidebar 
- [ ] Ctrl-c / Ctrl speed (also render speed when you switch from the Code Editor to the Visual one)
- [ ] Cloud speed
- [ ] Try to move fonts json outside the js code as a json file, maybe the default DC too.

**Review by Olekrut — CHANGES_REQUESTED** [review]
it is not end, but i see real difference, DC,/CL and in general Csyp-PRO-01   ( 14 sec )
I see after that some freezes 5sec yet so 19 sec for full loading, but it is much much much
 better

**Comment by elzadj** [comment]
@Olekrut please check the Cloud modal animation, weird visual artefacts (like on the video) should be fixed

[screencast-maxithemedev.dev600.com-2024.08.09-17_28_24.webm](https://github.com/user-attachments/assets/846406ef-803e-42ef-9a62-97e42de88f34)

**Review by Olekrut — APPROVED** [review]
Only 2 UI notices, but guess, it is not important.
1) https://jam.dev/c/44a88cfa-bc11-49f5-b8c0-446a529300de
weird loading
image
2) https://jam.dev/c/8b98b432-af37-450c-8b1a-09f25bb03368
blinking of row scheme

**Comment by elzadj** [comment]
> Only 2 UI notices, but guess, it is not important.

1. I've fixed it in the last commit, please do git pull, ```npm ci --legacy-peer-deps```, then ```npm build```, and clear your cache after that.
@myroslavve @Fybex do you see this bug too, or not? 
2. It's re-renders when you change the value, there is no a quick fix for that, unfortunately.

**Comment by myroslavve** [comment]
> > Only 2 UI notices, but guess, it is not important.
> 
> 1. I've fixed it in the last commit, please do git pull, `npm ci --legacy-peer-deps`, then `npm build`, and clear your cache after that.

I can reproduce the blinking, but only after scrolling for a while. Or using CPU slowdown in devtools, it appears almost immediately in this case.

**Comment by elzadj** [comment]
@Olekrut @myroslavve try now please. Not sure if I can 100% fix it for slow cpu tho.

**Comment by Olekrut** [comment]
https://jam.dev/c/7aa41a00-4038-4654-b752-8a383f8d1e3d
for me looks better now

**Pull request merged**
