### PR TITLE
Issue 4312 - Custom CSS label and button

### PR DESCRIPTION
**Pull request by Marko64**
Fixes #4312 

**_ Front/Back Testing _**

-   [ ] Add a background hover and check if the custom CSS label for it looks good and doesn't affect the button.

**_ Pre-Code Testing _**

-   [ ] Add a background hover and check if the custom CSS label for it looks good and doesn't affect the button.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
image

**Review by Naaaaiix — COMMENTED** [review]
I suggest nesting the title and the `validate` button into a `div` element displayed with flexbox and then play with it. Flexbox is much more organic and adapts better to any device; this fix might have issues on smaller screens 👍

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) I guess, better to remove margin-top
image

2) is not related with this issue but - 
 is it ok, that sidebar for S and XS sidebar is full width?
 
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
need to add space between label and button. For example padding-right:10px; to maxi-base-control__label

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
