### PR TITLE
Fixes for WP 6.5 RC2

### LINKED ISSUE #5485: Double Cloud Block when adding from Toolbar on Custom Post Type Single Template
### Description

Click on Template library from the toolbar adds the block 2 times, so it looks weird. For now noticed only on Single Item: CPT Templates.

screenshot-wordpress local-2024 03 05-18_20_56

### Step-by-step reproduction instructions

1. Add CPT from ACF, default Movies is fine.
2. Go too FSE - Add Template - choose 'Single item: your CPT'
3. Click Template library from the toolbar.

### Screenshots, screen recording, code snippet

_No response_

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### LINKED ISSUE #5488: WordPress 6.5
Test it deep

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Fixes (mostly) deprecations and previews in FSE. Full list is in the issue.

Fixes https://github.com/maxi-blocks/maxi-blocks/issues/5488 
Fixes #5485 

# How Has This Been Tested?

Please test responsive toolbar and switching breakpoints (deprecations are mostly about that). Test not only on WP 6.5 RC2, but on 6.4.3 too.

screenshot-wordpress local-2024 03 14-17_04_17

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test Responsive Toolbar / breakpoints on page editor
-   [ ] Test Responsive Toolbar / breakpoints in FSE
-   [ ] Check pattern previews (FSE and block inserter)
-   [ ] Check that creation of a new Template in FSE doesn't show a fatal error
-   [ ] Same 1-4 points for WP 6.4.3 too

**_ Pre-Code Testing _**

-   [ ] Test Responsive Toolbar / breakpoints on page editor
-   [ ] Test Responsive Toolbar / breakpoints in FSE
-   [ ] Check pattern previews (FSE and block inserter)
-   [ ] Check that creation of a new Template in FSE doesn't show a fatal error
-   [ ] Same 1-4 points for WP 6.4.3 too
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Enhanced fallback mechanisms for font loading in blocks.
	- Added new styling options for block elements.
	- Improved responsive design capabilities in the editor.

- **Refactor**
	- Optimized logic for responsive selector component.
	- Streamlined device type setting and retrieval in the editor's store.

- **Style**
	- Updated aspect-ratio values and added styles for pattern preview grid cards.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
There is adding extra template library block every time if add by toolbar
https://jam.dev/c/73383d63-8ab2-451f-973d-b5d0a39fa953

**Comment by elzadj** [comment]
> There is adding extra template library block every time if add by toolbar https://jam.dev/c/73383d63-8ab2-451f-973d-b5d0a39fa953

https://github.com/maxi-blocks/maxi-blocks/issues/5485

@Olekrut is it not the same on 6.4.3? Or do we have it on additional Templates on 6.5?

**Comment by Olekrut** [comment]
Looks like library is working slower on this brunch, 6.4.3 and 6.5-rc2
https://jam.dev/c/4cd0e511-1a78-4aa8-85a4-1b55a50ddf95

**Comment by elzadj** [comment]
@Olekrut please check Template library from the toolbar now. In all places you can think of, and both on 6.5 and 6.4.3

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
