### PR TITLE
Issue 5482 - fix DC link migrator

### LINKED ISSUE #5407: Button. Author's DC link
### Description

1) Displaying is wrong on backend
2) we don't have settings for links ( colours, and impossible to remove underline) on frontend
3) DC link works only on button's text ( link doesn`t work on icon and button area )

### Step-by-step reproduction instructions

1) create button
2) set Author
3) Enable Author's DC link

### Screenshots, screen recording, code snippet

1) image
2) image

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### LINKED ISSUE #5420: Extra link`s toggles are not working for DC text-block
### Description

Extra link`s toggles are not working for text-blocks where DC is enabled

### Step-by-step reproduction instructions

1) create Text block
2) Enable DC
3) Enable DC link 
4) try to enable any extra toggle for link under

### Screenshots, screen recording, code snippet

https://jam.dev/c/825de117-d071-40c4-a115-e87542ac3681
image

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### LINKED ISSUE #5482: DC link is removing from old DC blocks
### Description

 If load blog older 24 jan, DC link will be removed for authors, cats and tags. 
image
Probably, related with https://github.com/maxi-blocks/maxi-blocks/pull/5459

### Step-by-step reproduction instructions

1) Chose brunch issue-5407
2) pick blog loaded to library earlier 24 jan ( PBGL-PRO-101 - example )
3) check DC link for author, cat ot tag

### Screenshots, screen recording, code snippet

https://jam.dev/c/204fe978-3a70-4b85-9191-a527fa12c5fd

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
There was a conflict between DC link and DC class (https://github.com/maxi-blocks/maxi-blocks/pull/5223) migrators, fixed it.

Fixes #5482 

# How Has This Been Tested?
Checked that DC links for author/tags/categories still work, and that migrator works for different patterns. Also checked that migrator works for https://github.com/maxi-blocks/maxi-blocks/pull/5223, since it was changed (using [this code editor](https://github.com/maxi-blocks/maxi-blocks/files/14526498/code_editor.txt))

# Test checklist

**_ Front/Back Testing _**

-   [x] Test that DC links for author/tags/categories still work.
-   [x] Check migrator for DC links, with patterns from the issue.
-   [x] Check that migrator for DC hide option works with [this code editor](https://github.com/maxi-blocks/maxi-blocks/files/14526498/code_editor.txt) or with old patterns (older than January 2nd).

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Introduced enhanced link settings for dynamic content, improving link rendering and target handling.
	- Added new attributes for dynamic content links, including `dc-link-target` and `dc-link-status`, for better link management.
	- Enhanced dynamic content components with new properties to support improved link handling.
	- Streamlined dynamic content logic for taxonomy content retrieval and user link targeting.
- **Refactor**
	- Refactored link handling across various components and extensions for improved efficiency and maintainability.
	- Updated attribute validation logic to include new link target options.
- **Bug Fixes**
	- Fixed issues related to dynamic content link rendering and attribute handling.
- **Style**
	- Adjusted dynamic content and link styling defaults and migrators to align with new link handling features.
- **Chores**
	- Removed unused link fields and labels to clean up the codebase.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/963c6079-d33b-4472-87b0-f513fb284904
it does not work, for DC loaded before change brunch
if load after change, everything is ok

**Comment by myroslavve** [comment]
> https://jam.dev/c/963c6079-d33b-4472-87b0-f513fb284904 it does not work, for DC loaded before change brunch if load after change, everything is ok

exactly, migrator was not working correct, so if you loaded pattern before this fix it would lose its link attributes. But since we did not include the broken migrator with the public update, people won't have this problem so no need to fix this.

**Comment by myroslavve** [comment]
> > https://jam.dev/c/963c6079-d33b-4472-87b0-f513fb284904 it does not work, for DC loaded before change brunch if load after change, everything is ok
> 
> exactly, migrator was not working correct, so if you loaded pattern before this fix it would lose its link attributes. But since we did not include the broken migrator with the public update, people won't have this problem so no need to fix this.

Sorry, misunderstood your comment, I see now that patterns loaded on master are broken.

**Comment by myroslavve** [comment]
> https://jam.dev/c/963c6079-d33b-4472-87b0-f513fb284904 it does not work, for DC loaded before change brunch if load after change, everything is ok

Was happening because migrator didn't include last version of blocks (1.7.3) as valid for migration, updated.

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
