### PR TITLE
Issue 4377 - Margin indicator overlapping

### LINKED ISSUE #4377: Margin indicator is overlapping elements
### Description

Margin indicator is overlapping elements inside container

### Step-by-step reproduction instructions

1) create Container
2) add margins
3) create inside container block with BG colour
4) move this block to indicators with help transform:translate
5) hover margin indicator

### Screenshots, screen recording, code snippet

image

### URL and/or Code editor

[overlapping.txt](https://github.com/maxi-blocks/maxi-blocks/files/10745308/overlapping.txt)

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Marko64**
Fixes #4377 

# How Has This Been Tested?

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Improved block editing experience with conditional margin indicators based on full-width settings.

- **Style**
  - Updated z-index for better layering and visibility of block indicators in the editor.

- **Refactor**
  - Introduced new functions for enhanced margin control logic in axis controls.
  - Added conditions to refine the application of margin adjustments.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
@Marko64 sorry for confuse 
i thought, margin left/right will not be added if container is full-width
but if they will be added in any case then need to add indicators for margin left/right as well
image

**Comment by kyrapieterse** [comment]
MVP guys - this is stuck for month now

Full width no side margins. Seems obvious
If its not full width and there are side margins let's show them. This also seems obvious

**Comment by Marko64** [comment]
Ok, killing side margins for a full width container completely then. Problem solved lol

**Comment by Marko64** [comment]
Yes, side margins will still be possible to add for containers that are not full-width.

**Comment by elzadj** [comment]
Need to check the tests results - margins left - right were removed. If it's expected - need to update snapshots, if not expected - check what happened.

**Comment by Olekrut** [comment]
And Row has full-width toggle as well, so maybe need to do the same for row?

**Comment by Marko64** [comment]
> Need to check the tests results - margins left - right were removed. If it's expected - need to update snapshots, if not expected - check what happened.

I can't run the indicator test because I still get the timeout error for the container:

    TimeoutError: waiting for selector `.maxi-container-block` failed: timeout 30000ms exceeded

**Review by Olekrut — APPROVED** [review]
it is ok for now, but if somebody will ask about it, you need to know

if disable full-width > set left/right margin > enable full-width > impossible to change left/right margin
https://jam.dev/c/363409da-06e2-45a2-8473-ffb1e766ccca

**Review by elzadj — APPROVED** [review]

**Pull request merged**
