### PR TITLE
Issue 820

### PR DESCRIPTION
**Pull request by javadsamiee**
Minor fix

### CODE REVIEW

**Review by elzadj — CHANGES_REQUESTED** [review]
Backend - fixed, thanks.
Frontend - nope, re-check it, please.

**Review by elzadj — CHANGES_REQUESTED** [review]
The 'Image Dimensions - Width' setting conflicts with this style.

**Review by Naaaaiix — COMMENTED** [review]
Tested this branch and master. Differences:
1. On master, I have no problem with alignments for Image Maxi.
2. On this branch, changing the width doesn't have effect on frontend

👍

**Review by Naaaaiix — APPROVED** [review]
Works good for me 👍 😸

**Review by elzadj — APPROVED** [review]

**Pull request merged**
