### PR TITLE
Update WP environment to 6.1

### PR DESCRIPTION
**Pull request by Naaaaiix**
# Description

This PR aims to give both WP6.0 and WP6.1 compatibility for MaxiBlocks. The good news is that Maxi has a good resilience on updates, as it just broke in a singular place and hasn't been our fault. The main error we are receiving are coming from Popover WP native component that has been modified and its deprecations times hasn't been followed as it should. It was programmed to deprecate some props we were using like `getAnchorRect` on WP 6.3, but they already did it on 6.1 by mistake. Here's the original [Gutenberg PR]() and it says:

Captura de Pantalla 2022-11-04 a las 11 31 39

For winning this battle of having support for both WP versions, Popover instances have been modified to run under Gutenberg version and some List methods have been implemented as they were on previous versions of RichText to work the same on WP 6.0 and WP 6.1. Also updated some tests 👍 

# How Has This Been Tested?

Checked different patterns and particularly checked Popovers like: Toolbar, CaptionToolbar, PopoverButton (the upload button for Image and Icon Maxi), IconToolbar and BlockInserter (appenders) on both version: WP 6.0 and WP 6.1. Also, for both WP versions, tested Text Maxi as a list and checked from toolbar the indent and outdent actions.

If you're currently running WP 6.0 on your local, test this branch with it and once you want to jump to WP6.1, write on your terminal `npm run wp-env start` and that version will be automatically downloaded and installed.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test different Popovers on WP 6.0
- [x] Test list indent/outdent on WP 6.0
- [x] Test different Popovers on WP 6.1
- [x] Test list indent/outdent on WP 6.1
- [x] Look for new functional/style issues on WP 6.1

**_ Pre-Code Testing _**

-   [ ] Test different Popovers on WP 6.0
- [ ] Test list indent/outdent on WP 6.0
- [ ] Test different Popovers on WP 6.1
- [ ] Test list indent/outdent on WP 6.1
- [ ] Look for new functional/style issues on WP 6.1
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — APPROVED** [review]
In addition tested: 
- Inserting patterns
- Style cards
- Responsive
- Main components (background, sizing, spacing, border, box shadow...)

All seems good.

**Review by elzadj — APPROVED** [review]

**Review by Olekrut — APPROVED** [review]

**Review by kyrapieterse — APPROVED** [review]
go go go

**Review by Fybex — CHANGES_REQUESTED** [review]
1. Looks a bit off, right?

image

2. #3089 isn't working
image

**Review by myroslavve — CHANGES_REQUESTED** [review]
Toolbar doesn't move when I move block on wp 6.1

https://user-images.githubusercontent.com/53875005/199984859-2db41734-c17c-4c10-a033-09f7ad03dfdc.mp4

**Review by myroslavve — APPROVED** [review]

**Review by moroz-art-dev — APPROVED** [review]

**Review by Fybex — APPROVED** [review]

**Pull request merged**
