### PR TITLE
Issue 3948 toolbar spacing settings

### PR DESCRIPTION
**Pull request by Marko64**
Text block margin separated to top margin and bottom margin as per design:
[toolbar-1.pdf](https://github.com/maxi-blocks/maxi-blocks/files/10047216/toolbar-1.pdf)
Note: To be consistent with the sidebar settings, I kept all four sides margin unless you separate it first in the sidebar.

I didn't separate padding, border and box-shadow, because it's not what we have in our design. 

Fixes #3948

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the text block margin in the toolbar. Try with or without the margin axis separated in the sidebar.

**_ Pre-Code Testing _**

-   [x] Test the text block margin in the toolbar. Try with or without the margin axis separated in the sidebar.
-   [x] Check no commented code and no unnecessary imports
-   [x] Standards of the project have been followed
-   [x] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
image

image

**Review by Olekrut — CHANGES_REQUESTED** [review]
1)

[values in toolbar.webm](https://user-images.githubusercontent.com/88893350/203951913-3326d3b3-2583-4ee1-9dee-e713f6381f28.webm)

image
image
image



2) overlapping ( toolbar should go down when touch to interface-interface-skeleton__header
image

**Review by Naaaaiix — CHANGES_REQUESTED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
With a different breakpoint selected, the toolbar shows base as the selected one. Check on sidebar XXL is selected and in toolbar XL:

Captura de Pantalla 2022-12-07 a las 20 27 20

**Review by Olekrut — COMMENTED** [review]
much better!!!) IS it ok, that values invisible on responsive ( can see only changed) is it on purpose?
https://jam.dev/c/208bf36c-b7a1-4a1f-b526-296b4fdc5a04

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/efcacd0b-fa30-41c4-8204-9731feb65816
units are not working with the same value on responsive

**Review by Naaaaiix — APPROVED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Ups....
Captura de Pantalla 2022-12-29 a las 9 24 14

**Review by Naaaaiix — APPROVED** [review]
Sorry @Marko64, it's good; not sure why it rendered the inputs like that on my side 👍

**Review by Olekrut — APPROVED** [review]

**Review by Fybex — APPROVED** [review]

**Pull request merged**
