### PR TITLE
Issue 3605 - Generating new customLabel

### PR DESCRIPTION
**Pull request by blockchain-web-mobile-dev**
…D is repeated.

# Description

Generating new customLabel by combining with origin customLabel and new uniqueID when uniqueID is repeated.

image

UPD by @Fybex:
- after meeting with @Naaaaiix, decided to simplify custom `customLabel` change on duplication. In short: MVP. Idea with count index for custom `customLabel` uses a lot of recourses and doesn't work correctly with duplication of multiply blocks without reconsidering how we change `uniqueID` and `customLabel` on duplication process. About new method, for example, if block have `customLabel: 'Custom name'`, then it will be modified in duplicated block to `customLabel: 'Custom name_${uniqueIDNumber}`, if `uniqueID: 'button-maxi-6'`, then `customLabel: Custom name_6`.
- also removed old check if `uniqueID` is unique in `withAttributes` HOC ⚠️ Checked, looks like it is no longer needed, check it carefully on the review @all
- modified `getIsUniqueIDRepeated`, didn't cover one case, fixed it and wrote test to ensure

Fixes #3605

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — APPROVED** [review]

**Review by Fybex — CHANGES_REQUESTED** [review]
The code is fine, but check out [Environment, standards and habits](https://github.com/maxi-blocks/maxi-blocks/wiki/Environment,-standards-and-habits). You must have Prettier extension installed, it will help you with code formatting. After installing it, open all the files you have changed and save them again, Prettier will prettify them 👍

**Review by Fybex — APPROVED** [review]
Good job 😄

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Not sure if this is what we should expect:

https://user-images.githubusercontent.com/50477222/192773822-7f82d5a7-a6c2-4339-9a68-4178e3a26e19.mp4

I think it would be more correct that:
1. In case the `cusomLabel` hasn't been changed, just add a `+1` to the last number
2. In case we duplicate a block with a changed `customLabel` like `test-block`, the duplicated should be `test-block_1`, and if it's duplicate again `test-block_2`, not `test-block_1_2`

🤔

**Review by Naaaaiix — COMMENTED** [review]
Mmmmmmhhh... not sure if this is expected 🤔 

https://user-images.githubusercontent.com/50477222/193256850-4c564c93-763e-4142-851d-989f0cea9b74.mp4

**Review by Olekrut — CHANGES_REQUESTED** [review]
[not correct.webm](https://user-images.githubusercontent.com/88893350/204083999-75283dab-b17d-4b42-b799-7f25e964ba91.webm)

better, but
it is not working correct yet, if duplicate pattern

**Review by Naaaaiix — COMMENTED** [review]
To ensure a better understanding of the functionality and its circumstances, and also to keep a better trace of the issues and future fixes, I recommend adding unit tests for `getCustomLabel` 👍

**Review by Naaaaiix — APPROVED** [review]
Good job @Fybex, let's see if we finally close this long PR lol

> also removed old check if uniqueID is unique in withAttributes HOC

Been meditating about it for few minutes, and tested a bit, and seems is good. What can scape to that old condition should be fixed on `maxiBlocksComponent.uniqueIDChecker` method 🤔

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
