### PR TITLE
Issue 4687 - Context Loop

### PR DESCRIPTION
**Pull request by Fybex**
# Description

⚠️ #4647 was merged in this branch, so we should merge #4647 first ⚠️ 

Fixes #4687 

Context Loop logic overview:
1. Context loop is available from sidebar (advanced) and toolbar for: container, row, column and group-maxi.
2. Value inheriting: between from higher context loop block to lower context loop or DC block, value inherits. On change value on lower block, inheriting from higher block will stop.

https://user-images.githubusercontent.com/46112160/230653993-082cb0f6-9e7b-4888-be8a-874e09094d68.mp4

3. By enabling context loop on one block, all nested blocks (which support context loop) will be enabled as well by default. (you can see it in video from second point, I've activated context loop for container and it became activated for row and columns, but the blocks as text did not have DC activated)
4. It's impossible to set field, author id and other similar options in context loop. It's only possible as previously from DC. For a better understanding of available context loop options, you can check schema for each block: https://docs.google.com/drawings/d/1oC_rF3x-XyHLrTRAFd5aDm2KS-MA-o6rpJ6NUErcojI/edit
5. Accumulator option which was added in #4662 have special logic for columns. The first column has the same accumulator as the parent row. Second column have accumulator = row accumulator + 1, third = row accumulator + 2. All accumulators can be overwritten as any other option (concept 2) 

https://user-images.githubusercontent.com/46112160/230654641-7241e12d-99cb-4294-998f-acd788034405.mp4

P.S. Person 1, 2, 3 - pages, which was created for test.

P.S. It is also recommended to watch a preview video from the issue: https://github.com/maxi-blocks/maxi-blocks/issues/4687#issue-1655989690

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the context loop + dc
-   [ ] Check that the context loop + dc work on frontend
-   [ ] Test the dc without context loop
-   [ ] Check that the dc work on frontend
-   [ ] Same 1, 3 points for the toolbar

**_ Pre-Code Testing _**

-   [ ] Test the context loop + dc
-   [ ] Check that the context loop + dc work on frontend
-   [ ] Test the dc without context loop
-   [ ] Check that the dc work on frontend
-   [ ] Same 1, 3 points for the toolbar
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

### Summary
📝🚀🎨

This pull request adds and updates features and tests for the dynamic content blocks in the maxi-blocks plugin. It adds dynamic content support to the button maxi block, and adds new fields for the categories and tags of the post or page. It also adds a new feature called context loop, which allows the dynamic content blocks to inherit the settings from their parent blocks. It updates the logic and the signature of some functions in the `core/class-maxi-dynamic-content.php` and `core/class-maxi-styles.php` files. It adds and updates e2e tests for the dynamic content and the context loop features in the `e2e-tests/components` folder.

> _We're coding the dynamic content blocks_
> _We're testing them with e2e mocks_
> _We're heaving on the `custom_meta` function_
> _And sailing with the `context_loop` junction_

### Walkthrough
*  Add and update the dynamic content attributes for the button maxi, text maxi, and image maxi blocks ([link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72R29-R157), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72R167), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72R173), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72R179))
*  Add a new dependency to the `core/class-maxi-dynamic-content.php` file, which is the `core/class-maxi-styles.php` file, to get the custom meta data for the dynamic content blocks ([link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72R2))
*  Add a new logic to the `render_dc` function in the `core/class-maxi-dynamic-content.php` file, which is to get the custom data for the dynamic content from the `MaxiBlocks_Styles` class and use it to get the context loop settings for the dynamic content blocks ([link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72R192-R208))
*  Add a new logic to the `get_post_or_page_content` function in the `core/class-maxi-dynamic-content.php` file, which is to handle the dynamic content fields for the post or page categories and tags, and to format them as links or plain text depending on the attributes ([link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72R487-R488), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72R527-R549))
*  Add a new set of functions to the `core/class-maxi-dynamic-content.php` file, which are used to get the final values for the dynamic content attributes, by combining the attributes, context loop, and defaults arrays, and by using callbacks for some attributes ([link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72R754-R829))
*  Fix some typos and conditions in the `core/class-maxi-dynamic-content.php` file, which are related to the default value and the condition for the `dc-relation` attribute ([link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72L113-R263), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72L156-R306), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72L222-R372), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72L243-R393), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-af3e709c2c6b8e084fa9f907dcee2d8e2e9a69a642c995aae3b858405b5a2a72L263-R413))
*  Update the signature of the `custom_meta` function in the `core/class-maxi-styles.php` file, which is used to get the custom meta data for the dynamic content blocks, to make the `$is_template` parameter optional and to set its default value to `false` ([link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-b7ff34f9cedb3e28404133fc4bc88e7754790b35921ab3041415cd47a975087eL523-R523))
*  Update the `src/blocks/button-maxi/edit.js` file, which contains the edit component for the button maxi block, to add a new dependency, a new static property, a new getter method, and a new logic to use the `getDCValues` function from the `DC` extension to get the final values for the dynamic content attributes ([link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-5bd015f18e9f02defaafe6c1a7ecfe39539017cbf20f6177f47a15b0f3f9cd25L16-R23), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-5bd015f18e9f02defaafe6c1a7ecfe39539017cbf20f6177f47a15b0f3f9cd25R45-R46), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-5bd015f18e9f02defaafe6c1a7ecfe39539017cbf20f6177f47a15b0f3f9cd25R87-R92), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-5bd015f18e9f02defaafe6c1a7ecfe39539017cbf20f6177f47a15b0f3f9cd25L90-R106))
*  Add a new file `e2e-tests/components/context-loop/content.js`, which contains the code editor content for the context loop e2e test, and a new file `e2e-tests/components/context-loop/index.spec.js`, which contains the e2e test for the context loop feature ([link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-8741c2a67a2e65ef69c2ee5120a828d8dedc13469690210bc7a8299ea7f8f2a9R1-R4), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-f7be057316002feeb2e123fd1f23e1f80f5e13150f76d84ce7476e4e5c1a0949R1-R104))
*  Update the `e2e-tests/components/dynamic-content/content.js` file, which contains the code editor content for the dynamic content e2e test, to add two new blocks that test the dynamic content fields for the post or page categories and tags ([link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-37f7d914ca6362150649fed79e88c7cf3a0196b066659c720f98217a6da4fedcL2-R2))
*  Update the `e2e-tests/components/dynamic-content/post.spec.js` file, which contains the e2e test for the dynamic content post, to add the expected values and the results for the categories and tags fields, and to add them to the assertions ([link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-e88d9f9f7d42f674eb6bcced6ba0b852bfd604494e3a0a16b6bad46abb98c96cR44-R45), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-e88d9f9f7d42f674eb6bcced6ba0b852bfd604494e3a0a16b6bad46abb98c96cR52-R53), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-e88d9f9f7d42f674eb6bcced6ba0b852bfd604494e3a0a16b6bad46abb98c96cR74-R81), [link](https://github.com/maxi-blocks/maxi-blocks/pull/4701/files?diff=unified&w=0#diff-e88d9f9f7d42f674eb6bcced6ba0b852bfd604494e3a0a16b6bad46abb98c96cR88-R89))

### CODE REVIEW

**Review by Naaaaiix — COMMENTED** [review]
Tested yesterday and did a shallow review of the code. Lovely, is awesome! 😻 

Let's share your opinions, doubts and suggestions; remember it's a prototype and we are building as we walk 😸

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) was not fixed it in some of previous issues?
image
2) is it ok, that if we dont have enogh posts for columns, they are repeating?
https://jam.dev/c/d4eddb96-0e22-4498-bc0b-f97d5264cad0
3) need to check how should work tags and categories
https://jam.dev/c/1ceb331b-bb71-499e-ac19-7227cf445540

**Review by Olekrut — APPROVED** [review]
but need to decide smth with point 2 https://github.com/maxi-blocks/maxi-blocks/pull/4701#issuecomment-1531767836

**Review by Naaaaiix — APPROVED** [review]
Awesome job @Fybex, congrats buddy 👏 

Some comments to discuss and talk:
1. Not convinced about this flow, not sure how it fits with the CL 🤔  and I'm who suggested it lol
Captura de Pantalla 2023-05-03 a las 16 03 19

2. Selecting `Get by: random` makes the changes constantly on the blocks, which generates unexpected changes that also reduce the speed of the flow. It probably comes from previous implementations, and doesn't mean it needs to be fixed in this one; just sharing and expecting your point of view:

https://user-images.githubusercontent.com/50477222/235942532-a32d8494-3ae4-43e9-93be-dacf21d32f93.mp4

And that's all. I really tried to find problems to complain and to make a long list, but haven't find any more 😜  again, good job @Fybex 🙌 

PS: @Olekrut about the accumulator situation, not 100% sure, but IMO we should prevent the accumulator going higher than the biggest amount of elements, and the Row should do the same: in case we have a Row of 4 and the CL just returns 3 elements, it should become 3. @Fybex feel free to open a discussion for it, is a big thing 👍

**Review by Naaaaiix — APPROVED** [review]
Looks good @Fybex; about e2e test, going to derive to a new issue so we can start testing CL 😄

**Pull request merged**
