### PR TITLE
Issue 3799 - fix responsive

### PR DESCRIPTION
**Pull request by moroz-art-dev**
# Description

When changing the responsive, there was an error with the positioning of the border width.

Fixes #3799

# How Has This Been Tested?

to check the work, watch the video in the issue

# Test checklist

**_ Front/Back Testing _**

-   [ ] add some containers
-   [ ] add borders these components
-   [ ] choose other values responsive
-   [ ] choose other values borders
-   [ ] make sure the image works correctly

**_ Pre-Code Testing _**

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — APPROVED** [review]

**Review by myroslavve — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
What's happening with the tests is the fact that some results has changed. In this case, the best way to see it, is the unit tests coming from the bg helper (`src/extensions/styles/helpers/test/getBackgroundStyles.js`). It's saying couple of things:
1. This implementation is adding new `size` entry on the styles object. That can be a problem, and needs to be checked (that's the main reason of the tests) as is adding content that maybe 1) is not necessary or 2) can affect other elements or styles.
2. This new implementation needs new tests to be shielded. Current unit tests need to be update or need to be enhanced to deal with what this PR is implementing 👍

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Check my last comment please @moroz-art-dev

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Better, but still broken:
1. Please, be carefully when updating tests: `e2e-tests/components/border-control/__snapshots__/index.spec.js.snap` is broken:
Captura de Pantalla 2022-11-07 a las 19 47 19

2. Please, create tests to ensure this feature is not breaking in future

**Review by Olekrut — APPROVED** [review]

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Much better, yes sir! 👏 

Some things I've found; not sure if they were before, but I think they are related. Here they come:
1. On a responsive stage different from base, when setting some value to 0, the position doesn't look correct; seems it needs to have a position `-1px`. You can test it on the code editor below from a XL base and M responsive:
Captura de Pantalla 2022-11-09 a las 20 10 23

2. On removing the number, in my case on hover, it seems to have an error. Can also be tested with the same code editor:
Captura de Pantalla 2022-11-09 a las 20 17 05 1

3. With `border-style === 'none'` the positioning styles are still rendered. Can be seen on hover tab, same responsive and same code editor:
Captura de Pantalla 2022-11-09 a las 20 28 04

[code editor](https://github.com/maxi-blocks/maxi-blocks/files/9974619/border.txt)


Ping me tomorrow, we might use these commented cases to create tests to ensure this fix works and is not broke never again 😸

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Same code editor than last comment on M responsive stage 👍 

Captura de Pantalla 2022-11-10 a las 18 00 30

As commented, we might work this case as a TDD; ping me tomorrow and we might work together on it 👍

**Review by Olekrut — APPROVED** [review]

**Review by Fybex — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]

**Pull request merged**
