### PR TITLE
Issue 736

### PR DESCRIPTION
**Pull request by javadsamiee**
Add Highlights

### CODE REVIEW

**Review by elzadj — CHANGES_REQUESTED** [review]
Cool, I have some notes:

1. I think we need one custom setting for the highlight, with a multiply selector:
--->Highlight: text, bg, border<--- 

Or we can move settings @javadsamiee created around - add highlight text to typography, border - to border, bg - to bg. But I think the first way with just one setting is more usable.
This can wait for now tho. Not important for the library. 

2. We may want to make the text and bg highlights to disable each other. I.e. if the text is on - the bg is automatically off, and vice versa. Again, this can wait.

3. There is a problem with the border - when you highlight it, nothing really happens, because it's None in the settings. Need to make it solid automatically, I think. This we need for the library. @javadsamiee , please, add it.

4. I do not see the highlight classes on the frontend. I think we need to test Frontend too, at least for one block, to make sure it's ok before we start the patterns.

**Review by elzadj — CHANGES_REQUESTED** [review]
Need to update the border settings, not just add another border. The highlight toggles the border colour only.

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Container and Row return me an error 💥

**Review by Naaaaiix — APPROVED** [review]
Cool! Did some suggestions for improving, but is working, so it can be merged if my suggestions are not considered 👍 😄

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
On testing Container it breaks 👍

**Review by Naaaaiix — APPROVED** [review]
Looks good for me =) The only thing would be what @elzadj commented: when setting a highlight bg, may the text should become other colour. Would you like to merge this branch and set a new issue for it or what's the plan?

**Review by elzadj — APPROVED** [review]
Merge it, we can deal with the text later :+1:

**Pull request merged**
