### PR TITLE
issue 3321 icon toolbar position

### PR DESCRIPTION
**Pull request by Marko64**
Made the toolbar open downwards and moved the toolbar a bit lower when the icon is on the top so it doesn't cover the text

Fixes #3321 

# How Has This Been Tested?

Insert the button block and add an icon. Test all 4 icon positions and open each option's settings.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test all four icon positions and make sure it doesn't cover the button.

**_ Pre-Code Testing _**

-   [ ] Test all four icon positions and make sure it doesn't cover the button.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Rustam198804 — APPROVED** [review]

**Review by Fybex — CHANGES_REQUESTED** [review]
Can we make the `translateY` icon-position-top value non-static? We can calculate it based on the spacing and font size of the button, right?

**Review by Fybex — APPROVED** [review]
I think now it's much better, won't overlap content 👍

**Review by Naaaaiix — COMMENTED** [review]
Lovely the way you played with the refs, well done @Marko64 👏 

Small thing and will be ready to merge 👍

**Review by elzadj — APPROVED** [review]
Just fix what Josh says, thanks :+1:

**Review by elzadj — APPROVED** [review]

**Pull request merged**
