### PR TITLE
WP 6.4 fixes

### LINKED ISSUE #5225: WP 6.4-RC2 bugs
### Description

1) UI for SC window ( fixed )
image
2) List has weird padding on backend
image
3) colour under pallet does not change
https://jam.dev/c/bf0f0e7f-7989-40d9-ac2c-b5f1e76c9d02
4)  wrong colour pallet in SC
https://jam.dev/c/d6026b31-33f6-4a06-928e-be6646e43b30
5) random horizontal scroll
https://jam.dev/c/b6e4b052-645b-4aa1-b68b-f10f4716dc17

### Step-by-step reproduction instructions

.

### Screenshots, screen recording, code snippet

_No response_

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Fixes bugs for WP 6.4 and other small bugs (crisp chat on new installation, dc-field php warning)

Fixes #5225

# How Has This Been Tested?

Please test the Text block, especially lists. We lose the indent setting on 6.4 in toolbar, and the cursor doesn't move automatically when we create a new li on 6.4, but that's something we can survive for now.

Please test Text Block on 6.3.2 too. Custom lists too (text, url, svg). Whatever you can imagine.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the Text block lists component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] The same points on WP 6.3.2

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Added a chat support feature in the admin dashboard.
	- Introduced new settings for list styles in the toolbar.
	- Added compatibility with WordPress 6.4 and WooCommerce integration with Dynamic Content.
- **Bug Fixes**
	- Fixed PHP warnings, scroll effects, text generator placeholder color, shape divider for containers, custom aspect-ratio for image and video blocks, repeater warnings, global padding for full-width containers, and rendering dynamic content on new sites.
- **Refactor**
	- Improved handling of list items and links within a text block.
- **Style**
	- Updated CSS styles for various components and blocks.
- **Tests**
	- Adjusted timeout duration in a test file.
- **Documentation**
	- Updated readme and changelog for version 1.5.2.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
list is not working correct:
1) how list works with "Enter" and "Shift + Enter"
https://jam.dev/c/605c41f2-76e6-4f9b-bf3c-f878508137ea
2) dotted border should be for all text block, not for each li ( i guess, related with previous point )
image
3) text-block overlapping, can be problem if use BG Layers for them
image
4) https://jam.dev/c/4a7a97a1-cbf2-4f22-9618-d283d8c65d65
problem with links at old patterns ( link is empty and can't change link's colour ) - backend
5) 2 warnings
image

**Comment by elzadj** [comment]
1. how list works with "Enter" and "Shift + Enter"
https://jam.dev/c/605c41f2-76e6-4f9b-bf3c-f878508137ea

Can't change, it's in the WP update.

**Comment by Olekrut** [comment]
> 1. how list works with "Enter" and "Shift + Enter"
>    https://jam.dev/c/605c41f2-76e6-4f9b-bf3c-f878508137ea
> 
> Can't change, it's in the WP update.

It is terrible news. looks bad((((

**Comment by elzadj** [comment]
@Olekrut 
ok, new version. Please use Shift+Enter on 6.4 for the list (no, can't change it). Ignore the warnings please. 
Knows issue - new empty li item is weird on 6.4, I'm trying to fix

**Comment by Olekrut** [comment]
except bug with Ctrl+Shift

1) first rendered colour for links, it is ok after click
https://jam.dev/c/ae6b46e1-8f35-4e47-8f82-36aea6b07722
2) error
image
3) warning on frontend
image

**Comment by elzadj** [comment]
@Olekrut would be great to get the pattern name of the gutenberg code. And is it on 6.4 or 6.3.2?

**Comment by elzadj** [comment]
2. Ignore for now https://github.com/maxi-blocks/maxi-blocks/pull/5237

**Comment by Olekrut** [comment]
> @Olekrut would be great to get the pattern name of the gutenberg code. And is it on 6.4 or 6.3.2?

@elzadj i ve used PFL-PRO-74, but the same is with any pattern with list
WP 6.4-RC3

**Review by Olekrut — APPROVED** [review]

**Pull request merged**
