### PR TITLE
Issue 5344: speed in Editor

### LINKED ISSUE #5344: General speed optimization in EE
### Description

Need to measure speed for each function and chunk of code, find the slowest, and optimize them. 

For an example, the slowest part on click on a block is ```displayStyles / const obj = this.getStylesObject;``` , i.e. ```getStyles``` per a block. 

For a column, the main issue there was ```getSizeStyles``` - 50-60 ms before optimization, and 20-30 after optimizing```getLastBreakpointAttribute```, ```getDefaultAttribute``` and ```getSizeStyles```. And cumulative speed win is even bigger. 

Main targets for optimizations are in /src/extensions/styles/helpers/

### Other plugins or websites examples

_No response_

### How to implement it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

General optimizations for style generation for some functions (see the commits for the list). Affects render speed, browsing blocks in Gutenberg and changing settings.

Fixes #5344 

# How Has This Been Tested?

Deep test borders, margins, background, colours (including palette), NC, Images and SVG Blocks. For old patterns, new reated blocks, patterns from the Cloud.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Performance Improvements**
	- Optimized color retrieval and application across style cards and breakpoints.
	- Implemented memoization for attribute value fetching to enhance efficiency.

- **Refactor**
	- Streamlined logic for obtaining active style card information.
	- Refined color string generation and breakpoint attribute handling.
	- Improved background, border, margin, padding, and SVG style processing.

- **Bug Fixes**
	- Fixed inconsistencies in style application for hover states and variable conditions.

- **Style**
	- Adjusted styling logic to ensure accurate visual representation across various user interactions.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) after changing tone, some of the colours are not correct ( need to click to this block )
https://jam.dev/c/a12deb02-128c-4e30-a6cb-2bd050b12df2

ooo, the same on master we have important bug, not related to this brunch

**Comment by elzadj** [comment]
> 1. after changing tone, some of the colours are not correct ( need to click to this block )
>    https://jam.dev/c/a12deb02-128c-4e30-a6cb-2bd050b12df2
> 
> ooo, the same on master we have important bug, not related to this brunch

Moved to another issue, since it's the same on master https://github.com/maxi-blocks/maxi-blocks/issues/5360

**Review by Olekrut — APPROVED** [review]
IDK, it is miracle or need some combination to find the bugs, but cant) 
Great job, @elzadj 🥇

**Comment by ckp267** [comment]
Whoohooo! This is amazing so far! Well done @elzadj - I want more now! 

**Some items to look at** 
I was testing on staging.

1. block dragging (mover) is definitely faster but 

- outlines, 
- drop targets, 
- and z-index need some love. See video. 

https://github.com/maxi-blocks/maxi-blocks/assets/7437580/44619eac-2095-4139-9fcd-e14f9fef720c

2. block delete and page delete CTRL + A + Delete is finally fast. A huge page took 3 seconds - previously it took like 12 seconds to delete the page content.

3. Insert from template library is faster too. 

Great work really. We need more of this.

**Comment by elzadj** [comment]
I did not touch the moving at all, the speed improvement is from other changes, good that they affect everything. 
Going to add block moving to part 2 for optimization.

**Pull request merged**
