### PR TITLE
Issue 4115 - hover attributes on responsive

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
 - hover attributes that have the same value as normal one (e.g. `attribute-general-hover: 5` is the same as `attribute-general: 5`)  are now cleared, but only on general or if they are non-responsive because if this kind of attribute is cleaned on responsive, the higher hover attribute can generate hover styles that will apply on lower breakpoints which then need to be overridden to have same value on hover and normal.
 - hover attributes on responsive are now cleared the same as normal ones.
 - added tests to ensure fixes work.

Fixes #3810
Fixes #4115

# How Has This Been Tested?
 - Checked that #4115 was fixed. 
 - Checked that hover attributes same as normal ones are removed (saved as `undefined`). 
 
 https://user-images.githubusercontent.com/53875005/210220437-b2d1c610-60e1-4854-b1fd-f6efd38657ef.mp4

 - Checked that hover attributes are cleaned on responsive.
 
 https://user-images.githubusercontent.com/53875005/210219855-cf141c96-68ba-4dcc-b49d-618050ffb1a9.mp4

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check that #4115 was fixed. 
-   [ ] Check that hover attributes same as normal ones are removed (saved as `undefined`).
-   [ ] Checked that hover attributes are cleaned on responsive.

**_ Pre-Code Testing _**

-   [ ] Check that #4115 was fixed. 
-   [ ] Check that hover attributes same as normal ones are removed (saved as `undefined`).
-   [ ] Checked that hover attributes are cleaned on responsive.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [x] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/9db1bf54-664a-47e8-a6e5-222674761177

**Review by Olekrut — CHANGES_REQUESTED** [review]
only on this brunch
hover is not working if change only unit
https://jam.dev/c/1586bcc1-8a39-4d8a-8883-76b934c339b2

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/831ef4f8-2c0f-480a-916b-d570dbec39d5
[hover attr.txt](https://github.com/maxi-blocks/maxi-blocks/files/10483710/hover.attr.txt)

**Review by Olekrut — APPROVED** [review]

**Review by Fybex — CHANGES_REQUESTED** [review]

**Review by Fybex — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]

**Pull request merged**
