### PR TITLE
Issue 4051 - `ClipPathControl` love

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Changes:
- set by default 4 points in square shape for polygon
- fixed problems with `Add new point` button
- added hover state
- added clip path transition support (not smooth when hover and state have different amount of points)
- added capacity to reset values on custom editing
- fixed problem, when shape overlaps settings (try to move shape to the top and change `ClipPathControl` settings)
- `clip-path-general` default is now - `none`
- `hover-transition-easing` default from `easing` to `ease`

Fixes #4051 

# How Has This Been Tested?
Checked if all changes works as expected in image-maxi and bg layers.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in image-maxi
-   [ ] Test the component in hover state in image-maxi (if hover exists)
-   [ ] Test the component in normal state in bg layers
-   [ ] Test the component in hover state in bg layers (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in image-maxi
-   [ ] Test the component in hover state in image-maxi (if hover exists)
-   [ ] Test the component in normal state in bg layers
-   [ ] Test the component in hover state in bg layers (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] My changes generate no new warnings/errors
-   [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/19425503/208945338-954953c1-dfe1-453b-b203-a2c6540911e2.mp4

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/d6310f54-cc51-48a6-b329-9f54c87fa2a0
to add Manage Hover transition to clip-path hover state
2) Button - "add new point" is disappearing after 10
3) if clip-path has more than 10 points, points  don't have colour
image
image

**Review by Olekrut — APPROVED** [review]
Conflict hover and IB ( hover is not working if we set IB ), but I guess, it should be another brunch because we already have similar problem with opacity and BG color https://github.com/maxi-blocks/maxi-blocks/issues/4068

**Review by Naaaaiix — COMMENTED** [review]
Awesome job @Fybex 👏  left a detail 👍

**Pull request merged**
