### PR TITLE
Issue 2474 - ColorControl reset button

### PR DESCRIPTION
**Pull request by FitseTLT**
I have dealt with the comments you gave me. Check it out and ping me back.

-------------------------------------------------------
@Naaaaiix comment:
To test:
1. On changing a palette colour, when reseting it should give back the default palette colour or the responsive previous one.
2. On change from palette to custom, custom should get the palette colour
3. On change custom colour and then reset, custom colour should come back to the palette colour default (not changing to palette selector)

Note: BackgroundColor layers is not perfectly working, needs to be fixed. As is part of something bigger, will be derive to a new issue onces this PR will be merged 👍

### CODE REVIEW

**Review by Naaaaiix — COMMENTED** [review]
BRAVOOOOO 👏 🥳 

Really good implementation, but furthermore an incredible understanding of the issue and Maxi's mechanics. Keep pushing like this 💪 

So, left some small comments. More labeling and reading clues than anything, the code works perfect. So, next step: implement it on every ColorControl instance. Onces done, we'll have a call to check the tests so I'll introduce you on them 👍

**Review by Naaaaiix — COMMENTED** [review]
Good job, couple of changes and then we'll have a look to tests together 👍 . For the moment we are going to leave the toolbar changes, so don't worry for them 😸

**Review by Naaaaiix — CHANGES_REQUESTED** [review]
Ping me on chat if there's anything you don't understand of my comments or my suggestions. Thanks 🙏

**Review by Naaaaiix — CHANGES_REQUESTED** [review]

**Review by Naaaaiix — APPROVED** [review]
Magnific job @FitseTLT , congrats 🥳

**Review by elzadj — APPROVED** [review]

**Review by Alejandro9kgm — APPROVED** [review]

**Pull request merged**
