### PR TITLE
Issue 5332 - Fix `image-maxi` hover effect frontend

### LINKED ISSUE #5332: Image hover effect amount not working on the frotnend
### Description

The amount is always the default one 1.3 on the frontend.

### Step-by-step reproduction instructions

1. Insert an image.
2. Apply the zoom-in hover effect.
3. Change the amount. It works correctly on the backend but not the frontend.

### Screenshots, screen recording, code snippet

_No response_

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #5332 

### Changelog
- fixed hover effect custom duration, etc on frontend
- fixed `cubic-beazer` easing settings save(on master it resets to default after reload)
- fixed conflict between transitions from hover effect and other transitions (for example: enable hover effect and clip-path hover. On master only one transition would work, but here - both)

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test all hover effects options on backend
-   [ ] Test all hover effects options on frontend
-   [ ] Test hover effects with transitions from other blocks (hover border, hover clip-path)
-   [ ] Test if cubic-beazer ease settings don't disappear after editor reload
-   [ ] Test image-maxi styles in general
-   [ ] Test if old image-maxi blocks with hover effect don't crash after switching to this branch

**_ Pre-Code Testing _**

-   [ ] Test all hover effects options on backend
-   [ ] Test all hover effects options on frontend
-   [ ] Test hover effects with transitions from other blocks (hover border, hover clip-path)
-   [ ] Test if cubic-beazer ease settings don't disappear after editor reload
-   [ ] Test image-maxi styles in general
-   [ ] Test if old image-maxi blocks with hover effect don't crash after switching to this branch
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors

## Summary by CodeRabbit

- **New Features**
  - Added a search functionality to the app.

- **Improvements**
  - Optimized hover effect application, ensuring smoother transitions and visual enhancements.
  - Refined hover effect timing functions for a more polished user experience.

- **Bug Fixes**
  - Fixed inconsistencies in hover effect transitions across various components.

- **Refactor**
  - Streamlined hover effect logic for better performance and maintainability.
  - Removed redundant code related to hover effects, improving component efficiency.

- **Style**
  - Updated styling logic to accommodate new hover effect features and ensure consistent application.

- **Documentation**
  - Adjusted documentation to reflect changes in hover effect management and style processing.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
Not sure that all these points related to this issue, but..
1) if enable image-maxi hover and any else hover ( for example box-shadow ) hover-in transition does not work correct - https://jam.dev/c/0b8ce821-afe6-4049-b264-a292d4eb1c52
Check split in/out, guess, there is conflict
image
2) Check for all transform options ( zoom, slide, rotate ) - trigger field is "img" , is not working correct, - https://jam.dev/c/1d3695d7-6f0d-4f5c-877c-d1f6f2d06d86
3) For gray scale and sepia hovers - transition does not work - https://jam.dev/c/31ed34cd-d297-42e7-a191-0eb7ebaaa0c6
4)
4.1) animation in image settings use transform for img, so there are conflict - we cant use both - https://jam.dev/c/306c4e51-872a-41a7-9a96-7d5a6f666ccc
4.2) The same with scroll - we cant use hover animation and scroll -https://jam.dev/c/d2a72c2f-985f-4f92-a11a-3fa135ab0dc4
5) if use hover with disabled "Extend outside boundary" > guess, settings ( box-shadow, borders, etc. ) are not visible, because overflow:hidden - is not intuitive for nubbies - https://jam.dev/c/85f00dcd-aa7d-420d-8bc2-eeec33bbcd9a
6) ( not very important )  text hover - when you are changing animation type - first hover-in is not working correct - https://jam.dev/c/a727ffe9-4a96-42b8-b9c6-1bfdfeddab14
7) Sure, that we will have conflicts with IB as well


We have a lot of conflicts with hover animations - so 
1) need a warn massage
2) disallow part of used  options.
3) or best way as for me - 
it should work like quick styles for button
Example when we use Zoom hover animation > it should enable related transform scale setting in advanced tab
the same with slide, etc

**Comment by Olekrut** [comment]
@kyrapieterse said that need just hide hover animation for Image block for now

**Comment by kyrapieterse** [comment]
Lets hide these setting for now. We want people to use the IB anyways

**Comment by Olekrut** [comment]
Actually, we can  hide only zoom slide and rotate effects
most of the conflicts related with it.. 
just will be need to fix transition and overflow bugs (point 1,3,5), if is not hard
image
I think it will upset users a lot less

**Comment by kyrapieterse** [comment]
ok good plan @Fybex ping me if you need to talk about it

**Comment by Fybex** [comment]
> Not sure that all these points related to this issue, but..
> 
> 1. if enable image-maxi hover and any else hover ( for example box-shadow ) hover-in transition does not work correct - https://jam.dev/c/0b8ce821-afe6-4049-b264-a292d4eb1c52
>    Check split in/out, guess, there is conflict
>    image

Thanks, fixed for split in/out. Rechecked if it works with setting turned on and off 👍 

> 2. Check for all transform options ( zoom, slide, rotate ) - trigger field is "img" , is not working correct, - https://jam.dev/c/1d3695d7-6f0d-4f5c-877c-d1f6f2d06d86

Changed trigger

> 3. For gray scale and sepia hovers - transition does not work - https://jam.dev/c/31ed34cd-d297-42e7-a191-0eb7ebaaa0c6
> 

Fixed

> 4.1) animation in image settings use transform for img, so there are conflict - we cant use both - https://jam.dev/c/306c4e51-872a-41a7-9a96-7d5a6f666ccc 

image

Fixed

4.2) The same with scroll - we cant use hover animation and scroll - https://jam.dev/c/03ad0426-ede9-4003-bfcb-939b920fd3dc

image

Fixed

5) if use hover with disabled "Extend outside boundary" > guess, settings ( box-shadow, borders, etc. ) are not visible, because overflow:hidden - is not intuitive for nubbies - https://jam.dev/c/85f00dcd-aa7d-420d-8bc2-eeec33bbcd9a 

Deriving it to a new issue

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
