### PR TITLE
Experimental settings

### PR DESCRIPTION
**Pull request by Naaaaiix**
## Update (2/5/23)
- Fixed Row alignment problems
- Fixed unit tests
- Fixed the repeated class on native WP blocks on frontend
- Added CSS processor for SC styles

# Description

This implementation adds different experimental settings, so the first implementation is a new tab on the Maxi Dashboard with `Experimental settings`. The idea of experimental settings are to let people test them knowing they aren't working 100% correct. The ones implemented are:
1. Indicators: allow enabling the well known indicators.
~~2. Allow StyleCards to affect Gutenberg native blocks: this is the most interesting one. Going to get deeper into it:~~

P.S. it's not in experimental dashboard accordion anymore

Affect Gutenberg native blocks inside Maxi Blocks: feature which was added to Maxi SC popup

image

The main idea of `Allow StyleCards to affect Gutenberg native blocks` setting is to let native blocks be styled by SC. The objective is to be able to use MaxiBlocks as a tool capable of create a whole website, including header and footers. As we don't have blocks for it, we can use the existing WP native ones for it, and to be sure we can keep the styles coming from SC in whole website, this feature enables the capacity to affect that blocks with the SC. To do be affected we need:
1. Enable the option from `experimental` tab on Maxi ~~dashboard~~ Maxi SC Popup (it's turned on by default for default SCs).
2. Add a native block inside a MaxiBlock.

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/3dbb076e-aaae-4ad8-a70f-9f54f0775dfc

As `experimental` feature, there are some small known errors:
~~1. The classes added to native blocks in frontend are sometime repeated.~~
~~2. Fonts don't work unless there's a Text Maxi or any other Maxi block that requires fonts from SC.~~
~~3. ... 🤔 ~~
4. Fonts don't work if page wasn't saved with turned on SC toggle

# How Has This Been Tested?

Create native WordPress blocks inside MaxiBlocks and check the behavior when modifying SC. Can check also enabling/disabling options. Same for indicators 👍 
Checked how SC works with turned on and off toggle in FSE and post editor, on frontend and backend. Checked how SC migration works.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check whether the indicators experimental setting works when it is on and does not work when it is off
-   [ ] Check if default SC and any imported SC from SC library have this Affect native blocks toggle turned on by adding into maxi block native blocks and checking whether they have SC styles or not
-   [ ] Check if the SC that was not reactivated in this branch still has styles applied to native blocks on backend and frontend
-   [ ] Check if it's possible to turn on toggle and if after turning on SC won't apply to native blocks on backend and frontend
-   [ ] Change SC settings with turned on affect native blocks toggle and check if it works as expected
-   [ ] Change SC settings with turned off affect native blocks toggle and check if it works as expected
-   [ ] Test if toggle affects only native blocks, not other custom blocks
-   [ ] Check if native blocks are visible in maxi wrapper block with added bg layers

**_ Pre-Code Testing _**

-   [x] Check whether the indicators experimental setting works when it is on and does not work when it is off
-   [x] Check if default SC and any imported SC from SC library have this Affect native blocks toggle turned on by adding into maxi block native blocks and checking whether they have SC styles or not
-   [x] Check if the SC that was not reactivated in this branch still has styles applied to native blocks on backend and frontend
-   [x] Check if it's possible to turn on toggle and if after turning on SC won't apply to native blocks on backend and frontend
-   [x] Change SC settings with turned on affect native blocks toggle and check if it works as expected
-   [x] Change SC settings with turned off affect native blocks toggle and check if it works as expected
-   [x] Test if toggle affects only native blocks, not other custom blocks
-   [x] Check if native blocks are visible in maxi wrapper block with added bg layers
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [X] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — CHANGES_REQUESTED** [review]
For me font size doesn't change at all.
Font family only changes for Text Maxi (top text in the video). The bottom one (paragraph block) doesn't change.
Also rows are not aligned properly - not sure if related to this PR but didn't notice it on master.
https://jam.dev/c/17b68855-858f-47ac-8759-0c3fc30c8bb2

**Review by Marko64 — CHANGES_REQUESTED** [review]
Row alignment - **fixed**.

Font thing still behaves the same for me. Attaching the code.
I have the option "Allow StyleCards to affect Gutenberg native blocks" enabled. Tested in Chrome and FF.

[sc-gutty-blocks.txt](https://github.com/maxi-blocks/maxi-blocks/files/11371082/sc-gutty-blocks.txt)

**Review by Olekrut — CHANGES_REQUESTED** [review]
font things are not working for me as well
works only colour and only on frontend

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/4cfd5868-1136-4b1f-9475-6188291d2b29
1) for button is working only BG Colour ( not hover )
2) WP Navigation is not looking correct on backend
3) Paragraph looks better, but : 
3.1) need ability to remove default margin-top/bottom
3.2) white-space is not working on backend
3.3) bottom gap is not working at all

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) For theme templates, we need Comments, they are not working on frontend) 
on backend, they are not working correct as well
https://jam.dev/c/36de0652-5f81-44d2-bba6-bcc1e089cb85
and need that comment and date, author could have ability make them as different colours ( now they as P ) maybe need to make tham as P and H6
2) paragraph is better, but is not enough, and i understand
3) button as block is not good, and i understand, but we have WP button in Comment "post comment"

**Review by Olekrut — CHANGES_REQUESTED** [review]
check Comments and Navigation) smth is working, but very partly 
https://jam.dev/c/22b905c6-74ec-44dd-ab68-3167b98833f9
backend and frontend
[experemental.txt](https://github.com/maxi-blocks/maxi-blocks/files/11429212/experemental.txt)

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
comments block is not working with it ( pagination, next, previous button )
actually, nothing is working

before last update styles are worked partially, bad, but worked

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/a4844c1a-5ac6-433c-be8f-a201f9f3d0ce
Comments
2) 
image
not all H-tags looks correct on backend
3) 
image
I guess, it needs for default ( not custom SC ) as well
4) 
image
Not sure, that is possible, but need our settings for Gutenberg blocks ( at least paddings, margins ) . Otherwise, will be need to add extra CSS file

**Review by Olekrut — CHANGES_REQUESTED** [review]
Much much much better 👍 

Tested on 2023:

1) would be good to make transition for native blocks
2) Responsive is not working for native blocks (backend)
image
3) some of native blocks have own opacity is not changing by SC
image
4) https://jam.dev/c/f17ae7d7-1a7d-4f44-838c-c496a8c3decb
I guess, it needs for default ( not custom SC ) as well
we can't disable Maxi styles for native blocks for not custom SC
5) have noticed it few times, but randomly
https://jam.dev/c/8b06cad7-f902-4899-866c-567a9402b1dd
Changing smth on SC, and everything is disappearing on frontend ( only this brunch )

**Review by Olekrut — CHANGES_REQUESTED** [review]
Looks almost good))

1) check it for pagination block
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
Hover colours with help SC are not working
https://jam.dev/c/e2cc710d-cc45-44ae-8492-582dec1e08da
is it expected?

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) text-indent is not working for some texts
image
2) bottom-gap is not rendering on responsive
image
3) again this problem with SC
try it
[Maxi (Default) - 111_exported.txt](https://github.com/maxi-blocks/maxi-blocks/files/12147850/Maxi.Default.-.111_exported.txt)
if change to default SC, everything is OK
image
4) field is not changing after swap to dark tone
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) typed text inside form, need to change colour for dark tone
https://jam.dev/c/213e6183-de5b-4c13-b1a8-dc65fd974271
better if it will be changed by Paragraph colour, right?

**Review by Olekrut — APPROVED** [review]
not sure, but i guess, main problems are solved)

**Review by myroslavve — APPROVED** [review]
Works good, didn't find any bugs, have two small non-blocking questions.

**Review by elzadj — APPROVED** [review]

**Pull request merged**
