### PR TITLE
Issue 5706 - fix reset for DC values

### LINKED ISSUE #5706: Reset for DC values
### Description

Reset button is not backing value selected in parent block ( CL )
P.S.: if to change some value for included block (DC) > it will not be changed automatically after changes in parent row (CL).
You will always have to change it manually.

### Step-by-step reproduction instructions

1) Create row and enable CL
2) add some block inside and enable DC
3) change some values ( relation, order, type, etc. )
4) try to reset these values ( should be the same as in CL of parent row )

### Screenshots, screen recording, code snippet

https://jam.dev/c/d8bcb8aa-79b9-4cc4-ade0-c799e0b4bda1

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description

Fixed resetting values for DC in CL.

Fixes #5706

# How Has This Been Tested?
Checked that all the values reset correctly for blocks inside CL and without CL.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check that all the values reset correctly for blocks inside CL and without CL.

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Improved clarity in the DynamicContent component with a variable rename from `isCL` to `CLStatus`.
	- Enhanced conditional rendering of the ToggleSwitch component based on the new `CLStatus` variable.
	- Updated logic for resetting the `cl-id` in the ContextLoop component to improve state management.

- **Bug Fixes**
	- Adjusted logic for detecting changes in dynamic content, improving the accuracy of UI updates.

- **Refactor**
	- Streamlined the flow of the changeProps function for better performance and clarity.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
doesnot work for me
https://jam.dev/c/2a0fbc4c-1597-4564-a471-5da8e1ab9dba

**Comment by elzadj** [comment]
> doesnot work for me https://jam.dev/c/2a0fbc4c-1597-4564-a471-5da8e1ab9dba

Can't open the video, but it doesn't work for me too - nothing happens when I click reset, both in DC in Toolbar and Sidebar. I've used Pure Blog Dark PBGD-PRO-60 for tests.

**Comment by elzadj** [comment]
@Olekrut looks ready for a review too

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/b2de725b-6a9e-4f9e-be6d-430d51fddf3d
Blog pro-60 for example
check wrapper group and column - it is not reseting to value from parent row
sometimes it reset to wrong value

**Comment by elzadj** [comment]
@Olekrut looks like it's ready for review.

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
