### PR TITLE
Fix clicks on blocks speed

### LINKED ISSUE #5323: Freezes due to swapping between blocks
### Description

it has accumulative effect.
Add ib, blocks, use ib preview and repeater, after some moment, you will see freezes

more time in editing, without update and reload > longer freezes

### Step-by-step reproduction instructions

1) Add ib, blocks, use ib preview, after some moment, you will see freezes

### Screenshots, screen recording, code snippet

https://jam.dev/c/d37361f0-f26f-4a67-a557-f5624874329f

https://github.com/maxi-blocks/maxi-blocks/assets/88893350/fb53062c-8402-4f40-896f-80bd7c7b103f

### URL and/or Code editor

[code for test.txt](https://github.com/maxi-blocks/maxi-blocks/files/13663178/code.for.test.txt)

[code for test 2.txt](https://github.com/maxi-blocks/maxi-blocks/files/13663363/code.for.test.2.txt)

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elzadj**
# Description

Please see if that helps with freezes and clicks on blocks in general. Still work in progress.

Fixes #5323

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Enhanced the block editing experience with additional properties for block manipulation and interaction.

- **Refactor**
  - Improved the internal logic for breakpoint change detection and block rendering.
  - Streamlined attribute retrieval and default value handling in style management.

- **Bug Fixes**
  - Fixed an issue with rendering behavior controlled by `uniqueID`.

- **Style**
  - Code clean-up for better readability and maintainability, including removal of commented-out code.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/e31b8a78-17c4-43da-bb5e-37cd687b218f
i guess, not helped a lot 
maybe a bit, 5-8% better

**Comment by Marko64** [comment]
https://jam.dev/c/6bc1b1c1-ad4a-43da-b569-ff5e12488b8e
In my example there is a visible improvement. Still needs more time to switch sometimes but better compared to what we have now for sure.

**Comment by elzadj** [comment]
"the tests results are inconsistent", lol
I try something else, but yeah, Marko's columns are better for sure.

**Comment by elzadj** [comment]
@Olekrut could you give me code for the whole page from your tests? And the products export file too.

**Comment by Olekrut** [comment]
[woo part 1.txt](https://github.com/maxi-blocks/maxi-blocks/files/13685995/woo.part.1.txt)
[3devdemomaxiblockscom.WordPress.2023-12-15.zip](https://github.com/maxi-blocks/maxi-blocks/files/13686001/3devdemomaxiblockscom.WordPress.2023-12-15.zip)

**Comment by elzadj** [comment]
@Olekrut @Marko64 let's try this one

**Comment by Marko64** [comment]
I am not sure. Looks better but that page (code 2 example) is still a beast and really slow. @Olekrut What do you think, how it looks like for you? Maybe I can try another example to tell for sure.

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/8821c01d-b085-4327-8e57-3f5a2068cda2
SV said that test page should not have more than 200-250 blocks, i am using page with 197 blocks
[test 197 blocks.txt](https://github.com/maxi-blocks/maxi-blocks/files/13687654/test.197.blocks.txt)

Not sure about long using, but it obviously gets better ( less delay )

note: I guess, it gets slower after every click to "Update" page

**Comment by elzadj** [comment]
Some info on the issue - the slowest here is ```displayStyles / const obj = this.getStylesObject;``` , i.e. ```getStyles``` per a block. For a column the main issue is ```getSizeStyles```. 

And then its going down to optimizing ```getLastBreakpointAttribute``` and ```getDefaultAttribute``` too. And any helpers function, ideally.

**Comment by elzadj** [comment]
@Olekrut please take a look when you have a min. Test not only speed after pulling, but also responsive and defaults (code changes were added there).

**Review by Olekrut — COMMENTED** [review]
Feels better ( ~2sec instead of 3-5sec), don`t see bugs.
@Marko64 Check as well pls

**Comment by elzadj** [comment]
> Feels better ( ~2sec instead of 3-5sec), don`t see bugs. @Marko64 Check as well pls

tx, need to fix tests anyway

**Comment by Marko64** [comment]
I'm happy with the changes so far. Those codes we added in the issue work better and I just tried inserting patterns from the library, switching between blocks is significantly faster. If you ask me, let's push this as soon as possible, definitely feels faster

**Review by Olekrut — APPROVED** [review]

**Review by Marko64 — APPROVED** [review]
This I like

**Pull request merged**
