### PR TITLE
Issue 4210 - RTL UI - Round 1

### LINKED ISSUE #4210: Editor UI in RTL
### Description

Some styles don't look like they supposed.

### Step-by-step reproduction instructions

1. Switch editor to rtl
2. Create text-maxi
3. Open sidebar
4. Look at screenshot
5. Look at red shapes
6. Assess the problem

### Screenshots, screen recording, code snippet

image

### URL and/or Code editor

_No response_

### How to fix it

There are two problems:
1. Fix block info button position for RTL
2. Fix reset button position for RTL

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Marko64**
Fixes #4210 

There are many things to fix, so let's divide it a a few steps. This time, only check the sidebar.

**_ Front/Back Testing _**

-   [ ] Check sidebar settings.

**_ Pre-Code Testing _**

-   [x] Check sidebar settings.
-   [x] Check that CSS implementations are correct.

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Introduced search functionality, unified coding style, and added new issue templates for better issue tracking.
	- Implemented end-to-end and unit tests for improved code reliability.
	- Added new classes and methods for managing settings, styles, style cards, breakpoints, and custom data.
	- Enhanced the plugin with features like custom image cropping, local fonts handling, and page templates management.
	- Improved user interface with new CSS styles and added functionality for blocks like "Divider Maxi", "Group Maxi", "Image Maxi", "Button Maxi", "Column Maxi", and others.

- **Bug Fixes**
	- Fixed issues related to map marker addition, alignment settings, and responsive behavior of various components.

- **Documentation**
	- Updated README and LICENSE files.

- **Refactor**
	- Updated various configuration files for better code quality and testing.

- **Tests**
	- Added new test suites for various blocks and components for better code coverage.

- **Chores**
	- Updated `.gitignore` and `.eslintignore` files for better project management.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) arrow nav position
image
2) space between elements and setting labels
image

image
3) separate line from another side
image
4) 
image
5) negative values
image
6) 
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/a18b0695-1dd5-4f2e-8b49-82b63fdfc6e7
try to text in custom CSS


2) image
but the same on LTR
image
will create new issue

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://github.com/maxi-blocks/maxi-blocks/pull/4601#pullrequestreview-1354584908
point 1 is not fixed



2) clip-path ( remove point icon)
image
3) logo missed)
image
4) order of row is reversing https://jam.dev/c/53430ee8-8965-4376-a54a-44f5ebd02d7e
because it brakes patterns. Try to load Hero Light PRO-48 ( for example) 
image
5) link> toolbar > check word "search"
image
6) blue border
image
7) need to add space
image
8) wrong position for cursor https://jam.dev/c/56f0304c-0c7e-4deb-b4bb-1ed0ea8a7cd9
9) overlapping inside dropdown list 
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) wrong alignment for button and Icon and NC and divider
 image

image

2) 
image

3) need left padding and I see only end of label, I understand why, but looks wrong
image

4) dont see blue border from the right side yet
image

5) wrong position for search) 
image

6) breadcrumbs overlapping
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) text alignment is working correct in general because lefti is right and right is left, but icon can confuse 
image
For all blocks, which have text
image
2) I guess, list does not look correct
image

3) divider
image

**Review by Olekrut — APPROVED** [review]
1) cursor has wrong position 
https://jam.dev/c/520440ad-31e7-43b6-a5f4-e2654a10ac9f
2)
image
3) we have empty space for scroll line before it is appeared
image

> A suggestion: There is a lot more to do for RTL probably, so maybe we can do it in a new PR as round 2 so we can merge all these changes so far.

sure, then add these points to next round

**Review by Fybex — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
