### PR TITLE
Issue 5333 - Search button styles in toolbar

### LINKED ISSUE #5333: Search button styles in toolbar
### Description

Link:

screenshot-wordpress local-2023 12 15-12_40_56

Also please check it for all blocks with a link.

### Step-by-step reproduction instructions

Add a block with a link and check the toolbar.

### Screenshots, screen recording, code snippet

_No response_

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by kyrapieterse**
Fixes https://github.com/maxi-blocks/maxi-blocks/issues/5333

## Summary by CodeRabbit

- **Style**
	- Updated the layout and visual design of certain UI elements for improved user experience.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) Changes influence to another buttons
image
2) and fix is not correct at all, button, overlap input field.
https://jam.dev/c/0007271d-adf0-4043-b050-158d03fd2384

**Comment by elzadj** [comment]
yeah, I think we can just remove / hide this Search button from the url. Search works without it, when you type.

**Comment by kyrapieterse** [comment]
right: -19px !important;
position: absolute;
			
is what broke the other buttons lol

beyond me 🤪 @Marko64  take over and hide it 🙏

**Comment by Marko64** [comment]
Hidden the button now.

By default there's this arrow, we can have that too if  it looks better:
Screenshot_2

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) loader circle is overlapping link
image
2) sometimes link is suggesting, but not always 
I understand that I need to press Enter, but will it be intuitive for customers?
https://jam.dev/c/e834fd9f-a80c-4703-a781-c5b701ad5f14
3) is not related to this issue, but guess, easy to fix it here...
Need to change text colour for suggestion`s links ( grey or black )
image

**Comment by Marko64** [comment]
1. No good way to solve this. If I add right padding for the text it looks weird without the spinner icon.
2. I think it doesn't suggest anything for you because nothing similar exists to the content you added.
3. Not able to reproduce:
Screenshot_4
, text black for me in FF and Chrome

**Comment by elzadj** [comment]
1. How about just hiding that circle? Do we really need it?

**Comment by Olekrut** [comment]
About 1 and 2, agree with SV)
3) The same on incognito and FF, but looks like it is only on my local. Sv does not have this bug, so ignore
image

**Comment by Marko64** [comment]
2. Isn't enter reserved to confirm the input now? Especially when we don't have the button anymore. Default WP search also works like this. It shows suggestions as you type, not on enter

**Comment by kyrapieterse** [comment]
MVP 🙏

**Review by elzadj — APPROVED** [review]

**Pull request merged**
