### PR TITLE
Slider Maxi Block

### PR DESCRIPTION
**Pull request by elzadj**
# Description

New block - Slider Maxi.

IMPORTANT

We still need to figure out the slides width issue https://github.com/yeahcan/maxi-blocks/issues/2836 
@Marko64 you worked with our clients and DDP sliders a lot - how do people work with the width? 

Fixes #2835
Fixes #2833
Fixes #2777 

# How Has This Been Tested?

Add a new slider, some blocks inside the slides. Note that it has a starting template with empty slides with different color bgs.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the block in normal state in sidebar
-   [ ] Test the block in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the block in normal state in sidebar
-   [ ] Test the block in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — COMMENTED** [review]
This is starting to look muuuch better.

A couple of really small things with the navigation I noticed:

When you enable infinite loop and go to the end, it slides back to the first slide but the dot isn't active (same on frontend):

Screenshot_3

When you make the arrows a bit bigger they go outside the slider:
Screenshot_2

What about width exactly? Do we want slides to optionally have different width within the container? Not sure I understand it, lol

**Review by Marko64 — COMMENTED** [review]
A couple of things:

1. 
https://user-images.githubusercontent.com/19425503/177767502-bf206916-d826-4899-a91f-35652d77efff.mp4

2. You can click on the slide to edit it even it's not visible. Maybe some overflow hidden is missing only?
Screenshot_2

**Review by Marko64 — COMMENTED** [review]
I can see you added the CSS, but there's something wrong with the attribute data-slide-active. It appears in the DOM for a moment only and disappears. I think it shows only while  there's a transition between slides

**Review by Marko64 — CHANGES_REQUESTED** [review]
Something's still not right when the infinite loop is enabled. Same happens in Chrome and FF:
https://user-images.githubusercontent.com/19425503/178714451-fc645827-71e3-4bd3-a2f9-677208d1096e.mp4

**Review by Marko64 — CHANGES_REQUESTED** [review]
1. This issue still happens. If you click on the inactive slide that's on the screen, the slider gets messed up:
https://user-images.githubusercontent.com/19425503/182347320-ec9f2efc-1458-4a9a-b7cb-140c900591af.mp4
We need to add display; none; or visibility: hidden; for inactive slides.

2. When you change the icon, everything shifts:
Screenshot_1

3. When autoplay is enabled, the second slide is off:
Screenshot_2

4. Pause on hover not working for me.
5. Autoplay works on the backend, but not the frontend.
6. If you select a block and leave autoplay, this happens:
Screenshot_3

**Review by Marko64 — CHANGES_REQUESTED** [review]
All issues fixed. Noticed something else. This happens only if you have infinite loop enabled. Try enabling this option and then click on the slider:
https://user-images.githubusercontent.com/19425503/182800773-25c3af7f-284a-4321-ac71-6889a5f7fe9b.mp4

**Review by Marko64 — CHANGES_REQUESTED** [review]
Still something wrong when the infinite loop is enabled. Try clicking on the icon:
Screenshot_4

2. I think the edit view should show all the slides but it doesn't do that right now:
Screenshot_1

**Review by Marko64 — CHANGES_REQUESTED** [review]
One more thing :) 

It's hard to click these insert/add buttons:
Screenshot_1

Screenshot_2

**Review by Marko64 — CHANGES_REQUESTED** [review]
Sorry, found a couple more issues:

1. When you add a new slide, all slides become blank. 
https://user-images.githubusercontent.com/19425503/184316833-b9dfbfea-730c-44cf-85d9-02015db7e84c.mp4

2. In the Edit view, dot navigation isn't below the last slide, but above it:
Screenshot_1

**Review by Marko64 — CHANGES_REQUESTED** [review]
Everything looks good now except for those blank slides. I'm still getting that sometimes:
https://user-images.githubusercontent.com/19425503/184620571-6cabe0f7-15be-42ef-959f-0f75f732c5d0.mp4

Can't reproduce it all the time. Feels like something with the performance? Not sure.

**Review by Marko64 — APPROVED** [review]
You know what, I'm approving this now :) Good job.

**Review by Fybex — COMMENTED** [review]
Resolve conflicts, please @TeksPeks 😄

**Review by Fybex — CHANGES_REQUESTED** [review]
Bugs:
1. Autoplay with Fade transition: when slider arrives to last slide, it's repeating fade animation.
2. Navigation value: arrows, on frontend I have one big dot
image
When navigation: dots, I have:
image
3. Dots fill colour changing slide svg icon colour 
image
4. Dots active state custom colour changing not displaying (inline styles)
5. Dots border, background, shadow not working in active state
6. On responsive breakpoints, values from higher breakpoints are disappearing in Dots and Arrows accordion
image
7. Spacing make dots uncentred 
image
8. On adding arrow padding, right arrow hasn't expected position
image
9. On switching so s, xs breakpoints, content of slide is disappearing until clicking on slide
image
10. If set slider to full-width and then turn on loop, slides are broken (it's related with any size changes), also sometimes, with turned on loop, on unselect slider, slide is disappearing.
11. Transform is broken in slider and slide-maxi 
12. After deleting all slides, in toolbar I see that I have two slides in toolbar
image
13. After removing not last slide, slider until unselect and select looks like this:
image 

Thoughts:
1. Won't be better for UX if in navigation we will have switch for dots and arrows, easier IMO
2. Shouldn't dots, when outside is enable be in slider container anyway, but not in slides, not sure how even to do it, just thoughts 🤔 
3. Dots fill colour and arrows colour isn't responsive, it can be confusing for users to see him under responsive buttons
4. When slider - full-width, would be good to turn off arrows outside option 🤔 
5. I can see that box-shadow applies for slide-maxi, but I couldn't see it, do we need it then, or what I should to do to see it?
6. Move up, move down arrows should be move right, move left arrows as in row-maxi IMO
I mean these buttons:
image

**Review by Fybex — CHANGES_REQUESTED** [review]
Good job, you've run a marathon, there's a little sprint left 😄 

1. Hasn't been fixed: Dots active state custom colour changing not displaying (inline styles)
2. Can’t change dots stroke width in active state, I think, that this setting shouldn’t be available in active state.
3. After turning off dots border or box-shadow, styles which was added previously remains



4. Dots background doesn't work

P.S don't forget about unresolved comments from previous review

**Review by Fybex — CHANGES_REQUESTED** [review]
Problem with slider SVG color

[screen-capture (3).webm](https://user-images.githubusercontent.com/46112160/192595753-7ca74408-3333-4ca3-b8d9-fc53433ae1cb.webm)

**Review by Fybex — CHANGES_REQUESTED** [review]
Check icon settings again please, stroke width not affect active state, colours unchangeable

[something_wrong_with_slider_icons.webm](https://user-images.githubusercontent.com/46112160/192860121-51402c8c-a01e-439a-b42f-458ea143fbc1.webm)

**Review by Fybex — CHANGES_REQUESTED** [review]
One more thing, why we're showing line colour for shapes, for example? We shouldn't show options which isn't working with some svg types 👍

We aren't showing unnecessary information in `IconControl` or svg-icon-maxi `Icon colour`

**Review by Fybex — APPROVED** [review]
That day has come, I'm going to approve slider. Good job @TeksPeks 🎉 
Wish you have fewer comments in Final review 👍

**Review by moroz-art-dev — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
Much, much better

**Review by Naaaaiix — APPROVED** [review]
Awesome job 👏

**Pull request merged**
