### PR TITLE
Issue 4492 - Search icon position

### PR DESCRIPTION
**Pull request by Marko64**
Fixes button position for icon reveal skin - left.

Fixes #4492 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Insert search. Choose icon reveal skin, and set button position to left. Make sure it looks good.

**_ Pre-Code Testing _**

-   [ ] Insert search. Choose icon reveal skin, and set button position to left. Make sure it looks good.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
I guess, was better before, when Icon overlaps input field) 
image
need to make negative margin for field and padding


image
as like that) but margin and padding should depend on button's size

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) to add bigger padding for input field
image
2) when position center, search icon is not center
image
3) for right and center position
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/42ca534d-65b3-40c9-b825-8aa05773f99d
1) transition on backend for position:center is not working
2) for position:center - frontend
image

**Review by darimshlk — APPROVED** [review]

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/703c68de-aa99-4b4a-9851-f682b89aa771
Alignment for search is not center!
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/16568b49-1d98-4e1f-ae70-c0b82e9c5f69
take a look on close animation for center reveal search
reducing height, should reducing only width as for left and right

**Review by Olekrut — CHANGES_REQUESTED** [review]
left
image
right
image
center is not center again
image

**Review by Olekrut — CHANGES_REQUESTED** [review]
Almost) just need to make it center!
image

**Review by Olekrut — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Is this expected? 🤔 


https://user-images.githubusercontent.com/50477222/228464586-47ae14e1-491f-4f39-9495-d3e7f81cfc09.mp4

**Review by Olekrut — CHANGES_REQUESTED** [review]
image
need to add padding-right for input field

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — CHANGES_REQUESTED** [review]
Try to change the icon size, I don't think that's the expected result: :thinking: 

screenshot-wordpress local-2023 04 19-12_37_16

**Review by elzadj — APPROVED** [review]

**Pull request merged**
