### PR TITLE
Text maxi optimization

### PR DESCRIPTION
**Pull request by Naaaaiix**
Just a part of the work. This branch improves the speed and has optimized part of the code; also fixes #1181 , #1179 , #1178 and #1032

### CODE REVIEW

**Review by javadsamiee — COMMENTED** [review]
-When unbold a selected text in a list the other bolded texts will become unbold
_When I use B for some text it is active and for other, I should click twice to bold it


https://user-images.githubusercontent.com/65819265/112815947-16fb6380-9096-11eb-9c33-73b89fd17145.mov

**Review by javadsamiee — COMMENTED** [review]
I can not apply Bold to previous words into a sentence

https://user-images.githubusercontent.com/65819265/112983073-762ea600-9172-11eb-8c4c-c0368419d3fe.mov

**Review by Alejandro9kgm — APPROVED** [review]

**Review by javadsamiee — COMMENTED** [review]
we have this problem yet

https://user-images.githubusercontent.com/65819265/113298839-7b762700-9311-11eb-9cb1-def6b3253e75.mov

**Review by javadsamiee — APPROVED** [review]
Good job man, this version is very fast than old one I like it 👍🏻

**Pull request merged**
