### PR TITLE
Issue 5262 - Box shadow range values

### LINKED ISSUE #5262: Need to change max and min values for range control of box-shadow
### Description

Need to increase range for range control for values of box-shadow
Check for Horizontal, Vertical, Blur and Spread for all units

### Step-by-step reproduction instructions

1) max and min values bigger than can be set by range control

### Screenshots, screen recording, code snippet

https://jam.dev/c/b78d2c0c-1c11-4fd7-ae4c-657c307bc246

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Marko64**
Fixes #5262 

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Enhancements**
  - Expanded the range limits for box-shadow control, allowing for greater customization of shadow effects.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
It is not correct for EM and VW yet
https://jam.dev/c/dd03a779-642b-4a3b-b43e-f1fbebdd47b2
we can set -999 to 999, but by range only -300 to 300
we should have ability to set -999 to 999 by range as well

**Review by Olekrut — CHANGES_REQUESTED** [review]
The same bug for height, width, ( max, min as well ), margins, paddings, etc,, need to check all options with units
https://jam.dev/c/8449071f-d27d-49f8-9b5d-7330b67b591c

**Comment by Marko64** [comment]
If I remember correctly, this is not a bug but something we did on purpose.

Imagine you want to give a block a small margin. Instead of typing it in the input you can increase the range slider (less clicks, faster). However, if the limit is 39999px even slightly moving the slider will be too much for what you want to do.

We need to discuss if this is something we want or not want to do then.

**Comment by Marko64** [comment]
After discussing we decided to close this one and leave everything as is.

**Pull request closed without merging**
