### PR TITLE
Issue 712

### PR DESCRIPTION
**Pull request by javadsamiee**

### CODE REVIEW

**Review by Naaaaiix — APPROVED** [review]
The implementation is good, but has some issues on performance and lifecycle. As it works, I'm not going to request changes, and let's leave it as it is: we'll fix it in future 👍 Anyway, it will be readapted with #727 and with the future DB and API works. Good job!

**Review by Naaaaiix — COMMENTED** [review]
Bye

**Review by javadsamiee — COMMENTED** [review]
Magnificent and clean organization 👍

**Review by elzadj — CHANGES_REQUESTED** [review]
Bye

**Review by elzadj — CHANGES_REQUESTED** [review]
Bye

**Review by elzadj — APPROVED** [review]
Let's merge it. We always can catch and fix small bugs (if there are any) later.

**Pull request merged**
