### PR TITLE
Interaction builder new controls

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Added more controls, requests on which was commented here #3299 

Added controls: 
- svg icon colour
- svg icon background 
- svg icon line width
- svg icon border button icon
- background / layers
- position
- transform

Other changes:
- move all functions like `onChangeFill`, `onChangeStroke` inside `SvgColorControl`
- move button icon styles from `styles.js` to new helper - `getButtonIconStyles`
- move `getIconWithColor` from button `inspector.js` to extensions styles
- fix minor problem with responsive, replace `window.innerWidth < obj.breakpoint` to `window.innerWidth <= obj.breakpoint`

# How Has This Been Tested?
Checked all controls in general, checked if my movement of some SVG and button icon code didn't break their correct work.

# Test checklist

**_ Front/Back Testing _**

-   [x] Test all new IB controls
-   [x] Test if svg-icon-maxi settings works as usual
-   [x] Test if button icon settings works as usual
-   [x] Check that the settings work on frontend
-   [x] Check that backend works and saves the settings after the editor reload
-   [x] Same 1-4 points on responsive
-   [x] Test the block inside the grid (Container + Row + Column)
-   [x] Test the block as a standalone block
-   [x] Duplicate the block, test that the settings of the first do not affect the second
-   [x] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test all new IB controls
-   [ ] Test if svg-icon-maxi settings works as usual
-   [ ] Test if button icon settings works as usual
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — CHANGES_REQUESTED** [review]
SVG IB colours stay on page reload and do not go back to the original settings. 
To replicate the issue: Add one block and an SVG block. Change SVG colours using the other block. Check the frontend and go to edit again - you should see the IB colours there applied.

**Review by Marko64 — APPROVED** [review]
I think it works well now. 

The video block, for now, doesn't have any changes, but I assume that's yet to be added.

**Review by FitseTLT — CHANGES_REQUESTED** [review]
1. For button icons icon width, icon stroke width, icon color, icon padding doesn't work.
2. I don't think button hover trigger should be on the block wrapper. Though invisible wrapper is wider than the button and it is not the users will expect.

**Review by FitseTLT — CHANGES_REQUESTED** [review]
Ok. I see that the problem occurs when U use specifically our button preset 5. Can U check that?

**Review by FitseTLT — APPROVED** [review]
Interaction Builder is getting insane. Awesome Job.
Just have only two comments for the future, maybe.
1. It would be fantastic if we allow the users to see the interaction in the editor too.
2. I see there will definitely be interest to apply multiple interactions effects under a single interaction.

**Review by Naaaaiix — APPROVED** [review]
Interaction Builder is awesome, but this implementation's code is from other galaxy! 🪐 Congrats @Fybex 👏

**Pull request merged**
