### PR TITLE
Issue 4221 - `IconControl`: height fit-content option

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #4221 

# How Has This Been Tested?
Checked if new option
image
works as expected on responsive, hover, with different stroke-width, different icons.
### [code editor](https://github.com/maxi-blocks/maxi-blocks/files/10708378/fit-height-implementation-test.txt)

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points on responsive
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) https://jam.dev/c/bc81858f-23ad-4ee8-9c95-095a8762c31a
it is working perfect for icons with small height, but not sure, that it is working correct for icons with small width
2) I guess, will be need the same for width: fit-content
3) and I hope the same implementation will be for Icon Maxi

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/9db76d08-bc05-4094-8b91-45ff42883ee3
Disabling on responsive if disable for higher BP (maybe because it is base)

**Review by Olekrut — APPROVED** [review]

**Review by darimshlk — CHANGES_REQUESTED** [review]
https://jam.dev/c/14c5676f-dead-4c5c-bd50-d398220daf7f
Hover for icon is changing width

https://jam.dev/c/afd7ce1d-1ec2-40fa-91df-7b9b89c1a1e2
Stroke width for line icons same,changing width

**Review by darimshlk — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
Awesome job, thanks for adding tests. Left a comment, going to derive into a new issue!

**Pull request merged**
