### PR TITLE
Text Maxi

### PR DESCRIPTION
**Pull request by Naaaaiix**
This is a compilation of the different branches we've been reviewing lately and some minor fixes. Here's a list of all the implementations:
1. Improved speed performance: reduced the amount of renderings on Text Maxi. Now, the sidebar and the non-related elements on toolbar won't render when changing the content of Text Maxi, all based on a new part of code generated on `MaxiBlock` that allows avoid some renderings when sendings the attributes we don't want to be triggers for render. You'll find the code on [these lines](https://github.com/yeahcan/maxi-blocks/blob/8e090cc735d8496f2f129ce96d48d3aa2efc9fff/src/extensions/maxi-block/index.js#L72-L126). Also done the same for Text Maxi `inspector` and for general Toolbar 👍 
2. Fixed Custom Formats and generated integral tests for some of the most important functions related.
3. Fixed Lists options.
4. Fixed Link component on toolbar.
5. Fixed Paste functions: replaced the lifecycle to avoid unnecessary renderings.
6. Fixed undo/redo actions.
7. Implement Jest tests for unit, integral and End to End (puppeteer) testing.

There are some known issues, may not related with Text Maxi:
1- When pasting a piece of HTML with different parts that merges on different blocks, when doing undo, the white background start to disappear. This is related to the 'block-style' class implementation done on [this file](https://github.com/yeahcan/maxi-blocks/blob/master/src/extensions/attributes/index.js) that generates a record between the paste action and the last view for users. Will be elevate to a new issue and should be 'easy' to fix 👍 
2- Speed performance has been improved but may not be on the same level than native Gutenberg Paragraph block. There are some actions that we can do, but will need time and I, being honest, I need some rest from Text Maxi. Please, share your experience and will be elevate to a new issue as soon as we decide if it's or not fast enough.

Thanks for your reviews, happy coding fellas 😊

### CODE REVIEW

**Review by javadsamiee — COMMENTED** [review]
I see this error for the link

https://user-images.githubusercontent.com/65819265/116055057-924e3600-a691-11eb-8985-b0bacf547041.mov

**Review by Alejandro9kgm — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Auto-review (lol)
On selecting a word and without setting a link, set options, and the word gets the Link format 👍

**Review by Alejandro9kgm — COMMENTED** [review]
Can't change fount and gives a console error

https://user-images.githubusercontent.com/58038966/116225385-09e39a00-a752-11eb-8a7c-b8da5e8d6092.mp4

[console error.txt](https://github.com/yeahcan/maxi-blocks/files/6383746/console.error.txt)

**Review by Alejandro9kgm — COMMENTED** [review]
The width slide bar in text size is duplicated

https://user-images.githubusercontent.com/58038966/116243660-73ba6e80-a767-11eb-8606-3180703c6597.mp4

[code.txt](https://github.com/yeahcan/maxi-blocks/files/6384629/code.txt)


https://user-images.githubusercontent.com/58038966/116245669-7a49e580-a769-11eb-826f-aa999ea8f011.mp4

**Review by Alejandro9kgm — APPROVED** [review]

**Review by javadsamiee — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
