### PR TITLE
Issue 5393 - DC avatar support

### LINKED ISSUE #5393: Author's avatar bug
### Original issue

1) image
DC Image - avatar does not work
2) 
image
Impossible to choose avatar of author, related by cat, tag, etc...

### MVP solution

1

### How to fix it

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Fixed:
 - avatar for image author DC.
 
Added:
 - new field "Author's avatar" for posts and pages in image DC.
 image

Fixes #5393 

# How Has This Been Tested?
Checked how avatar for DC works.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Check avatar for author in DC.
-   [ ] Check "Author's avatar" for posts and pages.

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Introduced the "Author's avatar" option for dynamic content fields.
	- Added the ability to display user avatars within content.

- **Enhancements**
	- Improved image rendering and resizing handling in the editor.
	- Enhanced dynamic content rendering to better handle empty fields.

- **Bug Fixes**
	- Fixed an issue with incorrect content display when no dynamic content is found.
	- Adjusted condition checks for media content properties to ensure proper functionality.

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
1) for products need to add it as well
image
2) hide DC does not work for avatar, if there are not
image

**Comment by myroslavve** [comment]
> 1. for products need to add it as well
>    image

Products don't have author, so can't add this.

> 2. hide DC does not work for avatar, if there are not
>    image

fixed

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/e722c488-2b81-4de3-bf18-cd5b51fd5469
1) type Author > there is image, but it is hidden
2) type Author > there is not image, but it is not hidden

**Review by Olekrut — CHANGES_REQUESTED** [review]
We back to begin with this request, everything is visible.
With feature images is the same, btw.

I was thinking about this, maybe we should post this in a new issue and not hide the image if we don't have one, but just do some placeholder with a maxi logo "need to add image" and it won't break the patterns, btw.
@kyrapieterse what do you think?

**Comment by myroslavve** [comment]
> I was thinking about this, maybe we should post this in a new issue and not hide the image if we don't have one, but just do some placeholder with a maxi logo "need to add image" and it won't break the patterns, btw.

created an issue https://github.com/maxi-blocks/maxi-blocks/issues/5403, featured images and gallery images will be fixed there as well, only changing avatar here.

**Comment by myroslavve** [comment]
For avatars, made "Hide on frontend" switch hidden, and they are not hidden on frontend.

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Pull request merged**
