### PR TITLE
Issue 4368 - Replace bg shape image in copypasted block fix

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #4368 

# How Has This Been Tested?
Reproduced steps, which was described in issue, checked if it's working as expected

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the steps from issue
-   [ ] Test if shape layer works as expected

**_ Pre-Code Testing _**

-   [ ] Test the steps from issue
-   [ ] Test if shape layer works as expected
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/9618ebd7-4ad2-4676-8c26-861060c9fbbb
is not fixed for me

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/f079d6cf-96bc-4421-9908-cd51ce280ead
error after duplicate container, only on this brunch

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/53fd2484-ce2e-46e0-81ca-ce58ecd61a3f
is not fixed

**Review by Olekrut — CHANGES_REQUESTED** [review]
only on this brunch
if download light pattern and then download the same pattern of dark tone
Light pattern will have black BG Colour but in settings it is white
https://jam.dev/c/4e03da6c-23be-48ba-a55e-b0f0da8623c3

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/f1478080-3f00-4b4b-9d4d-54db78f699ae
sorry(((

**Review by Olekrut — APPROVED** [review]

**Review by Naaaaiix — APPROVED** [review]
Awesome job, lovely 👏

**Pull request merged**
