### PR TITLE
Issue 4234 - SelectControl default values

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
When the reset button was clicked, the value on `SelectControl` reset to `undefined` and instead of changing value to default `select`'s value remained the same, now it will fall back to new `defaultValue` prop or to first element if `defaultValue` is not passed.

Fixes #4234 

# How Has This Been Tested?
Checked that dropdown changes its value on reset.

# Test checklist

**_ Front/Back Testing _**

-   [x] Check that dropdown changes its value on reset.

**_ Pre-Code Testing _**

-   [ ] Check that dropdown changes its value on reset.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/49dbdacc-70ed-49ba-99db-4cb573b15ab9
font-weight in SC is resetting to 100, not to default 400 (regular)

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/2dc3b19c-d6f6-4bfa-b9b1-3b4506025114
is not fixed for me((

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/db7daa4a-8a1c-42e8-8b4e-adb496575af0
yy, almost) for topography globals should be 500 ( medium)

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/9669be91-76b7-4d77-8727-4e2007417059

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/05b934c9-d6c5-4868-8984-e47bc6a7a102

**Review by Olekrut — APPROVED** [review]
@TeksPeks yy, sorry, you are right)) well done))

**Review by Fybex — CHANGES_REQUESTED** [review]

**Review by Fybex — APPROVED** [review]

**Review by elzadj — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Awesome job, well done @TeksPeks ! Just a small comment 👍

**Pull request merged**
