### PR TITLE
Issue 4240 - fix wrong font weight on backend

### PR DESCRIPTION
**Pull request by myroslavve**
# Description
Fixed fonts loading incorrectly initially on backend.

Fixes #4240 

# How Has This Been Tested?
Added text maxi and checked that font weight looks same on editor and frontend.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Add text maxi and check that font weight looks same on editor and frontend.

**_ Pre-Code Testing _**

-   [ ] Add text maxi and check that font weight looks same on editor and frontend.
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Marko64 — CHANGES_REQUESTED** [review]
The backend seems to work now. Roboto 500 (medium) doesn't load on the frontend.

**Review by Olekrut — CHANGES_REQUESTED** [review]
Roboto - medium and Regular are similar, but in styles, everything is ok, idk...
https://jam.dev/c/46d841b5-cb73-49e9-b040-3b8f6b98838f
check font-weight after changes font-family. They are not updating even after update page. I guess, if font-family does not have weight chosen in previous family, font-weight should drops to default (400) or which picked in SC

**Review by Olekrut — APPROVED** [review]

**Review by Marko64 — CHANGES_REQUESTED** [review]
One more thing, and I think we're good. When you first change font-weight (only from the block settings, SC is correct), it changes the weight everywhere on the page, not just the text block.

https://user-images.githubusercontent.com/19425503/217476318-546818f9-1c26-4d46-8310-1cbe0d604f60.mp4

**Review by darimshlk — APPROVED** [review]

**Review by Marko64 — APPROVED** [review]

**Review by Naaaaiix — COMMENTED** [review]
Works good, but SC fonts aren't working on frontend 🤔 


https://user-images.githubusercontent.com/50477222/218991798-ffe4ef02-6b96-4789-8885-2cd4e8803da6.mp4

**Pull request merged**
